### ISSUE TITLE
How i can implement the ISOF function?

### ISSUE THREAD

**Issue by manusisnova** [object/Simple.OData.Client#100]
I am trying to get all records of specific Type derived from BaseType, OData V3 URL conventions says

5.1.2.4.26. isof

The isof canonical function has the following signatures

Edm.Boolean isof(type)
Edm.Boolean isof(expression, type)
If implemented the single parameter isof canonical function MUST return true if, and only if, the current instance is assignable to the type specified. If implemented the two parameter isof canonical function MUST return true if, and only if, the object referred to by the expression is assignable to the type specified.

The isofMethodCallExpr syntax rule defines how the isof function is invoked.

For example:

http://services.odata.org/Northwind/Northwind.svc/Orders?$filter=isof(NorthwindModel.BigOrder)
Returns only orders that are also BigOrders.

http://services.odata.org/Northwind/Northwind.svc/Orders?$filter=isof(Customer, NorthwindModel.MVPCustomer)
Returns only orders that have a customer that is a MVPCustomer.

**Comment by object** [comment]
Thanks, isof is not currently supported, but I will look into it asap.

**Comment by object** [comment]
Functions isof and cast are implemented in the version 4.4.0. Here are the docs:

https://github.com/object/Simple.OData.Client/wiki/Using-isof-and-cast

**Comment by manusisnova** [comment]
I tested and works well, but i cant use typed syntax because it does not recognize the derived type, i think is because it does not sent a model name.

**Comment by object** [comment]
Well, it's supposed to send the namespace. I need generated URI.

**Comment by manusisnova** [comment]
I double check my code and i discover my problem, when i use this syntax i had a error
var category = await odataclientTest .For<BaseCategory>("Simple_OData_ClientTest_DataModelCode_BaseCategory").Filter(c => c is Category).As<Category>("Simple_OData_ClientTest_DataModelCode_Category").FindEntryAsync();

but when i use this other one, everything gone fine

var category = await odataclientTest .For<Simple_OData_ClientTest_DataModelCode_BaseCategory>().Filter(c => c is Simple_OData_ClientTest_DataModelCode_Category).As<Simple_OData_ClientTest_DataModelCode_Category>().FindEntryAsync();

Thanks for your help

**Comment by object** [comment]
Good news!
