### ISSUE TITLE
Unbound function and bad request

### ISSUE THREAD

**Issue by matejgolob** [object/Simple.OData.Client#105]
I have unbound function, and call it like that:
await client.Unbound().Function("Test").Set(new { param = "abc" }).ExecuteAsScalarAsync<int>();

Everything works until I put some "special" character inside string, for example < or > (maybee some other to?). If I do this
await client.Unbound().Function("Test").Set(new { param = "<" }).ExecuteAsScalarAsync<int>();

I get exception: "bad request".

Any idea?

Matej

**Comment by object** [comment]
I ran some tests, and in my tests request URI was correctly built and escaped. So I need some more info to be able to reproduce the error. Can you check what URI is sent to the service? If URI is wrong, can you send it to me, I may also need a metadata file or at least that function definition.

**Comment by matejgolob** [comment]
What is simplest way to get generated URI? Fiddler?

**Comment by matejgolob** [comment]
Thanks for "hint". WIth fiddler I have extracted url. And It is escaped well. Then I've put generated uri into browser and I get error from mvc server:
A potentially dangerous Request.Path value was detected from the client 

So It looks it is odata server related not client.
Thanks for help...

**Comment by object** [comment]
Another hint: fiddler is great and the one I am using mostly, but you can also use the library OnTrace event:

            var client = new ODataClient(new ODataClientSettings(serviceUri)
            {
                OnTrace = (x, y) => Console.WriteLine(string.Format(x, y))
            });
