### ISSUE TITLE
Error adding library for Xamarin iOS projects

### ISSUE THREAD

**Issue by sameerbattoo** [object/Simple.OData.Client#111]
Issue:
In VS 2015 RC - After creating a new Xamarin iOS project for iPhone, I am unable to add the Simple.oData.Library PCL as a reference to the project. See the picture below for error details.
![step1- create a new xamarin iphone app](https://cloud.githubusercontent.com/assets/9197069/7586686/9f58cbbc-f8af-11e4-876d-b0ed317a4a6b.png)
![step2 vs 2015 rc - error - unable to install simple odata client pcl library](https://cloud.githubusercontent.com/assets/9197069/7586490/a72d0c38-f8ad-11e4-9ab3-1ec555a4be06.png)
In VS 2013 Update 4 -  After creating a new Xamarin iOS project for iPhone, I am able to add the Simple.oData.Library PCL as a reference to the project, but as soon as I want to build, I get errors. See the picture below for error details.
![step2 vs2013 update 4 - add simple odata client pcl successfully](https://cloud.githubusercontent.com/assets/9197069/7586673/900a8790-f8af-11e4-9d1a-2f7f242224f5.png)
![step3 vs2013 update4 - error - list of build errors](https://cloud.githubusercontent.com/assets/9197069/7586677/9542887a-f8af-11e4-86a6-92eee5d3458e.png)

**Comment by object** [comment]
Hi,

Thank you for a great issue report. I haven't tried Simple.OData.Client with VS 2015 and .NET 4.6, so I am not sure if this can have something to do with the error. Do you have a chance to try with VS 2013? In addition, you can check if you are able to add the reference to HttpClient (Microsoft.Net.Http) that Simple.OData.Client uses and that references Microsoft.Bcl. If you are able to add the reference, you can continue and refefence the Simple.OData.Client. If not, then I guess this is a problem with referencing HttpClient. Please let me know how it goes.

**Comment by sameerbattoo** [comment]
Hi Vagif,
Thanks for replying so quickly.
I had already tried in VS2013 Update 4 (as mentioned in my previous post). The result was that I was able to add the Simple.oData.Client PCL to the project, but it failed during the build.
After your reply, I tried adding the "Microsoft.Net.Http" to the project. It got added correctly and also I had no issues during build.
![vs2013update4 - microsoft net http added and built successfully](https://cloud.githubusercontent.com/assets/9197069/7587029/51e5ae6e-f8b3-11e4-817b-b076fc63efca.png)

**Comment by sameerbattoo** [comment]
HI Vagif,

Just for your info, in VS2013 Update 4, the errors that I get during the build after adding the Simple.oData.client successfully to the Xamarin iOS phone project, are as follows:

-- An assembly with the same identity 'System.IO, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.
-- An assembly with the same identity 'System.Runtime, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.
-- An assembly with the same identity 'System.Threading.Tasks, Version=2.6.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.

**Comment by object** [comment]
I think I've seen these error before. I will try to reproduce them later tonight, in the mean time you can try (in VS 2013 at least) to remove references to the mentioned assemblies if you see them in the reference list. There can occur some confusion for certain PCL profiles.

When it comes to VS 2015, after you successfully added Microsoft.Net.Http, did you try adding Simple.OData.Client? Did it fail with the same error?

**Comment by object** [comment]
It can also help me investigating the error if you can send me a failing project (or an extract from it) to vagif.abilov@gmail.com.

**Comment by object** [comment]
Apparently, when it comes to VS 2015 RC, this is NuGet 3.0 bug. See this thread:

http://forums.xamarin.com/discussion/40709/unable-to-add-json-net-to-a-xamarin-ios-project-under-visual-studio-2015
