### ISSUE TITLE
Resuse of http connection

### ISSUE THREAD

**Issue by Fabian-Schmidt** [object/Simple.OData.Client#112]
Hello,
I am using the Simple.OData.Client in a scenario where i do thousand of odata requests. I noticed that for each of these requests it does a TCP handshake and a SSL handshake. This adds up and is not ideal.

So i have created a change to reuse the http session to reuse open connection and therefor avoid a lot of the handshakes: https://github.com/Fabian-Schmidt/Simple.OData.Client/commit/4de42c09a00f967327a8e6894485376e8f249868

I am using it in a multithreading environment and did not had any issues.

The downside of this solution is that it introduces the IDisposable interface. Therefore all existing implementations should be changed to create the instance in a using statement.
An alternative solution could be a seperate ODataClient class which resuses the http to avoid 'breaking' existing code.

Regards,
Fabian

**Comment by object** [comment]
Hi, and thank you for the suggestion.

I will investigate this issue. Yes, if it's a breaking change it requires doing a major version upgrade, and I would like to keep it compatible for scenarios that don't need to reuse the session. I will try to figure out if it's possible to achieve the same result without making IODataClient disposable.

**Comment by object** [comment]
I believe it should be possible to reuse HttpClient now. There is a pre-release version of 4.6 available at MyGet: https://www.myget.org/feed/Packages/simple-odata-client

It extends ODataClientSettings with ReuseHttpConnection property (false by default).

Please check it out.

**Comment by object** [comment]
Implemented in 4.6.0.
