### ISSUE TITLE
using ModernHttpClient as a replacement for standard HttpClient in Xamarin projects

### ISSUE THREAD

**Issue by ahmedkhan25** [object/Simple.OData.Client#113]
Hi, thanks again for your work on simple odata..this is an invaluable client especially for mobile!

Wanted to see if its possible to use the Xamarin ModernHttpClient component in place of the standard   HttpClient inside of simple odata client 

https://components.xamarin.com/view/modernhttpclient

it's  measurably faster on native platforms because it uses native network implementations 

" brings the latest platform-specific networking libraries to Xamarin applications via a custom HttpClient handler. Write your app using System.Net.Http, but drop this library in and it will go drastically faster. This is made possible by two native libraries:

On iOS, via NSURLSession
On Android, via OkHttp 1.5 "

**Comment by object** [comment]
Hi,
Thank you for the suggestion. This might actually work already. ODataClientSettings class has OnCreateMessageHandler property that can be assigned to a NativeMessageHandler as suggested in ModernHttpClient docs. Can you check that this is what you need?

**Comment by ahmedkhan25** [comment]
Thanks - I followed your advice and went ahead and created a simple test app that uses both ClientHandlers and tested performance -for refernce I uploaded my code here -it does appear to be faster (saved 5 seconds off an 800 count query) in Xamarin.iOS
see example code here:
https://github.com/ahmedkhan25/NativeODATAClientTester/blob/master/README.md

**Comment by object** [comment]
That's a huge save! Thanks for sharing the code.
