### ISSUE TITLE
Exception when annotations object is passed into FindEntriesAsync method and single entry returned

### ISSUE THREAD

**Issue by walk0r** [object/Simple.OData.Client#115]
Null reference. Stacktrace below:

   at Simple.OData.Client.ODataFeedAnnotations.CopyFrom(ODataFeedAnnotations src)
   at Simple.OData.Client.ODataClient.<>c__DisplayClass3a.<FindEntriesAsync>b__37(ODataResponse x)
   at Simple.OData.Client.ODataClient.<ExecuteRequestWithResultAsync>d__1a7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Simple.OData.Client.ODataClient.<FindEntriesAsync>d__3c.MoveNext()

Also - I didn't find a way to read odata annotations on entries (@odata.Id, odata.editlink, etc) - is it possible?

EDIT: ok, I found that they are just ignored. Is it possible that you add them conditionally as you did with Type (IncludeResourceTypeInEntryProperties property)?

**Comment by object** [comment]
Thank you for the bug report. I will investigate the issue and get back to you.

**Comment by object** [comment]
I just pushed version 4.6.1 that should fix the exception with annotations. I will have a look at how to include annotations in entries.

**Comment by walk0r** [comment]
Thank you!

**Comment by object** [comment]
I pushed version 4.7 that adds support for entry annotations in both typed and untyped version. These tests contain a usage example for typed scenario: https://github.com/object/Simple.OData.Client/blob/v4/Simple.OData.Client.IntegrationTests/TripPinTests.cs

**Comment by walk0r** [comment]
I checked the results, but that's not exactly what I needed. Correct Id is only set when I request single entry, but not the collection (in this case the only Id belongs to set). See, when I request People using link like
http://services.odata.org/V4/%28S%28bnk2wlis0ffc5jenjgqhh3bs%29%29/TripPinServiceRW/People - each entry has metadata:

@odata.id": "http://services.odata.org/V4/(S(bnk2wlis0ffc5jenjgqhh3bs))/TripPinServiceRW/People('russellwhyte')",
      "@odata.etag": "W/\"08D26A681EB2EA9C\"",
      "@odata.editLink": "http://services.odata.org/V4/(S(bnk2wlis0ffc5jenjgqhh3bs))/TripPinServiceRW/People('russellwhyte')",
      "UserName": "russellwhyte",

@odata.id": "http://services.odata.org/V4/(S(bnk2wlis0ffc5jenjgqhh3bs))/TripPinServiceRW/People('scottketchum')",
      "@odata.etag": "W/\"08D26A681EB2EA9C\"",
      "@odata.editLink": "http://services.odata.org/V4/(S(bnk2wlis0ffc5jenjgqhh3bs))/TripPinServiceRW/People('scottketchum')",
      "UserName": "scottketchum",

And I actually need all this data accessible.

**Comment by object** [comment]
I'll check it out.

**Comment by object** [comment]
I checked the code and I can see that I am getting all these annotations. Can you make sure you are doing the following:

1. Create ODataClient with settings that have IncludeAnnotationsInResults set to "true"?
2. Either use untyped syntax or define a property of ODataEntryAnnotations in your entity type, e.g.:

    class Person
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string[] Emails { get; set; }
        public List<Location> AddressInfo { get; set; }
        public PersonGender Gender { get; set; }
        public long Concurrency { get; set; }

        public IEnumerable<Person> Friends { get; set; }
        public IEnumerable<Trip> Trips { get; set; }
        public IEnumerable<Photo> Photos { get; set; }
        public ODataEntryAnnotations Annotations { get; set; }
    }

**Comment by walk0r** [comment]
Ok, totally my fault. I can only use untyped version of requests, so I was expecting data to appear somewhere in ODataFeedAnnotation.InstanceAnnotations, not in dictionary. I see them now.
However, how can I extract annotations from dictionary now? Their property name is unknown to me. And it may be quite expensive to me to check every value if it of specific type.

**Comment by walk0r** [comment]
In fact, I've already implemented all of this (using almost the same approach as you did, but with 1 additional method - "ODataEntryAnnotations FromEntry(IDictionary<string, object>" in ODataEntryAnnotations)) in 4.5.4 version, because later ones (starting 4.6.0) fail randomly with socket errors for my requests. I don't know if it's a library, or my service.

**Comment by object** [comment]
I wouldn't use ODataFeedAnnotations for individual entries. The entry annotations are copied to an instance of ODataEntryAnnotations class and included in a property bag with the name __annotations, so they should be accessible in untyped version. It shouldn't be more expensive to extract entry annotations from enrty properties than from anywhere else.

**Comment by walk0r** [comment]
That's again, not what I meant. My point is that hardcoding key "__annotations" somewhere in external application isn't nice at all. And the other option is iterate dictionary values and try to find value which is of type ODataEntryAnnotations (which may be quite expensive) in case of huge amount of records with hundreds of fields.

**Comment by walk0r** [comment]
Anyway, that's up to you. Thanks.

**Comment by object** [comment]
I might be overlooking something but I don't see a more elegant way of supplying this information. Untyped library API returns collection of IDictionary of string and objects, so all data must be packed there one way or another. And the typed version traverses type properties, so it feels natural to extend it that way.

But if you have an alternative way that you prefer, can you share some code?

**Comment by walk0r** [comment]
Hey! I apologize, I haven't noticed your reply. The way of supplying information for untyped version is good, however my point was that it is hard to use - even if it's untyped version, metadata is something which IS typed. And so there must be a nice and easy way to extract it from that dictionary, which becomes complicated as it's key is unknown (private or internal somewhere in the library).
So in fact I did 1 additional change to your implementation - I've added a method to ODataEntryAnnotations class (I called it ODataEntryMetadata):
```
    public static bool TryRemoveFromResponse(IDictionary<string, object> response, out ODataEntryMetadata metadata)
    {
      if (response != null && response.ContainsKey(FluentCommand.ResourceEntryMetadataLiteral))
      {
        metadata = response[FluentCommand.ResourceEntryMetadataLiteral] as ODataEntryMetadata;
        response.Remove(FluentCommand.ResourceEntryMetadataLiteral);
      }
      else
        metadata = (ODataEntryMetadata) null;
      return metadata != null;
    }
```
This allows to read metadata value and at the same time removes it from collection.

**Comment by object** [comment]
I see, it makes sense. I am currently doing large changes for the forthcoming version 5, and I believe I've done similar things there. Once I have a stable version I will send you a link to the source so you can have a look and give a feedback.

**Comment by walk0r** [comment]
Superb! Thank you.
