### ISSUE TITLE
Paging and filtering on Unbound functions

### ISSUE THREAD

**Issue by johanparmar** [object/Simple.OData.Client#116]
Hi,

I have noticed that you cant do any paging(i.e .FindEntriesAsync(...))  or filtering (i.e .Filter(...)). Is there nay reason for this?

**Comment by object** [comment]
The client supports standard OData Top and Skip clauses. Aren't they sufficient?

**Comment by johanparmar** [comment]
I'm doing paging on the server side but I suppose I can use top and and skip instead. 
But for filtering it won't help but maybe  I should do this in the function on the server side...

**Comment by object** [comment]
If you want full control over paging you might consider doing it using functions or other custom functionality. But for common client-side paging implementation using standard OData clauses Top and Skip is often sufficient. Simple.OData.Client stays close to OData protocol so I don't think it will ever offer any non-standard paging possibilities.

**Comment by johanparmar** [comment]
OK. Thanks for the answer!
 I converted the unbound methods to bound.

**Comment by vytasg** [comment]
Filter would be useful for Unbound functions too, instead of introducing a new method. e.g. there is  GetEmployees method which returns a DTO, not an entity, so instead of parametrising the method $filter does the job if we write a query, but it is not possible with Simple.OData.Client currently
