### ISSUE TITLE
Simple.OData.Client 4.7.2 allows Microsoft.OData.Core >= 6.11, but requires 6.12

### ISSUE THREAD

**Issue by sp1ze** [object/Simple.OData.Client#118]
Once installing or updating simple odata client it allows Microsoft OData.Core 6.11 or higher. But I was receiving the following inner exception: "{"Could not load file or assembly 'Microsoft.OData.Core, Version=6.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Microsoft.OData.Core, Version=6.12.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}".

I solved it by updating ODataLib from 6.11 to 6.12 manually.

**Comment by sp1ze** [comment]
Closing the issue due to own fault. I had wrong information in the .config file that required 6.12 version.

**Comment by object** [comment]
Great!
