### ISSUE TITLE
Preference return=representation and return=minimal

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#119]
Hi,

Currently, when performing a GET request using the FindEntriesAsync(annotations) method, the header always sets the Preference to return=minimal. From Fiddler, you will find that it generates the information below:

GET /V4/TripPinServiceRW/People?$select=UserName,FirstName,LastName&$count=true HTTP/1.1
Prefer: return=minimal
Accept: application/json, application/xml, application/text
Host: services.odata.org

Is Prefer: return = minimal correct? According to the OData documentation http://docs.oasis-open.org/odata/odata/v4.0/os/part1-protocol/odata-v4.0-os-part1-protocol.html#_Toc372793631

In OData, return=representation or return=minimal is defined for use with a POST, PUT, or PATCH Data Modification Request other than to a stream property, or to an Action Request. Specifying a preference of return=representation or return=minimal in a GET or DELETE request, or any request to a stream property, SHOULD return a 4xx Client Error.

It also states that:

A preference of return=minimal requests that the service invoke the request but does not return content in the response. 

Am I misunderstanding what the specification means or this is a bug in the FindEntriesAsync method?

Thanks in advance!

**Comment by object** [comment]
Thank you for the observation. I will investigate the issuea and come back to you. It will takes some time though because I am currently on vacation.

**Comment by mwchan** [comment]
Thanks! Looking forward to your reply. Have a good holiday!

**Comment by object** [comment]
You were right about correct usage of Preference headers. The fix will be included in version 4.8 (to be released in a few days).

**Comment by object** [comment]
Fixed in 4.8.
