### ISSUE TITLE
Unable to insert new entry that has navigation link to singleton

### ISSUE THREAD

**Issue by majiccode** [object/Simple.OData.Client#120]
I'm new to OData and this great library but I'm trying to do something quite simple here. Insert an item that has a link to another item that happens to be a singleton. The code looks like so:

 var env = client.For("Environment").FindEntryAsync().Result;
 await client.For("WebCapabilities").Set(new { id = "wc1", Environment = env } ).InsertEntryAsync();

Where:
"Environment" is a navigation property on the "WebCapability" entity type. 

The error produced is a NullReferenceException in RequestWriter.cs at :
 var linkSet = _model.SchemaElements
                        .Where(x => x.SchemaElementKind == EdmSchemaElementKind.EntityContainer)
                        .SelectMany(x => (x as IEdmEntityContainer).EntitySets())
                        .BestMatch(x => x.EntityType().Name, linkTypeWithKey.Name, _session.Pluralizer);
                    var formattedKey = _session.Adapter.GetCommandFormatter().ConvertKeyValuesToUriLiteral(
                        linkKey.ToDictionary(x => x.Name, x => linkEntry[x.Name]), true);
                    linkUri = linkSet.Name + formattedKey;

The problem seems to be that the code only iterates over entity sets so ignores all the Singletons contained within the Entity Container.

Is this desired behavior or a bug? I would love to know if their is a workaround to this or will it require a fix to the code ?

Thanks,
paul.

n.b:
Excluding setting Environment would produce the following odata response as you would expect:
HTTP/1.1 400 Bad Request
Server: Apache-Coyote/1.1
Content-Language: en
OData-Version: 4.0
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 02 Jul 2015 14:31:36 GMT
Connection: close

6a
{"error":{"code":"2000","message":"The request does not specify the navigation links for 'Environment'."}}
0

**Comment by object** [comment]
Thank you for a comprehensive bug report. Yes, this is a bug. Should be easy to fix but I am away now so it may take some time until the new version is available. I will let you know. Unfortunately I don't think there is a workaround for this.

**Comment by majiccode** [comment]
Thanks, looking forward to the new version :)

**Comment by object** [comment]
I believe I've made a fix. You can test the pre-release of the forthcoming version 4.7.3 by downloading a package from Myget:

https://www.myget.org/gallery/simple-odata-client

Please give it a try.

**Comment by majiccode** [comment]
Hi, many thanks for that fix. I've tested the changes. It didn't quite work but perhaps this is not a fault of your changes? Have a look and see what you think...

When using my sample code with your fixes the request body now looks like this:

{  "@odata.type":"#Tridion.WebDelivery.Platform.WebCapability","id":"wc1","Environment@odata.bind":"http://cdwstest.ams.dev:8082/test/discovery.svc/Environment('DefaultEnvironment')"
}

At first glance it looks good but sadly the service returns a bad request here because the singleton Environment can't handle the fact a key predicate was passed. If I manually browse to http://cdwstest.ams.dev:8082/test/discovery.svc/Environment('DefaultEnvironment') it fails. If you loose the key predicate it works so changing the bit above to this:
"Environment@odata.bind":"http://cdwstest.ams.dev:8082/test/discovery.svc/Environment"

Do you think this is a problem with the library or perhaps *shudder* its an issue with my odata 4 service?

Thanks again
paul

**Comment by object** [comment]
Hi Paul,
Looks you hit another singleton-related issue. Will work on it, thanks for the notice.

**Comment by object** [comment]
Hi,
I've just pushed a new pre-release version (at myget.org) that distinguishes between singleton and entity set. You can try that, and in case you have no other collection than singleton with Environment entity type, it should work. But if in addition to Environment there are entity sets that have the same type, for the time being the only way to hint that singleton should be taken is to use typed syntax and define two types: for entity set and for singleton, e.g.:

class Environment {...}
class OtherEnvironment : Environment {}

Then Simple.OData.Client will be able to choose the right collection when creating a link. But if you only have a single (singleton) collection of Environment type, this shouldn't be an issue.

Let me know how it goes.

**Comment by object** [comment]
Did you have a chance to test the new version?

**Comment by majiccode** [comment]
Ahh sadly no, I'll hopefully try it out on monday for you and let you know.

**Comment by majiccode** [comment]
Just tested the changes and it works fine now :)

Many thanks
Paul
