### ISSUE TITLE
Not able to call action having parameters and getting {"Object reference not set to an instance of an object."} exception.

### ISSUE THREAD

**Issue by parthivp** [object/Simple.OData.Client#123]
I am using Simple.Odata.client 4.7.2. I have a requirement to call Action from the Odata service, which is working fine if I make call using other http client like Rest client etc. But when I try to do that with Simple.Odata.Client I am getting object reference not set exception.

Here is the code I am using to make request:
var clientSettings = new ODataClientSettings("http://localhost.fiddler:21900/odata/",
                new NetworkCredential("testusername","testpassword"));
clientSettings.PayloadFormat = ODataPayloadFormat.Json;
clientSettings.OnTrace = (s, objects) => Console.WriteLine(string.Format(s, objects));
clientSettings.BeforeRequest = message => Console.WriteLine(message.Content);

var client = new ODataClient(clientSettings);

var result = await client.For<Factory>().Key(1).Action("CopyFactory").Set(new { test = "" }).ExecuteAsSingleAsync();

If I make a filter request etc.. then that is working perfect, but when I do this action request, then it is not even fire before request event or log in fiddler.

Also If I do not specify parameters (i.e. using Set) then it is working perfect, but I want parameters in the my case.

Here is also the definition of Action at the service side, just for reference 

[HttpPost]
public async Task<IHttpActionResult> CopyFactory([FromODataUri] string key, ODataActionParameters parameters)
{
            var newFactory = new Factory();
            return Ok(newFactory);
}

I am not sure if I am missing something or not doing the rightway.

I request you to kindly look into this and guide me.

Thanks in advance.

Parthiv

**Comment by object** [comment]
Thank you for reporting this issue. This is definitely a bug (anything that raises NullReferenceException must be some sort of bug), and I will look into it.

**Comment by object** [comment]
Can you provide me with the metadata document for your OData service?

**Comment by parthivp** [comment]
Hello Vagif,

Please find metadata for the service as below :

<edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" Version="1.0">
<edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:DataServiceVersion="3.0" m:MaxDataServiceVersion="3.0">
<Schema xmlns="http://schemas.microsoft.com/ado/2009/11/edm" Namespace="ProductService.Models">
<EntityType Name="Factory">
<Key>
<PropertyRef Name="FactoryId"/>
</Key>
<Property Name="FactoryId" Type="Edm.String" Nullable="false"/>
<Property Name="ShortName" Type="Edm.String"/>
<Property Name="LongName" Type="Edm.String"/>
<NavigationProperty Name="ProductLines" Relationship="ProductService.Models.ProductService_Models_Factory_ProductLines_ProductService_Models_ProductLine_ProductLinesPartner" ToRole="ProductLines" FromRole="ProductLinesPartner"/>
</EntityType>
<EntityType Name="ProductLine">
<Key>
<PropertyRef Name="ProductLineId"/>
<PropertyRef Name="FactoryId"/>
</Key>
<Property Name="FactoryId" Type="Edm.String" Nullable="false"/>
<Property Name="ProductLineId" Type="Edm.String" Nullable="false"/>
<Property Name="ShortName" Type="Edm.String"/>
<Property Name="LongName" Type="Edm.String"/>
</EntityType>
<EntityType Name="Product">
<Key>
<PropertyRef Name="ID"/>
<PropertyRef Name="FactoryId"/>
<PropertyRef Name="ProductLineId"/>
</Key>
<Property Name="ID" Type="Edm.String" Nullable="false"/>
<Property Name="Name" Type="Edm.String"/>
<Property Name="Price" Type="Edm.Decimal" Nullable="false"/>
<Property Name="Category" Type="Edm.String"/>
<Property Name="SupplierId" Type="Edm.String" Nullable="false"/>
<Property Name="FactoryId" Type="Edm.String" Nullable="false"/>
<Property Name="ProductLineId" Type="Edm.String" Nullable="false"/>
<NavigationProperty Name="Supplier" Relationship="ProductService.Models.ProductService_Models_Product_Supplier_ProductService_Models_Supplier_SupplierPartner" ToRole="Supplier" FromRole="SupplierPartner"/>
<NavigationProperty Name="ProductLine" Relationship="ProductService.Models.ProductService_Models_Product_ProductLine_ProductService_Models_ProductLine_ProductLinePartner" ToRole="ProductLine" FromRole="ProductLinePartner"/>
</EntityType>
<EntityType Name="Supplier">
<Key>
<PropertyRef Name="Key"/>
</Key>
<Property Name="Key" Type="Edm.String" Nullable="false"/>
<Property Name="Name" Type="Edm.String"/>
</EntityType>
<EntityType Name="ProductRating">
<Key>
<PropertyRef Name="ID"/>
</Key>
<Property Name="ID" Type="Edm.Int32" Nullable="false"/>
<Property Name="Rating" Type="Edm.Int32" Nullable="false"/>
</EntityType>
<Association Name="ProductService_Models_Factory_ProductLines_ProductService_Models_ProductLine_ProductLinesPartner">
<End Type="ProductService.Models.ProductLine" Role="ProductLines" Multiplicity="*"/>
<End Type="ProductService.Models.Factory" Role="ProductLinesPartner" Multiplicity="0..1"/>
</Association>
<Association Name="ProductService_Models_Product_Supplier_ProductService_Models_Supplier_SupplierPartner">
<End Type="ProductService.Models.Supplier" Role="Supplier" Multiplicity="0..1"/>
<End Type="ProductService.Models.Product" Role="SupplierPartner" Multiplicity="0..1"/>
<ReferentialConstraint>
<Principal Role="Supplier">
<PropertyRef Name="Key"/>
</Principal>
<Dependent Role="SupplierPartner">
<PropertyRef Name="SupplierId"/>
</Dependent>
</ReferentialConstraint>
</Association>
<Association Name="ProductService_Models_Product_ProductLine_ProductService_Models_ProductLine_ProductLinePartner">
<End Type="ProductService.Models.ProductLine" Role="ProductLine" Multiplicity="0..1"/>
<End Type="ProductService.Models.Product" Role="ProductLinePartner" Multiplicity="0..1"/>
<ReferentialConstraint>
<Principal Role="ProductLine">
<PropertyRef Name="ProductLineId"/>
<PropertyRef Name="FactoryId"/>
</Principal>
<Dependent Role="ProductLinePartner">
<PropertyRef Name="FactoryId"/>
<PropertyRef Name="ProductLineId"/>
</Dependent>
</ReferentialConstraint>
</Association>
</Schema>
<Schema xmlns="http://schemas.microsoft.com/ado/2009/11/edm" Namespace="Default">
<EntityContainer Name="Container" m:IsDefaultEntityContainer="true">
<EntitySet Name="Factories" EntityType="ProductService.Models.Factory"/>
<EntitySet Name="ProductLines" EntityType="ProductService.Models.ProductLine"/>
<EntitySet Name="Products" EntityType="ProductService.Models.Product"/>
<EntitySet Name="Suppliers" EntityType="ProductService.Models.Supplier"/>
<EntitySet Name="Ratings" EntityType="ProductService.Models.ProductRating"/>
<EntitySet Name="FactoryEntity" EntityType="ProductService.Models.Factory"/>
<FunctionImport Name="RateProduct" ReturnType="Edm.Double" IsBindable="true" m:IsAlwaysBindable="true">
<Parameter Name="bindingParameter" Type="ProductService.Models.Product"/>
<Parameter Name="Rating" Type="Edm.Int32" Nullable="false"/>
</FunctionImport>
<FunctionImport Name="CopyFactory" ReturnType="ProductService.Models.Factory" IsBindable="true" EntitySet="FactoryEntity" m:IsAlwaysBindable="true">
<Parameter Name="bindingParameter" Type="ProductService.Models.Factory"/>
<Parameter Name="sourceFactoryId" Type="Edm.String" FixedLength="false" Unicode="false"/>
<Parameter Name="targetFactoryId" Type="Edm.String" FixedLength="false" Unicode="false"/>
<Parameter Name="targetFactoryNameShort" Type="Edm.String" FixedLength="false" Unicode="false"/>
</FunctionImport>
<AssociationSet Name="ProductService_Models_Factory_ProductLines_ProductService_Models_ProductLine_ProductLinesPartnerSet" Association="ProductService.Models.ProductService_Models_Factory_ProductLines_ProductService_Models_ProductLine_ProductLinesPartner">
<End Role="ProductLinesPartner" EntitySet="Factories"/>
<End Role="ProductLines" EntitySet="ProductLines"/>
</AssociationSet>
<AssociationSet Name="ProductService_Models_Product_Supplier_ProductService_Models_Supplier_SupplierPartnerSet" Association="ProductService.Models.ProductService_Models_Product_Supplier_ProductService_Models_Supplier_SupplierPartner">
<End Role="SupplierPartner" EntitySet="Products"/>
<End Role="Supplier" EntitySet="Suppliers"/>
</AssociationSet>
<AssociationSet Name="ProductService_Models_Product_ProductLine_ProductService_Models_ProductLine_ProductLinePartnerSet" Association="ProductService.Models.ProductService_Models_Product_ProductLine_ProductService_Models_ProductLine_ProductLinePartner">
<End Role="ProductLinePartner" EntitySet="Products"/>
<End Role="ProductLine" EntitySet="ProductLines"/>
</AssociationSet>
<AssociationSet Name="ProductService_Models_Factory_ProductLines_ProductService_Models_ProductLine_ProductLinesPartnerSet" Association="ProductService.Models.ProductService_Models_Factory_ProductLines_ProductService_Models_ProductLine_ProductLinesPartner">
<End Role="ProductLinesPartner" EntitySet="FactoryEntity"/>
<End Role="ProductLines" EntitySet="ProductLines"/>
</AssociationSet>
</EntityContainer>
</Schema>
</edmx:DataServices>
</edmx:Edmx>

**Comment by parthivp** [comment]
Hey 

I am not able to sent it via attaching the file or copy those lines in here. Could you please let me know your email address, I can quickly send metadata file over there.

Thanks,
Parthiv

**Comment by object** [comment]
Please send it to vagif.abilov@gmail.com

**Comment by object** [comment]
Hi, I've improved error reporting so in such situtation you won't get NullReferenceException, but it will still fail because there is no parameter "test" for action "CopyFactory". The action "CopyFactory" contains 4 parameters and you are supposed to set the combination of them. So even though the error message was wrong, the error is as expected.

**Comment by parthivp** [comment]
Thanks for your help.
