### ISSUE TITLE
Adding custom query option

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#124]
Hi,

How do I add a custom query option? For example, to get a list of Customers, I am doing the following:

var client = new ODataClient("http://myOdataService");
var query = client.For("Customers").Select(new string[]{"Name"});

which would generate the following command:

Customers?$select=Name

How do I add a custom query option to generate the command below?

Customers?MyCustomOption=blah$select=Name

If it is not possible, can I generate the command and somehow append my custom option as part of the query?

Thanks in advance!

**Comment by mwchan** [comment]
Just wanted to add that I think it relates to this part of the specification:

6.1 Query Option Extensibility
Query options within the request URL can control how a particular request is processed by the service.
OData-defined system query options are prefixed with "$". Services may support additional custom query options not defined in the OData specification, but they MUST NOT begin with the "$" or "@" character.
OData services SHOULD NOT require any query options to be specified in a request. Services SHOULD fail any request that contains query options that they do not understand and MUST fail any request that contains unsupported OData query options defined in the version of this specification supported by the service.
In many cases OData services return URLs to identify resources that are later requested by clients. Where possible, interoperability is enhanced by providing all identifying information in the path portion of the URL. However, clients should be prepared for such URLs to include custom query options and propagate any such custom query options in future requests to the identified resource.

**Comment by object** [comment]
Thank you for the suggestion. Currently there is no support for custom query options in the library API (I will look into it for the next major release, version 5). However, you should be able to append it to an OData command: 
var commandText = await client.For("Customer").Select(new string[] {"Name"}).GetCommandTextAsync();
var result = await client.FindEntriesAsync(commandText);

The disadvantage of this approach is that you will get back not strongly typed result (a Dictionary of string*object instead of a typed collection).

**Comment by mwchan** [comment]
Thank you! Looking forward to it!

**Comment by object** [comment]
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7. This feature is available there.

**Comment by mwchan** [comment]
Thanks!!!
