### ISSUE TITLE
How do you do an OR for filters?

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#125]
Hi,

I am trying to chain filters with an OR instead of an AND but it does not look like its supported?

Code:
client.For("People").Filter(string.Format("{0} {1} '{2}' or", "LastName",
                "eq", "Ketchum")).Filter(string.Format("{0} {1} '{2}'", "LastName",
                "eq", "Guess"));

Url that I am trying to produce:
http://services.odata.org/V4/(S(xcbklsncj3tzf3qup2qwrrcz))/TripPinServiceRW/People?$filter=LastName%20eq%20%27Ketchum%27%20or%20LastName%20eq%20%27Guess%27

But I am getting an AND appended and it looks like it is hardcoded in FluentCommand.

 public FluentCommand Filter(string filter)
        {
            if (IsBatchResponse) return this;

            if (string.IsNullOrEmpty(_details.Filter))
                _details.Filter = filter;
            else
                _details.Filter = string.Format("({0}) and ({1})", _details.Filter, filter);
            return this;
        }

Is it possible to perform an OR?

Thanks!

**Comment by mwchan** [comment]
I was also wondering if it is currently possible to do filtering at the expanded entity level. For example, going from People -> Friends and filtering on the last name of a friend.

**Comment by object** [comment]
If you chain multiple Filter clauses, you will get them combined with AND. In order to use OR you should combine them in a single Filter clause.

**Comment by object** [comment]
Yes, it's possible to do filtering on expanded entity level, you can find some examples in test files in the source code. For such complex queries I'd recommend to use dynamic or typed syntax, it will be much easier to write expressions.

**Comment by mwchan** [comment]
Thanks for the quick response!
