### ISSUE TITLE
Retrieving String from custom OData function

### ISSUE THREAD

**Issue by tbaart** [object/Simple.OData.Client#130]
When I retrieve any other object from my API using the V4 Simple OData Client, everything works fine.
However, whenever I retrieve a string like this:

string result = await client.Unbound\<string\>().Function("SomeFunctionThatReturnsString").Set(new { someInt = 3 }).ExecuteAsSingleAsync();

I get an exception:

"System.InvalidOperationException: Unable to create an instance of type String that does not have a default constructor."

While it's true that System.String has no default consstructor, it seems weird that retrieving a simple string returns this exception. It seems even weirder that no one has reported this yet, so I am also very open to the idea that I'm simply messing up somewhere. If I am I wouldn't know where though.

**Comment by object** [comment]
Thank you for the issue report. Pretty weird, indeed. Will check this out.

**Comment by tbaart** [comment]
Yeah, so I found out that I needed to use:

ExecuteAsScalarAsync<string>()

instead of:

ExecuteAsSingleAsync()


So it was my mistake.

**Comment by object** [comment]
Great. I will however check why it caused that exception. I shouldn't.
