### ISSUE TITLE
Are batch Actions and Functions supported?

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#131]
Hi,

I am wondering if batch Actions and Functions are supported?

For example,

var client = new ODataClient("http://services.odata.org/V4/TripPinServiceRW/");
 IList<object> resultList = new List<object>();
            var batch = new ODataBatch(client);

            batch += async x =>
            {
                var result = await x.For("People")
                    .Key("scottketchum")
                    .NavigateTo("Trips")
                    .Key(0)
                    .Function("GetInvolvedPeople")
                    .ExecuteAsEnumerableAsync();
                resultList.Add(result);
            };
await batch.ExecuteAsync();

Thanks!

**Comment by object** [comment]
Sure, it should work, any problems with that statement?

**Comment by mwchan** [comment]
I am getting the error below:

{"error":{"code":"InternalServerError","message":"BatchSegment translation is not supported","innererror":{"message":"BatchSegment translation is not supported","type":"System.NotImplementedException","stacktrace":"   at Microsoft.Test.OData.Services.ODataWCFService.PathSegmentToExpressionTranslator.Translate(BatchSegment segment)\r\n   at Microsoft.OData.Core.UriParser.Semantic.BatchSegment.TranslateWith[T](PathSegmentTranslator`1 translator)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.QueryContext.ResolveQuery(IODataDataSource dataSource, Int32 level)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.QueryHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RequestHandler.Process(Stream requestStream)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RootRequestHandler.Process(Stream requestStream)"}}}

I am guessing in this case, the TripService is not supporting it?

**Comment by object** [comment]
I just tested similar code (only with typed syntax), and it worked fine against sample TripPin service at odata.org. I will check your code now.

**Comment by object** [comment]
No, it works fine for me. This is payload from Fiddler:

POST http://services.odata.org/V4/(S(ozr3zphuz0ptbrrzc23kb121))/TripPinServiceRW/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_b80abd80-5383-4556-9cee-8f57378b1b13
Host: services.odata.org
Content-Length: 358
Expect: 100-continue

--batch_b80abd80-5383-4556-9cee-8f57378b1b13
Content-Type: application/http
Content-Transfer-Encoding: binary

GET http://services.odata.org/V4/(S(ozr3zphuz0ptbrrzc23kb121))/TripPinServiceRW/People(%27scottketchum%27)/Trips(0)/Microsoft.OData.SampleService.Models.TripPin.GetInvolvedPeople() HTTP/1.1


--batch_b80abd80-5383-4556-9cee-8f57378b1b13--

**Comment by mwchan** [comment]
Looks like I am getting 2 different batch calls are being made and it is failing on the second call. Do you think I am running the batch above incorrectly?

First payload:
POST http://services.odata.org/V4/TripPinServiceRW/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_222cb962-296c-446f-aba3-8b378f286ed0
Host: services.odata.org
Content-Length: 328
Expect: 100-continue

--batch_222cb962-296c-446f-aba3-8b378f286ed0
Content-Type: application/http
Content-Transfer-Encoding: binary

GET http://services.odata.org/V4/TripPinServiceRW/People(%27scottketchum%27)/Trips(0)/Microsoft.OData.SampleService.Models.TripPin.GetInvolvedPeople() HTTP/1.1


--batch_222cb962-296c-446f-aba3-8b378f286ed0--

Second payload:
GET http://services.odata.org/V4/(S(5tmpzxar450dlw1jgk5w2rsr))/TripPinServiceRW/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_222cb962-296c-446f-aba3-8b378f286ed0
Host: services.odata.org
Cookie: ARRAffinity=7f4cfe00ce16676343cb49cea0f403e97155c6d542bba19d699062aa8aee04c6

**Comment by mwchan** [comment]
The second call causes the WebRequestException to be thrown from RequestRunner.cs.

private async Task PostExecute(HttpResponseMessage responseMessage)
        {
            if (_session.Settings.AfterResponse != null)
                _session.Settings.AfterResponse(responseMessage);

            if (!responseMessage.IsSuccessStatusCode)
            {
                throw await WebRequestException.CreateFromResponseMessageAsync(responseMessage);
            }
        }

Exception message is: Internal Server Error

Exception reponse is:
{"error":{"code":"InternalServerError","message":"BatchSegment translation is not supported","innererror":{"message":"BatchSegment translation is not supported","type":"System.NotImplementedException","stacktrace":"   at Microsoft.Test.OData.Services.ODataWCFService.PathSegmentToExpressionTranslator.Translate(BatchSegment segment)\r\n   at Microsoft.OData.Core.UriParser.Semantic.BatchSegment.TranslateWith[T](PathSegmentTranslator`1 translator)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.QueryContext.ResolveQuery(IODataDataSource dataSource, Int32 level)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.QueryHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RequestHandler.Process(Stream requestStream)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RootRequestHandler.Process(Stream requestStream)"}}}

**Comment by mwchan** [comment]
I also forgot to add that when it returns to this line:

resultList.Add(result);

result is an empty enumeration.

**Comment by object** [comment]
Can you move the line resultList.Add(result) out of the batch scope? Just to see if it changes anything. Since I am not able to reproduce the error you can also send me a small example that fails in this manner (my mail is vagif.abilov at gmail).

**Comment by mwchan** [comment]
Hi,

I have just emailed you the source code to reproduce.

Thanks.

**Comment by object** [comment]
I tested it. The problem occurs because that site rewrites the original URL and gives back something like http://services.odata.org/V4/(S(dejg0qsxxm4cj1m1sraqen34))/TripPinServiceRW/, so in my integration tests I first execute a request, check response and correct URI accordingly. Then subsequent requests work. If you try to execute batch POST request, the service will return HTTP 302 to redirect request to a new URL, but then the next request issues batch in a GET request instead of POST. And this causes 500 error. If you change base service URI as I am doing in my tests, it should work.

**Comment by mwchan** [comment]
That does make sense. Thanks for your precious time in helping me work that out!

**Comment by mwchan** [comment]
Hi,

I do have another question related to the above. When performing the following:

batch += async x =>
        {
            var result = await x.For("People")
                .Key("scottketchum")
                .NavigateTo("Trips")
                .Key(0)
                .Function("GetInvolvedPeople")
                .ExecuteAsEnumerableAsync();
            resultList.Add(result);
        };

why is "result" always assigned with an empty enumerable before coming back with the "real" enumerable? It's as if the method is being called once but results are being returned twice. So, if I have a for loop as below,

for (int i = 0; i < 2; i++)
            {
                batch += async x =>
                {
                    var result = await x.For("People")
                        .Key("scottketchum")
                        .NavigateTo("Trips")
                        .Key(0)
                        .Function("GetInvolvedPeople")
                        .ExecuteAsEnumerableAsync();
                    resultList.Add(result);
                };
            }

resultList would have 4 sets of enumerables rather than 2.

Thanks in advance!

**Comment by object** [comment]
Although this behavior is incorrect, it has its reasons. Batch actions are executed twice but in a different manner: when you build a batch with "+=" operator, the actions are recorded but not executed. Then when you call batch.ExecuteAsync() the program sends the request to the server, receives response and finally executes actions for real. I will check why resultList.Add(...) is executed both times instead of being skipped during recording phase, but as a simple workaround you can just move it from the batch scope.

**Comment by mwchan** [comment]
Does the workaround mean that if I have a for loop that returns the results x amount of times, I would need x number of different variables to store each result? It seems that all your examples for batch in your unit tests stores them in separate variables such as product1 and product2.

**Comment by object** [comment]
Yes it does but I will look into how to allow the syntax you were using.

**Comment by mwchan** [comment]
Thank you!

**Comment by object** [comment]
I investigated this case more, and apparently there is nothing I can do using current implementation. All batch actions are executed twice: first time recording the batch steps, then processing batch results. The batch "+=" operator just accumulates lambdas, they are obscure, so if the lambda includes some custom actions (not related to OData HTTP operations), there is no way to prevent them, and they will be executed twice. So the workaround is to use the style I am using in my tests and restrict batch action steps to method calls on IODataCleint interface.

**Comment by mwchan** [comment]
Ok. I will workaround it then. Thanks for your time.
