### ISSUE TITLE
Sequence contains more than one element exception?

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#134]
Hi,

When trying to delete more than one record, an exception is thrown from the TripPin service. Do you know if this is a bug with the service itself?

Code:
var batch = new ODataBatch(client);
            batch += async x =>
            {
                await x.InsertEntryAsync("People", new Dictionary<string, object>
                {
                    {"UserName", "Test0"},
                    {"FirstName", "Test1"},
                    {"LastName", "Test1"}
                });
            };
            batch += async x =>
            {
                await x.InsertEntryAsync("People", new Dictionary<string, object>
                {
                    {"UserName", "Test0"},
                    {"FirstName", "Test2"},
                    {"LastName", "Test2"}
                });
            };
            await batch.ExecuteAsync();
            await client.For("People").Filter("UserName eq 'Test0'").DeleteEntriesAsync();

Exception:
{"error":{"code":"InternalServerError","message":"Sequence contains more than one element","innererror":{"message":"Sequence contains more than one element","type":"System.InvalidOperationException","stacktrace":"   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.EntityCollection`1.GetEntity(Func`2 func)\r\n   at lambda_method(Closure )\r\n   at Microsoft.Test.OData.Services.ODataWCFService.QueryContext.ResolveQuery(IODataDataSource dataSource, Int32 level)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.DeleteHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RequestHandler.Process(Stream requestStream)\r\n   at Microsoft.Test.OData.Services.ODataWCFService.Handlers.RootRequestHandler.Process(Stream requestStream)"}}}

Thank you.

**Comment by mwchan** [comment]
I realized that it is probably because the UserName is the key to the entity but then surely the service should not have allowed me to insert 2 items with the same key? Do you have any idea what the expected behaviour should be?

**Comment by object** [comment]
I believe you are getting exception because of a duplicate key, but this is entirely up to the service how to deal with it. For example, the key be auto-incremented or auto-generated, and many services will simply ignore whatever clients send them.
