### ISSUE TITLE
Select clause limitation

### ISSUE THREAD

**Issue by Allann** [object/Simple.OData.Client#137]
Whilst this might be similar to #136 , I need to return items from multiple tables, but both tables contain the same property name.  e.g.  j => new { j.Id, j.Origin.Code, j.Destination.Code }  And of course this would result in the Lamda having 2 properties with the same name and will produce a compiler error.

**Comment by Allann** [comment]
Ah.. figured out how to do this correctly.  Sorry, I'll close..

**Comment by Allann** [comment]
Sorry, this is still an issue.  My result was a false positive.

This is an issue using typed objects.
basically I need to generate the following url:
http://localhost:21245/Journey?$expand=Origin($select=Code),Destination($select=Code)&$select=Comments

**Comment by object** [comment]
What about this:
.Expand(x => new { x.Origin, x.Destination })
.Select(x => x.Origin.Code)
.Select(x => x.Destination.Code)
.Select( x => x.Comments)

**Comment by Allann** [comment]
Stacking the Select part worked a treat.  Thanks.  Example from a similar call built using the stacking technique.

http://localhost:21245/ExchangeRates?$expand=Commodity($select=Code),Term($select=Code)&$select=Id,AsAt,Value&$orderby=AsAt%20desc&$count=true
