### ISSUE TITLE
BatchWriter throws a NullReferenceException

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#138]
Hi,

The BatchWriter class is throwing a null reference exception when deleting records that does not exist. This does not happen when executing a non-batch delete.

This works:
await client.For("People").Filter("FirstName eq 'Test1'").DeleteEntriesAsync()

This fails because there are no records that match the filter:
var batch = new ODataBatch(client);
batch += async x => await x.For("People").Filter("FirstName eq 'Test1'").DeleteEntriesAsync();
await batch.ExecuteAsync();

Method that throws the exception is EndBatchAsync() and the line that throws it is:
await _batchWriter.WriteEndBatchAsync();

Thanks!

**Comment by object** [comment]
Fixed. Will be released with the version 4.10.

**Comment by mwchan** [comment]
Thank you.
