### ISSUE TITLE
Mocking ODataClient

### ISSUE THREAD

**Issue by ssavages** [object/Simple.OData.Client#142]
I am trying to mock a call to the oDataClient and am getting:

Castle.DynamicProxy.InvalidProxyConstructorArgumentsException : Can not instantiate proxy of class: Simple.OData.Client.ODataClient.
Could not find a parameterless constructor.

This is my code I am trying to Mock:
var invoices = await _invoiceSvc.ODataClient(authHeader)
                    .For<Invoice>()
                    .Filter(i => i.PaymentDueDate > date)
                    .FindEntriesAsync(annotations);

This is my mock:

MockInvoiceSvc.Setup(
                m =>
                    m.ODataClient(It.IsAny<string>())
                        .For<Invoice>(null)
                        .Filter(i=>i.PaymentDate>DateTime.Now)
                        .FindEntriesAsync(annotations)).ReturnsAsync(invoices);

Any help appreciated.

**Comment by ssavages** [comment]
The interface didn't put my mock in correctly:

           MockInvoiceSvc.Setup(
                m =>
                    m.ODataClient(It.IsAny<string>())
                        .For<Invoice>(null)
                        .Filter(i=>i.PaymentDate>DateTime.Now)
                        .FindEntriesAsync(annotations)).ReturnsAsync(invoices);

**Comment by object** [comment]
Can you use IODataClient instead of ODataClient? Then you don't need to instantiate ODataClient.

**Comment by ssavages** [comment]
Thanks for your reply.

MockInvoiceSvc is an interface which returns an ODataClient from its associated concrete class with all the relevant connections.

I see what you are getting at though. I am new to unit testing and I am trying to get my code into a more testable state.

**Comment by object** [comment]
It's common practice to use interfaces instead of concrete classes for mocking. Much easier to manage. This is one of the reasons ODataClient implements IODataClient interface.

**Comment by ssavages** [comment]
Makes sense, thanks for taking the time to answer.

I wasn't aware of the IODataClient interface, thanks again.
