### ISSUE TITLE
BatchWriter throws a NullReferenceException #2

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#146]
This is related to https://github.com/object/Simple.OData.Client/issues/138 but for a slightly different scenario.

The BatchWriter class is throwing a null reference exception when deleting records that does not exist. In this case, I am also doing an Insert as part of the batch. The NullReferenceException is thrown in the BatchWriter.cs class in the following method:

protected override Task StartChangesetAsync()
        {
            return _batchWriter.WriteStartChangesetAsync();
        }

To reproduce it:

batch = new ODataBatch(client);
batch += x => x.For("People").Filter("UserName eq 'Test111'").DeleteEntriesAsync();
batch += x => x.InsertEntryAsync("People",new Dictionary<string, object> { { "UserName", "Test4" }, { "FirstName", "Test5" }, { "LastName", "Test6" } });
await batch.ExecuteAsync();

Thanks!

**Comment by object** [comment]
Thank you for the observation. I will look into it.

**Comment by object** [comment]
Fixed. Will be released in 4.11.
