### ISSUE TITLE
Is it possible to remove additional nuget packages related to Bcl

### ISSUE THREAD

**Issue by RonakThakkar** [object/Simple.OData.Client#149]
Hi,

I have observed Simple.OData.Client Nuget Package has dependency on following packages.

Microsoft.Bcl.Build
Microsoft.Bcl
Microsoft.Bcl.Async

Is it possible to get rid of them. Are they required for OData operations?

Example:  I read that "Microsoft.Bcl.Async" NuGet package provides support for the async/await without .Net framework 4.5 i.e for pre-.NET 4.5 platforms, such as .NET 4, Silverlight 4, and Windows Phone 7.5.

But If all of my projects use .Net 4.5 then that might not be required.

regards,
ronak thakkar

**Comment by object** [comment]
You are right, Microsoft.Bcl.Async is not needed for .NET 4.5, but the library supports legacy .NET platforms too where it's required. I will investigate if I can make the NuGet package contents more sensitive to the actual target platform.

**Comment by object** [comment]
I've removed Microsoft.Bcl.Async from packages other than targeting net40 and sl5 (to be released in 4.13). I still need to include Microsoft.Bcl and Microsoft.Bcl.Build because Microsoft.Net.Http depends on them.

**Comment by object** [comment]
Fixed in 4.13.

**Comment by Maxwe11** [comment]
@object it continues installed `Microsoft.Bcl.Async` on .NET 4.5.
VS 2015 Update 3, nuget 3.5

**Comment by Maxwe11** [comment]
@object I think explitly specified dependencies for .NET 4.5 resolves problem.
