### ISSUE TITLE
Authentication Example

### ISSUE THREAD

**Issue by NVentimiglia** [object/Simple.OData.Client#151]
I am looking into Simple.OData as a service client for a Xamarin client which communicates with an ASP.NET MVC WebAPI back end. I would like to use Authentication, however the examples are lacking implementation examples. I understand I will need to handle the BeforeRequest / AfterRequest events and read/write the Authentication token, but, not sure what the token is called.

Could you be as kind to show me a quick and dirty example ?

**Comment by object** [comment]
Hi,

Please have a look at the example here: https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.IntegrationTests/WebApiTests.cs

In the bottom of the file it has a class WebApiWithAuthenticationTests that sets credentials, so you don't need to use BeforeRequest handler (although you can still use it for more complicated cases).

**Comment by NVentimiglia** [comment]
That works, thanks !

**Comment by Abenezer** [comment]
suppose i want to use **bearer** authorization instead of **basic** do i need to use "BeforeRequest" handler  of client setting or can i set credential property?

**Comment by object** [comment]
I didn't try it myself, you probably can just use Credential property which will be passed to HttlClientHandler that is supposed to convert it authorization header.
