### ISSUE TITLE
Intended behaviour when updating fields that are keys to an entity

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#152]
Hi,

When updating an entity using a filter in a batch, and one of the fields being updated is a key field, a Put request is being ran instead of a Patch.

For example, if I have the following entity:

<EntityType Name="Person" OpenType="true">
<Key>
<PropertyRef Name="UserName"/>
<PropertyRef Name="FirstName"/>
<PropertyRef Name="LastName"/>
</Key>
<Property Name="UserName" Type="Edm.String" Nullable="false">
</Property>
<Property Name="FirstName" Type="Edm.String" Nullable="false"/>
<Property Name="LastName" Type="Edm.String" Nullable="false"/>
<Property Name="Address" Type="Edm.String" Nullable="false"/>
</EntityType>

And I inserted a record where:
UserName = "Test0"
FirstName= "Test1"
LastName= "Test2"
Address= "Test3"

And then I ran the following query to update it:
var batch = new ODataBatch(client);
batch +=  y =>
                    y.For("People")
                        .Filter("UserName eq 'Test0'").Filter("FirstNameeq 'Test1'").Filter("Address eq 'Test3'")
                        .Set(new Dictionary<string, object>
                        {
                            {"LastName", "Modified Test2"}
                        })
                        .UpdateEntryAsync();
            await batch.ExecuteAsync();

This would do a Put instead of a Patch request because in RequestWriterBase.cs in CreateUpdateRequestAsync method, CanUseMerge returns false.

Is this the intended behaviour?

Thanks in advance!

**Comment by mwchan** [comment]
The entity definition did not appear. I will try adding it again as an image instead

![image](https://cloud.githubusercontent.com/assets/13030742/9679846/bae42f64-5324-11e5-9096-af654242832e.png)

**Comment by mwchan** [comment]
Doing the same without using the batch would throw a NotFound exception as it tries to use {"LastName", "Modified Test2"} as part of it's filter to look for the record.

**Comment by object** [comment]
Thanks for the observation. I'll check it out.

**Comment by object** [comment]
I just released a version 4.11 where PATCH is always preferred. In addition there is a new property in ODataClientSettings that allow to specify preferred update method (PATCH or PUT). Can you try this version?

**Comment by mwchan** [comment]
Sorry for the delay and thanks for the fix. I will definitely try that and let you know.

**Comment by mwchan** [comment]
Just verified that a PATCH request is the preferred update method. Thanks!
