### ISSUE TITLE
Enable Xamarin nuget compatibility

### ISSUE THREAD

**Issue by thomas-goerlich** [object/Simple.OData.Client#153]
Hi,
i am working on a Desktop and Xamarin Mobile App which uses this library. Sadly i was unable to include the lib via nuget in the Xamarin project due to it being incompatibil (see error below).
To fix this i mirrored the lib on our internal nuget server and changed the lib/path in the package from:
portable-net45+win+win8+wp8+wpa81
to:
portable-net45+wp8+wpa81+netcore45+monoandroid1+xamarin.ios10
which works so far. Maybe consider changing the path in the official package or please tell me if this is a bad idea for some reason (i'm new in the whole c#/nuget world :)).
regards Thomas

Xamarin - Nuget compatibility error:
Could not install package 'Simple.OData.V3.Client 4.8.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by object** [comment]
Thank you for the observation, this is very valuable. I will investigate if your fix will work in other scenarios and release a new version.

**Comment by object** [comment]
Hi again,
Actually I don't really understand why this error occurs because the changes you did should not have affected anything. I asked a question on StackOverflow, you can check the discussion:

http://stackoverflow.com/questions/32483438/why-does-a-pcl-nuget-package-fail-to-target-xamarin-platform

So as was suggested on SO, I need more information about what kind of development environment you are using. It can even be a NuGet 3 bug. Can you provide me with more details?

**Comment by thomas-goerlich** [comment]
Thanks for getting back to me so quickly.
We are indeed using Visual Studio 2015 with the latest available nuget version (should be 3.x but i am not at work right now so can't check for an exact number sorry).
Isn't the monoandroid/xamarin.ios in lib/path required to download the packages in a Xamarin project?
I just checked a few Xamarin nuget packages and serilog which i tried out today and all of them had monoandroid1+xamarin.ios10 in the lib/path. The Xamarin docu seems to suggest the same https://developer.xamarin.com/guides/cross-platform/advanced/nuget/.

**Comment by object** [comment]
I can't say for VS2015 (didn't try it with Xamarin apps yet), but both VS2013 and Xamarin Studio work fine with NuGet packages that omit references to Xamarin platforms. Platform reference in NuGet is just an instruction of what lib (from potentially a number of libraries) to pick and link to a mobile app. Xamarin tools are smart enough to manage it without explicit platform reference. But perhaps all this changed with Visual Studio 2015 and an explicit reference is required. I will investigate this more, and if you have access to Visual Studio 2013 perhaps you can also check if you are able to install NuGet package there. Just to understand better what's going on.

**Comment by object** [comment]
Another request. You probably have Xamarin Studio on your machine. Can you try to build your app in Xamarin Studio using my original package?

**Comment by thomas-goerlich** [comment]
Thank you for the explanation regarding the platform references.
I tried adding the nuget package in Xamarin Studio and it worked fine. I don't have access to VS2013 right now.
Since it works fine in XS (using nuget v2.8.5) but not in VS2015 i thought that your idea that it might be a bug in nuget v3 is right and started to investigate. I found the following issue in the nuget project https://github.com/NuGet/Home/issues/1172 and removed a "win" entry in the path for testing purposes and it worked in VS2015. So that seems to be the correct issue/bug.
While it would help to add the platform references to make it work now in the end it is a nuget bug.
Thank your very much for your help and sorry for bothering you with an issue that is not really in your project.

**Comment by mrward** [comment]
This looks like a possible bug in NuGet v3. I get the same error trying to install the NuGet package with Visual Studio 2015 and NuGet 3.1.1 installed.

It looks to me as though NuGet 3 does not like the extra **win** in the portable profile for Simple.OData.V3Client 4.8.1. If I remove that from the extracted package in the local machine's cache then Visual Studio 2015 will install it into an Android project. So the profile folder is now:

    portable-net45+win8+wp8+wpa81

It would probably be worth reporting this as a [bug](https://github.com/nuget/home/issues) with the NuGet team to see if it is a bug or a change that has occured in NuGet 3 which makes it not backward compatble with NuGet 2.

A monoandroid/xamarin.ios in the lib directory is not required in the NuGet package in order for it to be used in a Xamarin project. If the NuGet package contains a compatible portable class library (PCL) then that can be used. You only need lib/monoandroid or lib/xamarin.ios if you have a library which uses part of monoandroid or xamarin.ios (i.e. is platform specific).

Also the monoandroid and xamarin.ios is not required in the portable class library profile in the NuGet package. These are treated as optional by NuGet. Json.NET for example does not any reference to monoandroid or xamarin.iOS in its NuGet package and that can be used by Xamarin projects.

**Comment by thomas-goerlich** [comment]
@mrward thanks for the additional explanation and help. Your observation was right. I sent my previous comment just shortly before yours explaning that it is indeed a nuget issue and that it is fixed in the next version.

**Comment by object** [comment]
I will change the platform targets and release an update (version 4.11) in a few days. Thanks for a great input.
