### ISSUE TITLE
Codesigned version of assemblies

### ISSUE THREAD

**Issue by masterkidan** [object/Simple.OData.Client#155]
Is it possible to get a codesigned version of Simple.Odata.Client?

**Comment by object** [comment]
Hmm, I am not sure. The library has never been signed and I don't want to start signing it now (I know many developers hate assembly strong naming). But I understand that some organizations have their own reasons for using signed libraries (the simplest is that the app is signed which implies all referenced libs to be signed too). But is this something you can manage yourself? I quickly checked and found a Nivot.StrongNaming NuGet package (https://www.nuget.org/packages/Nivot.StrongNaming/) that can be used to sign assemblies without having access to its source code. Can this help?

**Comment by masterkidan** [comment]
I believe signtool itself allows you to sign assemblies after they have been built. However, I had wanted to use a certificate that you had generated, as I was not entirely sure how signing an assembly with a certificate I had created would affect the terms of the OSS license.

**Comment by object** [comment]
I have no objection about signing my assemblies with client-generated certificate, but I see that it might be beneficial to generate a common certificate so in those scenarios where the singing is needed all signed assemblies will have the same strong name. I will investigate this further and in the mean time you can sign the libs with your certificate.

**Comment by object** [comment]
I looked around a bit more, and I think I will stick to general consensus about open source libraries: they are not signed but everyone can sign them locally. Check for example this thread:

https://groups.google.com/forum/#!topic/nancy-web-framework/PKC41D8j0qA

And a resolution similar to what I already mentioned: http://www.corelgott.de/?p=128

So I think I will keep the library unsigned leaving everyone option to sign it if required.
