### ISSUE TITLE
Batch actions never gets executed

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#156]
Hi,

I am not sure why but the actions in batch does not seem to be executed. I do not see any request going through in Fiddler except for the metadata request.

            var httpClient = new HttpClient();
            var response = httpClient.GetAsync("http://services.odata.org/V4/TripPinServiceRW/").Result;
            var uri = response.RequestMessage.RequestUri.AbsoluteUri;
            var client = new ODataClient(uri);
            var b = new ODataBatch(client);
            b += async c =>
            {
                var e = await c.For("People")
                    .Key("scottketchum")
                    .Action("ShareTrip")
                    .Set(new Dictionary<string, object> { { "userName", "russellwhyte" }, { "tripId", 0 } })
                    .ExecuteAsSingleAsync();
            };
            await b.ExecuteAsync();

Thanks.

**Comment by object** [comment]
Another one to be investigated, thanks.

**Comment by object** [comment]
Fixed, will be released in 4.11.
