### ISSUE TITLE
Odata v3 enum problem

### ISSUE THREAD

**Issue by thyn** [object/Simple.OData.Client#159]
Hi i have odata v3 service with enums in metadata

A have base class Post and Derived ExternalTest. Base Post class has enum Status.  You can review metadata here

http://pastebin.com/SKh9kZDc

the problem is when I'm trying to request service using 

    client.For<ExternalTest>().Filter(x => x.Status == PostStatus.Approved)

(generates /odata/ExternalTests?$filter=Status+eq+0)

i'm having error

The query specified in the URI is not valid. A binary operator with incompatible types was detected. Found operand types 'Edm.String' and 'Edm.Int32' for operator kind 'Equal'.

Then if I make a query using /odata/ExternalTests?$filter=Status+eq+%27Approved%27

it succeeded. Please help me to find problem in my scheme.

**Comment by object** [comment]
Thank you for reporting it. I will have a look and come back to you.

**Comment by object** [comment]
Sorry for not getting back to you earlier. The reason for not accepting the enum is quite simple: there is no enum definition inside the metadata document. The Status type in your service metadata is defined as Edm.String so it will only accept "Approved" as a value. If you revise your service metadata so Status will have enum type, then you will be able to use enums and not their string representation.

Hope this helps.

**Comment by AmirImam** [comment]
I have same issue right now .. I don't understand how can I revise my service metadata ?
