### ISSUE TITLE
Unbound Function Not Found error

### ISSUE THREAD

**Issue by bjones-hotdocs** [object/Simple.OData.Client#161]
When calling an unbound function or action where the FunctionImport Name differs from the Function Name in the Edm model (or the ActionImport Name differs from the Action Name) the client returns an error 'Function [...] not found' (or 'Action [...] not found'). This is using version 4.11.0 of Simple.OData.Client from nuget. I have not tried with any other versions.

If it helps, I am using the following code snippet to call the function:

var client = new ODataClient(uri);
var unboundclient = client.Unbound<IDictionary<string, object>>();
var results = unboundclient.Function(functionImport.Name).Set(parameters).ExecuteAsEnumerableAsync();

When the FunctionImport Name is the same as the Function Name of the function that it references, the code behaves as expected.

**Comment by object** [comment]
Can you paste an example of a metadata document that causes such error?

**Comment by bjones-hotdocs** [comment]
Here is a sample metadata that produces the error:

<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="myproductsNS" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="CategoriesItem">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" />
      </EntityType>
      <EntityType Name="ProductsItem">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" Nullable="false" />
        <Property Name="Price" Type="Edm.Double" Nullable="false" />
        <Property Name="CategoryId" Type="Edm.Int32" Nullable="false" />
      </EntityType>
      <EntityType Name="OrdersItem">
        <Key>
          <PropertyRef Name="OrderNumber" />
        </Key>
        <Property Name="OrderNumber" Type="Edm.Guid" Nullable="false" />
        <Property Name="Quantity" Type="Edm.Int64" Nullable="false" />
        <Property Name="OrderDate" Type="Edm.DateTimeOffset" Nullable="false" />
        <Property Name="ProductId" Type="Edm.Int32" Nullable="false" />
      </EntityType>
      <ComplexType Name="Top2ProductsByCategoryResultItem">
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" Nullable="false" />
        <Property Name="Price" Type="Edm.Double" Nullable="false" />
        <Property Name="CategoryId" Type="Edm.Int32" Nullable="false" />
        <Property Name="CategoryName" Type="Edm.String" />
      </ComplexType>
      <Function Name="Top2ProductsByCategoryFunction">
        <ReturnType Type="Collection(myproductsNS.Top2ProductsByCategoryResultItem)" />
      </Function>
      <ComplexType Name="mynewqueryResultItem">
        <Property Name="Id" Type="Edm.Int32" Nullable="false" />
        <Property Name="Name" Type="Edm.String" Nullable="false" />
        <Property Name="Price" Type="Edm.Double" Nullable="false" />
        <Property Name="CategoryId" Type="Edm.Int32" Nullable="false" />
        <Property Name="CategoryName" Type="Edm.String" />
      </ComplexType>
      <Function Name="mynewqueryFunction">
        <Parameter Name="CategoryId" Type="Edm.Int32" Nullable="false" />
        <ReturnType Type="Collection(myproductsNS.mynewqueryResultItem)" />
      </Function>
      <EntityContainer Name="myproducts">
        <EntitySet Name="Categories" EntityType="myproductsNS.CategoriesItem" />
        <EntitySet Name="Products" EntityType="myproductsNS.ProductsItem" />
        <EntitySet Name="Orders" EntityType="myproductsNS.OrdersItem" />
        <FunctionImport Name="Top2ProductsByCategory" Function="myproductsNS.Top2ProductsByCategoryFunction" />
        <FunctionImport Name="mynewquery" Function="myproductsNS.mynewqueryFunction" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>

**Comment by object** [comment]
Thanks! I will dome back to you.

**Comment by object** [comment]
I've fixed the problem, will come in version 4.12, to be released in a few days.
