### ISSUE TITLE
Updating and inserting in an OData service

### ISSUE THREAD

**Issue by Aspro1** [object/Simple.OData.Client#162]
I have a Xamarin.Forms Visual Studio solution, into which I installed the “Simple.OData.Client” package with NuGet. I have the URI of an OData service and I want to load items from the table “Persons”, in which the base element type is “Person” and which contains instances of the class “Customer”, which inherits from the class “Person”, as I can see when opening the URI to which I append “/$metadata”.

    <Schema xmlns="http://schemas.microsoft.com/ado/2009/11/edm" Namespace="A">
      ...
      <EntityType Name="Person" Abstract="true">
      ...
      <EntityType Name="Customer" BaseType="A.Person">
      ...
      <EntityContainer Name="Model" m:IsDefaultEntityContainer="true">
        ...
        <EntitySet Name="Persons" EntityType="A.Person"/>
        ...

I create an instance of the service:

    ODataClient clientSimple = new ODataClient("http://.../.../odata.v3/default");

I load items from the data table:

    System.Collections.Generic.IEnumerable<System.Collections.Generic.IDictionary<string, object>> persons = await clientSimple.For("Persons").FindEntriesAsync();

The items are returned as dictionaries where the keys are the property names and the values are the property values. I see that the properties from the “Person” entity type as well as those added in the derived “Customer” type are present.

I know that there is also a possibility of the typed syntax:

    var personsTyped = await clientSimple.For<Person>().FindEntriesAsync();

However, I do not know where to get the definition of the “Person” class so that I can use it here as the generic type parameter.

Then I want to modify an entry in the OData service:

    await clientSimple.For("Persons").Key(1).Set(new { FirstName = "Johnny" }).UpdateEntryAsync();

This works as long as I only update a property defined in the “Person” entity type, but trying to modify a property added in the “Customer” entity type raises an exception:

    await clientSimple.For("Persons").Key(1).Set(new { FirstName = "Johnny", SalesPerson = "..." }).UpdateEntryAsync();

    [Simple.OData.Client.UnresolvableObjectException] No property or association found for [SalesPerson].

Trying to insert a new item also fails:

    var newObjectCreated = await clientSimple.For("Persons").Set(new { FirstName = "...", ... }).InsertEntryAsync();

    [Simple.OData.Client.WebRequestException] Internal Server Error

How can I solve this so that I can update all properties and insert new items?

**Comment by object** [comment]
I've answered this question on StackOverflow, please have a look:

http://stackoverflow.com/questions/32761283/updating-and-inserting-in-an-odata-service/33254007#33254007
