### ISSUE TITLE
How i can to know class type from a request?

### ISSUE THREAD

**Issue by manusisnova** [object/Simple.OData.Client#165]
Hello

I have a request from a base type but i need to know what specific derived type is it, exists any form to know this. I am use untyped request.

Thanks in advance

**Comment by object** [comment]
You can set IncludeAnnotationsInResults=true in ODataClientSettings. This will cause it to include ODataEntryAnnotations in each entry data, and ODataEntryAnnotations contain TypeName property.

The unit tests for the library contain examples of using ODataEntryAnnotations.

**Comment by manusisnova** [comment]
Thanks a lot, works great!
