### ISSUE TITLE
Simple.OData.Client.Net40 assembly does not have a strong name.

### ISSUE THREAD

**Issue by spaswin** [object/Simple.OData.Client#166]
Hi,

I have installed the nuget package Simple.OData.Client" version="4.11.0".
It throws the build error "Referenced assembly 'Simple.OData.Client.Net40, Version=4.11.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name". Is it possible to resolve this issue  in the source code itself? 

Thanks
Aswin S P

**Comment by object** [comment]
Hi,

Please look at the discussion for the similar issue: https://github.com/object/Simple.OData.Client/issues/155

In short: no, I don't want to introduce strong naming in the library but there are some other ways to sign it, one of them referred in that discussion.

Hope this helps.
