### ISSUE TITLE
Preference return=representation not used in update that is part of a batch

### ISSUE THREAD

**Issue by radurd** [object/Simple.OData.Client#167]
I have the following code:

            Document originalDocument = null;
            Document renamedDocument = null;
            var batch = new ODataBatch(client);
            batch += async c => originalDocument = await c.For<Document>()
                .Key(documentId)
                .FindEntryAsync();
            batch += async c => renamedDocument = await c.For<Document>()
                .Key(documentId)
                .Set(new { Name = newName })
                .UpdateEntryAsync(true);
            await batch.ExecuteAsync();

When running, the following request is being generated:

POST https://.../15.2/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_bbd96368-b28f-4905-8488-4f9d2497e594
Content-Length: 912
Expect: 100-continue

--batch_bbd96368-b28f-4905-8488-4f9d2497e594
Content-Type: application/http
Content-Transfer-Encoding: binary

GET https://.../15.2/Documents(27249) HTTP/1.1

--batch_bbd96368-b28f-4905-8488-4f9d2497e594
Content-Type: multipart/mixed; boundary=changeset_2e4140c2-c3f8-4ac9-9917-27302e2e66a7

--changeset_2e4140c2-c3f8-4ac9-9917-27302e2e66a7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

PATCH https://.../15.2/Documents(27249) HTTP/1.1
Content-ID: 2
Prefer: return-content
OData-Version: 4.0
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8

{
  "@odata.type":"#Model.Document","Name":"foo"
}
--changeset_2e4140c2-c3f8-4ac9-9917-27302e2e66a7--
--batch_bbd96368-b28f-4905-8488-4f9d2497e594--

Please note the Prefer: return-content in the second part of the batch. That would need to be Prefer: return=representation for the proper behavior.

Thanks!

**Comment by object** [comment]
Thank you for the issue report. I will check it out.

**Comment by object** [comment]
Fixed. Will be release in version 4.13.

**Comment by object** [comment]
Fixed in 4.13.
