### ISSUE TITLE
2 Problems sending Entities using Set

### ISSUE THREAD

**Issue by romangpro** [object/Simple.OData.Client#168]
2 Problems I am having:

1. Any (virtual) child Entity is not sent using Set. I am trying to perform a "deep insert".
ex:
class A{
int i;
virtual B b;
}
controller with post Insert, taking A as argument.
REST client works - ie send a nested JSON
{ "i" : 0,
"b" : {}
}
But, Simple.OData.Client fails to serialize/send the child property b - it arrives with null;

2. I am trying to invoke an unbound Action with Entity parameters. 
REST client works - ie send named Entities as JSON 
Using Simple.OData.Client I get:
The parameter 'MessageTemplate2' is of Edm type kind 'Entity'. You cannot call WriteValue on a parameter that is not of Edm type kinds 'Primitive', 'Enum' or 'Complex'."

I tried defining the parameters on the model builder as Parameter and EntityParameter, and neither works with Simple.OData.Client

Any help would be appreciated

**Comment by object** [comment]
Hi,
In order to investigate this problem I need the following:
1. Service metadata
2. Entity definition (if you are using typed syntax)
3. Client code example that reproduces the error.
