### ISSUE TITLE
Exception connecting client to V4 Odata Service .Net 4.5

### ISSUE THREAD

**Issue by yasirk1** [object/Simple.OData.Client#169]
Hi, have spent a number of hours trying to get the most simple scenario working of connecting the client to an odata V4 service using the same service and also my local Odata service and the client just refuses to connect. I keep getting the session.Adapter exception below in the 'session' variable of the client. 

What am i missing?? 

var client = new ODataClient("http://packages.nuget.org/v1/FeedService.svc/");

  var packages =  client
                .FindEntriesAsync("Packages?$filter=Title eq 'Simple.OData.Client'");
          
Adapter = 'odataClient._session.Adapter' threw an exception of type 'System.InvalidOperationException'

**Comment by object** [comment]
I have no problems getting data from Nuget V1, but didn't you forget "await" keyword in your example? I.e. package = await client.FindEntriesAsync(...).

Can this be a problem? Simple.OData.Client API is asynchronous so you must await it.

**Comment by yasirk1** [comment]
Yes, indeed, that worked!! Thank you. Feel silly now. 

-----Original Message-----

**Comment by object** [comment]
No problem! Good to know it works now.
