### ISSUE TITLE
Creating dynamic linq expression OData for multiple conditions for filter Contains?

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#170]
For single Contains filter condition in Odata I tried like following

  var customerData = await myclient.For<Customer>()
            .Filter(x => x.Name.Contains("john"))
            .FindEntriesAsync();
How can I use multiple Contains filter? for example

 var customerData = await myclient.For<Customer>()
            .Filter(x => x.Name.Contains("john") || x.Address.Contains("india"))
            .FindEntriesAsync();
I tried with query expression used this code
http://www.codeproject.com/Tips/582450/Build-Where-Clause-Dynamically-in-Linq

but how do I pass filter expression inside Odata .Filter()?

List<Filter> filter = new List<Filter>()
{
    new Filter { PropertyName = "City" ,
        Operation = Op .Equals, Value = "Mitrovice"  },
    new Filter { PropertyName = "Name" ,
        Operation = Op .StartsWith, Value = "L"  },
    new Filter { PropertyName = "Salary" ,
        Operation = Op .GreaterThan, Value = 9000.0 }
};

var deleg = ExpressionBuilder.GetExpression<Person>(filter).Compile();
I want to use deleg expression and pass to Odata.

var customerData = await myclient.For<Customer>()
            .Filter(deleg.ToString())
            .FindEntriesAsync();
unable to execute above statement.

**Comment by object** [comment]
Please see my answer on SO: http://stackoverflow.com/questions/33254879/creating-dynamic-linq-expression-odata-for-multiple-conditions-for-filter-contai/33258926#33258926

At first I thought there's nothing much that can be done here, but if I expose a public method that creates ODataExpression from C# LINQ expressions, it might be sufficient for your needs.

**Comment by ashuthinks** [comment]
thanks a lot , it will be great if any code snippet will be given once you expose it public

**Comment by object** [comment]
I just pushed the version 4.12 that exposes public constructor for ODataExpression. So you can do things like these:

            Expression&lt;Predicate&lt;Product&gt;&gt; condition1 = x =&gt; x.ProductName == "Chai";
            Expression&lt;Func&lt;TestEntity, bool&gt;&gt; condition2 = x =&gt; x.ProductID == 1;
            var filter = new ODataExpression(condition1);
            filter = filter || new ODataExpression(condition2);
            var result = await client.For&lt;Product&gt;.Filter(filter).FindEntriesAsync();

            or

            var filter = new ODataExpression&lt;Product&gt;(x =&gt; x.ProductName == "Chai");
            filter = filter || new ODataExpression&lt;Product&pt;(x =&gt; x.ProductID == 1);
            var result = await client.For&lt;Product&gt;.Filter(filter).FindEntriesAsync();

**Comment by ashuthinks** [comment]
Fantastic thanks a lot :) its a great stuff
