### ISSUE TITLE
I can not able to use Contains-filter to expanded table.

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#173]
I can not able to use Contains-filter to expanded table.

var customersData = await myClient.For<Customer>()
                .Filter(t => t.name.Contains(searchCriteria) || t.PersonTable.ContactNumber.Contains(searchCriteria))
                .Expand(t => new { t.PersonTable, t.AddressesTable })
                .FindEntriesAsync();

Can you help me , I tried using new version 4.12 like below also.

    var filter = new ODataExpression<Customer>(t => t.name.Contains(searchCriteria));
            filter = filter || new ODataExpression<PersonTable>(x => x.ContactNumber.Contains(searchCriteria));
            var result3 = await myClient.For<Customer>().Filter(filter).FindEntriesAsync();

**Comment by object** [comment]
Thank you for the issue report. What error are you getting? What happens if you don't build the filter incrementally but send the whole expression at once (like you had to do in version 4.11)?

**Comment by ashuthinks** [comment]
If I use previous version and don't build the filter incrementally it is not able to use contains for expanded entity. no error thrown 
but for above code i tried like following and it works

var filter = new ODataExpression<Customer>(t => t.name.Contains(searchCriteria));
        filter = filter || new ODataExpression<Customer>(x => x.PersonTable.Contains(searchCriteria));
        var result3 = await myClient.For<Customer>().Filter(filter)
.Expand(x => new { x.PersonTable })
.FindEntriesAsync();

**Comment by object** [comment]
I see that you are using different types on For and Filter clause. I don't think this will work. Filter clause assumes that the generic type is the same as the main type you use in For (or NavigateTo) clause.

**Comment by ashuthinks** [comment]
this is working as var filter = new ODataExpression(t => t.name.Contains(searchCriteria));
filter = filter || new ODataExpression(x => x.PersonTable.Contains(searchCriteria));
var result3 = await myClient.For<Customer>().Filter(filter)
.Expand(x => new { x.PersonTable })
.FindEntriesAsync();
