### ISSUE TITLE
Filtering on Enumerations

### ISSUE THREAD

**Issue by Frankenslag** [object/Simple.OData.Client#174]
Hi,

 I am looking for a way of querying data based on an entity of an enumeration type using the dynamic methods.

 I can write a url type query i.e. $filter=PackageColor eq Namespace.Color’Green’ but I cannot work out how to write this using a dynamic .Filter method.

**Comment by object** [comment]
I am investigating this one. Apparently S.O.D. doesn't currently support specifying enumeration using dynamic syntax - you have to send such queries using typed or untyped syntax, which is silly. I will let you know when I extend dynamic support.

**Comment by object** [comment]
The issue is resolved. Will be release as a part of 4.13.

**Comment by object** [comment]
Fixed in 4.14.
