### ISSUE TITLE
Create entities without link

### ISSUE THREAD

**Issue by Jerther** [object/Simple.OData.Client#175]
Hi!

I'm trying to reproduce the following example from odata.org:

http://www.odata.org/getting-started/basic-tutorial/#create

Which produces the following POST request body:

```JSON
{
    "@odata.type": "Microsoft.OData.SampleService.Models.TripPin.Person",
    "UserName": "teresa",
    "FirstName": "Teresa",
    "LastName": "Gilbert",
    "Gender": "Female",
    "Emails": [
        "teresa@example.com",
        "teresa@contoso.com"
    ],
    "AddressInfo": [
        {
            "Address": "1 Suffolk Ln.",
            "City": {
                "CountryRegion": "United States",
                "Name": "Boise",
                "Region": "ID"
            }
        }
    ]
}
```
Notice that child properties are unlinked, that is, the whole object graphed is serialized.

Is it possible to obtain such JSON with simple.odata.client? The only thing I can find is the example here:

https://github.com/object/Simple.OData.Client/wiki/Adding-entries-with-links

Which adds bindings to the child properties (unwanted in my case), similar to:

```JSON
"City@odata.bind": "http://localhost:56062/api/City(0)"
```

**Comment by object** [comment]
Hi,

Please have a look at the test code here: 
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.IntegrationTests/TripPinTests.cs

In particular, the tests that create Event data and use the following method:

        private Event CreateTestEvent()
        {
            return new Event
            {
                ConfirmationCode = "4372899DD",
                Description = "Client Meeting",
                Duration = TimeSpan.FromHours(3),
                EndsAt = DateTimeOffset.Parse("2014-06-01T23:11:17.5479185-07:00"),
                OccursAt = new EventLocation()
                {
                    Address = "100 Church Street, 8th Floor, Manhattan, 10007",
                    BuildingInfo = "Regus Business Center",
                    City = new Location.LocationCity()
                    {
                        CountryRegion = "United States",
                        Name = "New York City",
                        Region = "New York",
                    }
                },
                PlanItemId = 33,
                StartsAt = DateTimeOffset.Parse("2014-05-25T23:11:17.5459178-07:00"),
            };
        }

The EventLocation is embedded without the link, so it should be similar to what you're trying to achieve.

So the answer is yes, it's possible to both send and retrieve embedded structures that don't have links.

**Comment by Jerther** [comment]
Hmmm there seems to be nothing special in the test. Then what would trigger
the inserted entity to be serialized with links?

**Comment by object** [comment]
The service metadata. Simple.OData.Client first reads the OData service metadata and handles linked or embedded structures dependent on how they are described in the metadata, e.g. whether it's a nested complex type or an entity type. The tests which I referred to use that particular schema that you mentioned, so unless I misunderstand you they achieve exactly what you are looking for.

**Comment by Jerther** [comment]
Oh! Now I understand! Thank you very much! I was trying to use entity types
as complex types. I'll run some tests soon to see if I can handle this
right.

--
Jerther

**Comment by object** [comment]
Great! Yes they are quite different even though on a client side this difference is not always seen.

**Comment by Jerther** [comment]
From what I've gathered, ```@odata.bind is not supported``` in Web API 2.2 v5.6, which is what I'm using. 

https://github.com/OData/WebApi/issues/158

There are some hacks around but nothing perfect. Here is a nice SO question with a workaround:

http://stackoverflow.com/questions/30871984/support-of-odata-bind-in-asp-net-web-api-link-to-existing-entity-during-post

But nothing that'll handle this properly. So bottom line, I can't use @odata.bind until MS genuinely supports it.

In the mean time, is there a way to force simple.odata.client to serialize linked entity types like it would for complex types? Otherwise I'll have to manually call the POST action with a HttpClient. No big deal, but it'd be nice to have S.O.C. handle this.

**Comment by object** [comment]
I need to investigate this further but I suspect there is no straightforward way to change the behavior of the Simple.OData.Client. It used to have its own serializer but starting from version 4 it's been using Microsoft's ODataLib (Microsoft.OData.Core and Microsoft.OData.Edm libraries for OData v4) so it they handle all serialization details according to the defined service metadata.

**Comment by Jerther** [comment]
I hope you find something. meanwhile, I''ll handle this easy with a HttpClient.
