### ISSUE TITLE
Query for derived types returns 'Entity type [Sisnova_Invex_BL_CategoriaElemento] not found'

### ISSUE THREAD

**Issue by manusisnova** [object/Simple.OData.Client#179]
I have a derived type very deep, my model is like this

PersistentType-> BaseType -> Type ->DerivedType

I attach my metadata for details.
[$metadata.txt](https://github.com/object/Simple.OData.Client/files/33462/metadata.txt)

When i try to query with Untyped Syntax, i have exception "Entity type [Sisnova_Invex_BL_CategoriaElemento] not found"

My query is:  

entities = await odataclient.For("Sisnova_Invex_BL_InvexCualidad").As("Sisnova_Invex_BL_CategoriaElemento").FindEntriesAsync();

Thanks for you help

**Comment by object** [comment]
I've reproduced and fixed the error. You can either get a pre-release 4.13 version from myget.org or wait for 4.13 at nuget.org.

**Comment by object** [comment]
Fixed in 4.13.

**Comment by manusisnova** [comment]
Works great, thanks.
