### ISSUE TITLE
Bug in DeleteEntriesAsync

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#180]
Hi,

There is a bug in the DeleteEntriesAsync(string collection, string commandText) method.

The following works:

await client.For("People").Filter("FirstName eq 'Test1'").DeleteEntriesAsync();

However, the following fails:

var commandText = client.For("People").Filter("FirstName eq 'Test1'").GetCommandTextAsync().Result;
var result = client.DeleteEntriesAsync("People", commandText);

And the error in Fiddler is

![image](https://cloud.githubusercontent.com/assets/13030742/11556417/5f061abe-99e1-11e5-8849-dd47d34fa5d5.png)

Cheers!

**Comment by object** [comment]
Thanks for the issue report, will have a look.

**Comment by mwchan** [comment]
Hi,

I was just wondering when would 4.14 be released?

Thanks!

**Comment by object** [comment]
Sorry for being slow with this (and other) fixes but I plan to release a new version by the end of the month. I will let you know when it's ready.

**Comment by mwchan** [comment]
Thank you. Appreciate it!

**Comment by object** [comment]
Fixed in 4.14.
