### ISSUE TITLE
Batch handler called twice

### ISSUE THREAD

**Issue by aki1729** [object/Simple.OData.Client#181]
In the following code sample, I am adding only one GET call to the batch, but the handler is getting invoked twice.

```C#
    var endpoint = "https://services.odata.org/V4/(S(vhodt3nnka0pencngtxlbg3l))/TripPinServiceRW";
    var collection = "People";
    var key = "russellwhyte";

    var results = new List<object>();
    var batch = new ODataBatch(new ODataClient(endpoint));

    batch += async c =>
    {
        var query = c.For(collection).Key(key);
        var result = await query.FindEntriesAsync();
        if (null != result)
        {
            results.Add(result);
        }
    };

    await batch.ExecuteAsync();

    Console.WriteLine("Result count: " + results.Count); // Displays "Result count: 2"
```

Note that there is only one call being added to the batch, but when printing the result, the count is 2.

I am using the Simple.OData.Client.V4.Adapter, Version: 4.13.0.0, Runtime Version: v4.0.30319

**Comment by object** [comment]
Actually this is not a bug although it looks confusing. If you check the communication with Fiddler you will see that HTTP POST with OData batch is written correctly and there is only GET there. The reason the result count is 2 is that the lambda that you define for batch execution is executed twice: first time to record batch operations for subsequent execution, and second time to assign operation results to local variables. With this in mind you should move all statements not related to batch operations (like results.Add(...)) out of the batch lambda.
