### ISSUE TITLE
If use Convert.ToInt32 inside Filter then it gives exception.

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#183]
I observed that If I use Convert.ToInt32() inside filter then it gives exception.
strange is that exception is null.

and if I use 

string mystringId= "123";

var packages = await client
    .For < Package > ()
    .Filter(x => x.MyID== Convert.ToInt32(mystringId))
    .FindEntriesAsync();

the above will give null exception.

and I used ODataExpression It will through Convertion exception.
var filter = new ODataExpression < Package > (x => x.MyID== Convert.ToInt32(mystringId));

**Comment by object** [comment]
I'll investigate why it throws NullReferenceException instead something more decent, but in general you can not send any expression to Filter - the library parses the Filter expression and builds an OData command from it, so it can not expect any C# expression there.

**Comment by ashuthinks** [comment]
yes later after I used more good managed code in filter but i found this to be reported so post it , thanks

**Comment by object** [comment]
Fixed in 4.14.
