### ISSUE TITLE
Simple.Odata don't run when fiddler is not open

### ISSUE THREAD

**Issue by ramon26cruz** [object/Simple.OData.Client#186]
I got this error when I make a call to Odata when fiddler is not open

<i>
<Message>An error has occurred.</Message>
<ExceptionMessage>An error occurred while sending the request.</ExceptionMessage>
<ExceptionType>System.Net.Http.HttpRequestException</ExceptionType>
</i>

**Comment by object** [comment]
This has nothing to do with the library. Check if Fiddler activates the proxy that affects the HTTP communcation.
