### ISSUE TITLE
Skip and Count data types mismatch

### ISSUE THREAD

**Issue by Makison** [object/Simple.OData.Client#187]
IFluentClient<T,FT> - Skip(int count);
however 
ODataFeedAnnotations Count has value type long?

Not sure if someone has values range greater than int but currently we can't get last page in theory for long? Count. 

Thanks

**Comment by object** [comment]
That's a good point, I will make them having same type.

**Comment by object** [comment]
I've changed Top/Long type from int to long, however since this is a public interface change it requires major version update, so this fix will be released when version 5.0 is out.

**Comment by Makison** [comment]
Thank you! You are doing great job!

**Comment by object** [comment]
Thanks, my pleasure!
