### ISSUE TITLE
Sign assemblies

### ISSUE THREAD

**Issue by lplotnikov** [object/Simple.OData.Client#190]
I've realised that your assemblies is not signed with strong name in and it becomes a problem to use it as NuGet packages. Would you mind signing your code?

**Comment by object** [comment]
Hi,
This issue has been discussed previously here: https://github.com/object/Simple.OData.Client/issues/155

There is also a long discussion thread about signing vs. not signing here:
http://nuget.codeplex.com/discussions/247827

BTW, signing has nothing to do with NuGet packages, there are hundreds if popular NuGet packages with assemblies that are not signed.

In short: if you absolutely must have a strong name, you can sign it yourself using some tools mentioned in a referenced issue above.

**Comment by lplotnikov** [comment]
Thanks!
