### ISSUE TITLE
Insert byte[] array using O'Dataclient  to database

### ISSUE THREAD

**Issue by sunny009000** [object/Simple.OData.Client#195]
I need to know, how can I insert byte[] array using O'Dataclient  to sql database.

I have my code =>
 
byte[] data = target.ToArray();

       Client.For<MyClass>()
                                              .Set(new MyClass
                                              {
                                                  AssemblyByte = data
                                              })
                                              .InsertEntryAsync();

My domain class is => 

 public class MyClass
    {
        public byte[] AssemblyByte { get; set; }
        public Guid Id { get; set; }
    }

but It shows me Internal server error. 
Could anyone have any idea , how can I insert  AssemblyByte  to database.

**Comment by object** [comment]
How is AssemblyByte defined in your OData service? Can you check the service metadata?

**Comment by sunny009000** [comment]
AssemblyByte  is name of my property in MyClass as

byte[] data = target.ToArray();

public class MyClass
{
public byte[] AssemblyByte { get; set; }
public Guid Id { get; set; }
}

I have directly assign the data  to AssemblyByte i.e AssemblyByte = data

Is this something wrong with my syntax

**Comment by object** [comment]
This is fine but I would like to know is how AssemblyByte is exposed by your OData service. All your entities are mapped to OData types, so even if you use byte array in your local code it might be mapped to Edm.Binary type, this is what I'd like to know. So please check the following:

1. Get your service metata available at [SERVICE_URL]/$metadata address. Check how AssemblyByte is defined there.
2. Check your communication in an app like Fiddler and see what is sent to the service (HTTP payload) - if it is ever sent.

**Comment by sunny009000** [comment]
Are u talking about this ?
I have nothing in my service, I just call insert of O'data directly, I think it should maintain everything internally.

 public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API routes
            config.MapHttpAttributeRoutes();

            ODataModelBuilder builder = new ODataConventionModelBuilder();
            builder.EntitySet<MyClass>("MyTable");

            config.MapODataServiceRoute(
                routeName: "client",
                routePrefix: "route",
                model: builder.GetEdmModel());

        }

and in context

 public class DbContext : ConventionBaseDbContext
    {
        public DbContext()
            : base("DataBase")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

        public virtual DbSet<MyClass> MyClass{ get; set; }

    }

**Comment by object** [comment]
Yes, this is what I meant, so it's Edm.Binary which corresponds to a byte array. Now I need to know what kind of error is raised i.e. whether exception happens in the client or it is the service that returns HTTP error code. Can you check run your program while having Fiddler session open and check the HTTP traffic? Note that Simple.OData.Client simply generates HTTP requests so in order to find out what's wrong it's important to understand whether such HTTP request was generated and if so what was the response.

**Comment by object** [comment]
And just to test if it works with strings, can you try the following:

public class MyClass
{
public string AssemblyByte { get; set; }
public Guid Id { get; set; }
}

and when calling Insert: AssemblyByte = Convert.ToBase64String(data)

Does it still fail? (and if so, Fiddler output would be useful)

**Comment by object** [comment]
Hi again,

I ran some tests and they worked, so there can something that your OData service doesn't accept. However I found and fixed a bug that might affect base64 conversion for JSON payload. Can you try the newest version 4.14.2, try both scenarios: the one that you wrote yourself and the one I suggested with using Convert.ToBase64String (and defining AssemblyByte as string).

**Comment by sunny009000** [comment]
for 
public class MyClass
{
public string AssemblyByte { get; set; }
public Guid Id { get; set; }
}

It properly works

but 

public byte[]AssemblyByte { get; set; }

doesn't work.

**Comment by sunny009000** [comment]
I'll explain u complete problem 

=> I need to store AssemblyByte  in sql table
=> In sql table i have assigned datatype VarBinary for AssemblyByte  column
=> In c# my class property is 
public class MyClass
{
**public byte[]AssemblyByte { get; set; }**
public Guid Id { get; set; }
}

=> Now , I need to insert byte via o'dataclient
e.g.
byte[] data = target.ToArray();

   Client.For<MyClass>()
                                          .Set(new MyClass
                                          {
                                              AssemblyByte = data
                                          })
                                          .InsertEntryAsync();

=> It shows me Internal server error in web api. even I didn't wright down any thing in my web api. I just inherit mu web api from odata.

what is the wrong one Iam doing

**Comment by sunny009000** [comment]
Yes its now working.

**Comment by object** [comment]
Good to know!
