### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by KevinBurton** [object/Simple.OData.Client#196]
I tried to install this package and I get:
. . . . .
Successfully added 'Microsoft.Bcl 1.1.9' to ODataClient.
Adding 'Microsoft.Bcl.Async 1.0.168' to ODataClient.
Uninstalling 'Microsoft.Bcl.Async 1.0.168'.
Successfully uninstalled 'Microsoft.Bcl.Async 1.0.168'.
Uninstalling 'Microsoft.Bcl 1.1.9'.
Successfully uninstalled 'Microsoft.Bcl 1.1.9'.
Install failed. Rolling back...
Install-Package : Failed to add reference to 'System.Net'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:16
+ Install-Package <<<<  Simple.OData.Client
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by object** [comment]
I encounter this from time to time and AFAIK this is NuGet-related issue. From your description I suspect the failing package is Microsoft.Bcl.Async or Microsoft.Bcl. Can you try adding them manually first? What platform are you building the application for?

**Comment by KevinBurton** [comment]
I don't get any errors but I cannot seem to resolve ODataClient when used as

var client = new ODataClient("http://...");

**Comment by KevinBurton** [comment]
I now have the following code:
using Simple.OData.Client;
namespace DFI.Data.Client{ class Program { static async void
Main(string[] args) { var client = new
ODataClient("http://localhost:50056/odata/"); var orgs = await
client.FindEntriesAsync("TOrgs"); foreach (var org in orgs) {
System.Diagnostics.Debug.WriteLine(org["fID"]); } } }}

But the "rebuild all" fails. There are three warnings that
Simple.OData.Client. could not be found so it seems that these
packages were not installed correctly after all. Ideas?
Kevin

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Mon, 15 Feb 2016 02:38:29 -0800
Subject: Re: [Simple.OData.Client] Install failed (#196)

	I encounter this from time to time and AFAIK this is NuGet-related
issue. From your description I suspect the failing package is
Microsoft.Bcl.Async or Microsoft.Bcl. Can you try adding them manually
first? What platform are you building the application for? 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/196#issuecomment-184160119

**Comment by KevinBurton** [comment]
When I remove the assembly references that "could not be found" and
then try to add them back using browse I get the same warning message
that the assembly could not be found? Again I just want this simple
code to work:
using Simple.OData.Client;
namespace DFI.Data.Client{ class Program { static async void
Main(string[] args) { var client = new
ODataClient("http://localhost:50056/odata/"); var orgs = await
client.FindEntriesAsync("TOrgs"); foreach (var org in orgs) {
System.Diagnostics.Debug.WriteLine(org["fID"]); } } }}

Ideas?

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Mon, 15 Feb 2016 02:38:29 -0800
Subject: Re: [Simple.OData.Client] Install failed (#196)

	I encounter this from time to time and AFAIK this is NuGet-related
issue. From your description I suspect the failing package is
Microsoft.Bcl.Async or Microsoft.Bcl. Can you try adding them manually
first? What platform are you building the application for? 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/196#issuecomment-184160119

**Comment by KevinBurton** [comment]
When I use the package manager console even though the ultimate
message is "success" I get a red error message:
Successfully added 'Microsoft.Bcl.Build 1.0.14' to
DFI.Data.Client.File
H:ODataDFI.Data.ClientpackagesMicrosoft.Bcl.Build.1.0.14toolsInstall.ps1
cannot be loaded. The file
H:ODataDFI.Data.ClientpackagesMicrosoft.Bcl.Build.1.0.14toolsInstall.ps1
is not digitally signed. The script will not execute on the system.
Please see "get-help about_signing" for more details..At line:1
char:2+ & 

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/196#issuecomment-184160119

**Comment by object** [comment]
Something seems to be broken in your project setup (btw which platform is it? Are you using Xamarin or VS project?) What you might try just to check if other stuff builds fine is to fetch the source code from this repository and build some of its test projects, then run the tests and see if they are green. Then you can try manually adding references to Simple.OData.Client to your app from that (fetched from GitHub) project instead of using NuGet packages and check whether your app builds and runs.

Can't suggest anything else at this level because I simply don't understand what can be wrong with your setup comparing to all others.

**Comment by KevinBurton** [comment]
I am using Visual Studio 2013. I just try to create a new project with
"new project". I am on Windows 7. Like i indicated I tried to manually
add the references but they still show up as a warning. All of the
NuGet packages have a green check box by them which seems to indicate
the NuGet install succeeded but it looks like the installation is
still missing something.

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Mon, 15 Feb 2016 06:45:59 -0800
Subject: Re: [Simple.OData.Client] Install failed (#196)

	Something seems to be broken in your project setup (btw which
platform is it? Are you using Xamarin or VS project?) What you might
try just to check if other stuff builds fine is to fetch the source
code from this repository and build some of its test projects, then
run the tests and see if they are green. Then you can try manually
adding references to Simple.OData.Client to your app from that
(fetched from GitHub) project instead of using NuGet packages and
check whether your app builds and runs. 

	Can't suggest anything else at this level because I simply don't
understand what can be wrong with your setup comparing to all others. 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/196#issuecomment-184235819

**Comment by KevinBurton** [comment]
I tried downloading the .zip and building it and I get two errors:
Error 1 'Allow unsafe code' is not supported by one or more of the
project's targets.
H:ODataSimple.OData.Client-masterSimple.OData.Client.CoreSimple.OData.Client.Core.csproj
0 0 Simple.OData.Client.Core
and
Error 11 Source file 'AdHocTests.cs' could not be found
H:ODataSimple.OData.Client-masterSimple.OData.Client.IntegrationTestsCSC
Simple.OData.Client.IntegrationTests

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Mon, 15 Feb 2016 06:45:59 -0800
Subject: Re: [Simple.OData.Client] Install failed (#196)

	Something seems to be broken in your project setup (btw which
platform is it? Are you using Xamarin or VS project?) What you might
try just to check if other stuff builds fine is to fetch the source
code from this repository and build some of its test projects, then
run the tests and see if they are green. Then you can try manually
adding references to Simple.OData.Client to your app from that
(fetched from GitHub) project instead of using NuGet packages and
check whether your app builds and runs. 

	Can't suggest anything else at this level because I simply don't
understand what can be wrong with your setup comparing to all others. 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/196#issuecomment-184235819

**Comment by object** [comment]
That's actually OK. "Allow unsafe code" is not a real error and can be ignored (the project still builds). And just delete AdHostTests.cs from the project, this file is for some internal testing. You should be able to build the whole thing and run some tests. There is a huge number of tests, try just a few to see they are working. Then inspect your project, see what's different. You can just include references directly from the library sources instead of using NuGet. I am really puzzled what's going on with your project since there are about 30K downloads of various NuGet packages for this library, and I don't get such reports. You can send me your project to vagif.abilov at gmail.com, I can try building it myself to see what's wrong.

**Comment by KevinBurton** [comment]
After a few tries I was able to get the project to build. Thank you for your help.

**Comment by object** [comment]
Good to know!
