### ISSUE TITLE
unable to read service BaseUrl property from ODataClient

### ISSUE THREAD

**Issue by RavindraBarapatre** [object/Simple.OData.Client#197]
Hello,

We are generating service BaseUrl run time and passing internally to ODataClient();

We want to do unit test on ODataClient() baseurl. But we don't have access to BaseUrl property in code from ODataclient object.

Can you please provide public property to read **oDataClient.BaseUrl**?

Thanks

**Comment by object** [comment]
Hello,
You can initiate ODataClient with ODataClientSettings instance with all client settings including BaseUrl. Will this help?

**Comment by RonakThakkar** [comment]
We would like to retrieve URL after its there in ODataClelient in our unit
tests to compare.

On Feb 10, 2016 8:56 PM, "Vagif Abilov" <notifications@github.com> wrote:
>
> Hello,
> You can initiate ODataClient with ODataClientSettings instance with all
client settings including BaseUrl. Will this help?

**Comment by object** [comment]
Hmm, I am not sure I fully understand your intention. Can you please give me a code example assuming you have access to BaseUrl? How would your test look like?

**Comment by RonakThakkar** [comment]
I have created a BaseClient : ODataClient. 
These BaseClient create URL based on the pattern defined in our project and based on the input parameters passed to BaseClient.

I have unit test case project where I need to check the URL generated is correct for the input parameters provided. If I am not able to write unit test case, I have to verify them manually If I change some logic and also my unit test case coverage is badly affected as I have many ClientWrappers derives from BaseClient

**Comment by object** [comment]
ODataClientSettings has a property BaseUri. You should be able to use that.
