### ISSUE TITLE
Chaining string methods

### ISSUE THREAD

**Issue by pandazzurro** [object/Simple.OData.Client#199]
Hi Vagif, we are experiencing an issue trying to match the company_name field with the 'xxx' because the client seems to not chain the contains and toLower operators.
In particular the filter clause in the url we want should be the following: [$filter=contains(tolower(company_name),'xxx')].
The c# code generating it is:

```
Client.For<company>()
         .Filter(x => x.company_name.ToLower().Contains("enerj"))
         .FindEntriesAsync()
         .Result;
```

We wait to hear something for you, please.
Bye

**Comment by object** [comment]
Hi,
I can have a look at it. Can you check how is filter currently generated by the library?

**Comment by marcomezzanotte** [comment]
Hi.

The URL generated (caught from the BeforeRequest action set on ODataClientSettings) by the call
```
Client.For<company>()
       .Filter(x => x.company_name.ToLower().Contains("enerj"))
       .FindEntriesAsync().Result;
```
 is
`~/odata/companies?$filter=tolower(company_name)`

instead we would like a URL like
 `~/odata/companies?$filter=contains(tolower(company_name),'enerj')`

@pandazzurro

**Comment by object** [comment]
Thanks, I'll investigate.

**Comment by object** [comment]
Fixed, will be released in 4.15.1.

**Comment by object** [comment]
4.15.1 is out now.

**Comment by pandazzurro** [comment]
**@object  Great job!**
@marcomezzanotte

**Comment by object** [comment]
Thanks!
