### ISSUE TITLE
Actions?

### ISSUE THREAD

**Issue by KevinBurton** [object/Simple.OData.Client#201]
I couldn't see in the samples or documentation how to invoke an action or function?

**Comment by object** [comment]
This is a test project for both actions and functions (this one is for OData V4 but there is a similar one for V3): https://github.com/object/Simple.OData.Client/tree/master/WebApiOData.V4.Samples.Tests

**Comment by KevinBurton** [comment]
I am assuming that 'For<T>' gives me   the equivalent of the TOrgs part of this URL 
"odata/TOrgs/GetOrganizationByTypeAndStatus(type='01', status='DLQ')'
and Set specifies the payload for the POST. How does the action call go if I don't have an object for 'For'?

**Comment by KevinBurton** [comment]
I tried
 var actionTask =
client.ExecuteActionAsEnumerableAsync("GetOrganizationByTypeAndStatus",
new Dictionary() { { "type", "01" }, { "status", "DLQ" } });
But I get an exception with the message:
Microsoft.OData.Core.ODataException: Unsupported primitive type. A
primitive type could not be determined for an instance of type
'System.Char'.

	-----------------------------------------From: "Kevin Burton" 
To: "object/Simple.OData.Client"
Cc: "object/Simple.OData.Client"
Sent: Tue, 16 Feb 2016 07:49:47 -0600
Subject: Re: [Simple.OData.Client] Actions? (#201)

    I am assuming that 'For' gives me the equivalent of the TOrgs part
of this URL   "odata/TOrgs/GetOrganizationByTypeAndStatus(type='01',
status='DLQ')'   and Set specifies the payload for the POST. How does
the action call go if I don't have an object for 'For'?   

   On Feb 15, 2016, at 10:55 PM, Vagif Abilov  wrote:

	This is a test project for both actions and functions (this one is
for OData V4 but there is a similar one for V3):
https://github.com/object/Simple.OData.Client/tree/master/WebApiOData.V4.Samples.Tests
[2] 

	—
 Reply to this email directly or view it on GitHub [3].       

Links:
------
[1] mailto:notifications@github.com
[2]
https://github.com/object/Simple.OData.Client/tree/master/WebApiOData.V4.Samples.Tests
[3]
https://github.com/object/Simple.OData.Client/issues/201#issuecomment-184519104

**Comment by object** [comment]
If you have an unbound action/function, i.e. there is no object for For as you formulated it, you should be able to use client.Unbound syntax, check the test in the source code that I referenced earlier.

**Comment by KevinBurton** [comment]
The function/action is not really unbound. It is bound to the
collection. This doesn't work but am I going down the right path with:
 var actionTask =
client.ExecuteActionAsEnumerableAsync("TOrgs/GetOrganizationByTypeAndStatus",
new Dictionary() { { "type", new string[] {"01"} }, { "status", new
string[] {"DLQ"} } });
I want to mimic a call like
 POST odata/TOrgs/GetOrganizationByTypeAndStatus HTTP/1.1
Content-Type: application/json Content-Length: 51
 {"type" : ["01"], "status" : ["DLQ"]}

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Tue, 16 Feb 2016 06:31:04 -0800
Subject: Re: [Simple.OData.Client] Actions? (#201)

	If you have an unbound action/function, i.e. there is no object for
For as you formulated it, you should be able to use client.Unbound
syntax, check the test in the source code that I referenced earlier. 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/201#issuecomment-184702011

**Comment by KevinBurton** [comment]
This is to clarify that the "action" that want to call is a bound
function. I just don't have an object type to supply to For.

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Tue, 16 Feb 2016 06:31:04 -0800
Subject: Re: [Simple.OData.Client] Actions? (#201)

	If you have an unbound action/function, i.e. there is no object for
For as you formulated it, you should be able to use client.Unbound
syntax, check the test in the source code that I referenced earlier. 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/201#issuecomment-184702011

**Comment by object** [comment]
I see. But can you define a type to send to For? Or simply send a collection name, like for untyped syntax? Then you can use something like For(...).Action(...).ExecuteAsArrayAsync<SomeType>() where SomeType is a return collection type if this is a collection.

**Comment by KevinBurton** [comment]
I am afraid you will have to send me pseudo-code for me to understand. Right now my main stumbling block is I don't understand how the type that I define tells the client how to form the request URL.

**Comment by object** [comment]
The types work simple: the library uses type and its property names to build request URL. For example, if the type is called Customers then the library will try to search service metadata for a collection called "Customers" or "Customer" (it's relatively flexible), so types simply gives some naming hints. So if you have an action bound to an entity set Customer you call For<Customer>().Action("MyAction") followed by a command to fetch either single result, scalar, array etc. If you call ExecuteAsArray<People> then the type People is expected to contain properties that can be matched to the response fields.

**Comment by object** [comment]
You can also look here for some examples of actions, functions and type mapping:

https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.IntegrationTests/TripPinTests.cs

**Comment by KevinBurton** [comment]
Sorry it is just not working. I have
 var actionTask = client.For("TOrgs")
.Action("GetOrganizationByTypeAndStatus") .Set(new Dictionary()
{{"type", new string[] {"01"}}, {"status", new string[] {"DLQ"}}})
.ExecuteAsEnumerableAsync();
And I get a SImple.OData.Client..WebException with a message of "Not
Found". I have 
 config.EnableUnqualifiedNameCall(unqualifiedNameCall: true);
But I notice that the client is making the call to 
http://localhost:50056/odata/TOrgs/Default.GetOrganizationByTypeAndStatus

Notice the 'Default' namespace. I think that is why it is "Not Found".
Can the namespace be removed or honor the configuration setting on the
OData server?
Kevin

	-----------------------------------------From: "Vagif Abilov" 
To: "object/Simple.OData.Client"
Cc: "KevinBurton"
Sent: Tue, 16 Feb 2016 11:59:43 -0800
Subject: Re: [Simple.OData.Client] Actions? (#201)

	The types work simple: the library uses type and its property names
to build request URL. For example, if the type is called Customers
then the library will try to search service metadata for a collection
called "Customers" or "Customer" (it's relatively flexible), so types
simply gives some naming hints. So if you have an action bound to an
entity set Customer you call For().Action("MyAction") followed by a
command to fetch either single result, scalar, array etc. If you call
ExecuteAsArray then the type People is expected to contain properties
that can be matched to the response fields. 

	—
 Reply to this email directly or view it on GitHub [1].     

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/201#issuecomment-184854853

**Comment by object** [comment]
I think what happens is that since you enable unqualified name calls, you get "Default" namespace in OData service metadata and this is what the library uses because it doesn't have similar setting on the client site so it swallows "Default" as namespace name.

I'll investigate possible workarounds on the client site. In the meantime if it's possible for you to disalow unqualified calls and handle correctly namespaces on the server side, it should make it work.

**Comment by object** [comment]
I just pushed a new version 4.16.0 with addition ODataClientSettings property UnqualifiedNameCall that corresponds to EnableUnqualifiedNameCall on the server side. If you set it to true, the library is supposed to generate URI with un-prefixed names for functions and actions.

**Comment by KevinBurton** [comment]
I upgraded but now I get the error (actually it shows up as a warning but it prevents the build from completing) that Simple.OData.Client.Dynamic an ...V4.Adapter could not be found.

**Comment by KevinBurton** [comment]
I restarted VS and all is well. I now can call an unqualified action! Thank you.

**Comment by object** [comment]
Good to know!
