### ISSUE TITLE
InsertEntryAsync does not work if entity contains Collection(Edm.Guid)

### ISSUE THREAD

**Issue by krombipils** [object/Simple.OData.Client#204]
If trying to insert an entry containing a Collection(Edm.Guid) property, there is a problem in Simple.OData.Client.V4.Adapter.RequestWriter:
In line 356 you are trying to cast the passed value to an IEnumerable<object>

`Items = (value as IEnumerable<object>).Select(x => GetPropertyValue(collection.ElementType(), x)),`

But covariance doesn't work for value types (like Guid), therefore the result of this cast is null and the following Select fails.
I fixed this line of code locally:
`Items = ((IEnumerable)value).Cast<object>().Select(x => GetPropertyValue(collection.ElementType(), x))`

**Comment by object** [comment]
Thanks, I will check the code and update it.
