### ISSUE TITLE
UpdateEntryAsync ignores PreferredUpdateMethod

### ISSUE THREAD

**Issue by mbreemans** [object/Simple.OData.Client#205]
When doing an update with the Simple OData Client I want to force it to use PUT instead of PATCH to our endpoint. This because our endpoint (SAP) only accepts PUT.

Settings:
```
var oDataSettings = new ODataClientSettings(endpoint)
{
    PreferredUpdateMethod = ODataUpdateMethod.Put,
    Credentials = credentials,
    IgnoreResourceNotFoundException = true,
    OnTrace = (x, y) => CMS.Log.Logger.WebserviceLogger.Debug(string.Format(x, y))
};

```

Update method:
```
var result = await client.For("UserRequestActivationRequestCollection")
            .Key(requestID)
            .Set(new 
            {
                ActivationKey = activationKey,
                RequestID = requestID
            }).UpdateEntryAsync();

```

Shouldn't it use PUT when setting the preferred update method to PUT?

**Comment by object** [comment]
Preferred doesn't mean prescribed. This depends on whether PUT satisfies the verb selection criteria that is based on what data is sent in Set clause. PUT is quite strong verb demanding that all entity properties are overwritten with supplied data. So it implies supplying all such data. It may also mean that you have to fetch them first, potentially increasing number of network roundtrips.

Can you rewrite your call and send all properties in Set clause? Yes, this means you may need to fetch them first.

I don't know if SAP accepts PUT with a partial field set. If so, I may need to add additional setting property that will force particular verb, although this is quite ugly.

**Comment by mbreemans** [comment]
Thanks for the fast answer, can you give an example how to rewrite the call in the Set clause? ( I am already sending all fields). The endpoint doesn't accept a GET either, only PUT but I can get the data from somewhere else, so overwriting shouldnt be a problem

**Comment by object** [comment]
So you are saying that you are sending all fields already? Does UserRequestActivationRequestCollection only has ActivationKey and RequestID? If so, just for the sake of a test, can you try not sending RequestID since it's a key? If it all fails, I will need to investigate it further.

**Comment by object** [comment]
I believe I managed to reproduce the problem. Working on it.

**Comment by mbreemans** [comment]
It works! Thanks!

**Comment by object** [comment]
Good to know!
