### ISSUE TITLE
Using Odata Filter and how to get a single value from list?

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#206]
I tried like following with Odata filter

var agreementIds = new List< Guid >();
agreementIds .Add("rt2348F1-grDA-E511-80C7-000D3AB24C19");
agreementIds .Add("g09B68F1-u6DA-E511-80C7-000D3AB24C19");
agreementIds .Add("D09B68F1-k5DA-E511-80C7-000D3AB24C19");

var agreementFilter = new ODataExpression< ExtEnergyRatingSeries >(x => agreementIds.Contains(x.ExtAgreementId));

var extPeriodIds = await dataServiceClient.For< ExtEnergyRatingSeries >()
                                                        .Filter(agreementFilter)
and getting following error :

The type 'System.Collections.Generic.List`1[System.Guid]' is not supported when converting to a URI literal.
any clue?
not working for multiple no IN clause in Odata I know but how do I work with above?

**Comment by object** [comment]
Not every LINQ expression can be converted to OData query URI. Can you express the query you are trying to execute using OData notation?

**Comment by ashuthinks** [comment]
having a list of guid and want to select one of it.
like in sql we use IN clause. 
So creating a filter for IN clause and will use it.
can you help me?

**Comment by object** [comment]
I don't think this is supported in OData, it's in proposal:

https://issues.oasis-open.org/browse/ODATA-556

The closest you can do is to replace it with a series of OR:

http://stackoverflow.com/questions/7745231/odata-where-id-in-list-query

So in short: no, this currently is not supported by OData, when constructing queries you should always bear in mind how they are mapped to OData URI.
