### ISSUE TITLE
can I use anything like batch update instead of forloop to update multiple records using simple odata?

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#207]
I want to update 10 records and I'm currently using for loop to do so like below.

    foreach (var custDetails in deserializeCustomerDetail.customerDetails)
                    {
                        await myClient.For<CustomerDetail>().Key(Id).Set(new { 
    					Key = custDetails.Key, Value = custDetails.Value }).UpdateEntriesAsync();
                    }

If I'm doing this for multiple records , multiple time request will
 go. How do I make it more optimized using something like batch or any
 other option?

**Comment by object** [comment]
You can use OData batch. Look at examples (check out tests for this library).
