### ISSUE TITLE
Add default filter in each service request.

### ISSUE THREAD

**Issue by RavindraBarapatre** [object/Simple.OData.Client#208]
Hello,

We have created **MasterDataClient:ODataClient**

We have requirement to append **fix Filter condition in each service request** in client.

Can we do that or Can we extend functions like FindExntriesAsync, InsertEntryAsync etc as per our need?

Thanks.

**Comment by object** [comment]
Hello,

Since this is an open source library, you can always make custom changes to it to fit your specific needs. But if you think your changes may be of a general use for others, it's worth apply them back to the library. It will also beneficial for you since you won't need to maintain your custom source branch. From what you wrote I didn't get a picture of what extensions to Filter you need to implement. If you share some of your thoughts, we can figure out if this is something that can be added to the library.

**Comment by RavindraBarapatre** [comment]
Thanks for suggestions and quick response.

In our case we want to add **CompanyId** filter in every service request in **Multi Company architecture**.

Can we get odata query generated by Simple.Odata.Client before executing service request?

If you have any example please share it. 

Thanks

**Comment by object** [comment]
Version 5 of the library will support adding custom query options. Right now you can perhaps execute GetCommandTextAsync to retrieve generated query URI, then extend it with whatever needed and run the customized query.

**Comment by sixlettervariables** [comment]
You could also consider the simple approach (if you only perform searches using OData):

```csharp
public class MultiCompanyODataApi : IDisposable
{
    private readonly ODataClient client;
    private readonly int companyId;
    
    public MultiCompanyODataApi(ODataClient client, int companyId)
    {
        if (client == null) throw new ArgumentNullException(nameof(client));
        
        this.client = client;
        this.companyId = companyId;
    }
    
    public IBoundClient<T> For<T>()
    {
        return this.client.For<T>()
                          .Filter($"CompanyID eq {companyId:0}");
    }
    
    ...
}
```

Or the slightly more involved approach which would be wrapping `IBoundClient<T>`:

```csharp
internal class FilteredBoundClient<T> : IBoundClient<T>
{
    private IBoundClient<T> client;
    private readonly string filterExpression;
    
    public FilteredBoundClient(IBoundClient<T> client, string filterExpression)
    {
        if (client == null) throw new ArgumentNullException(nameof(client));
        if (filterExpression == null) throw new ArgumentNullException(nameof(filterExpression));
        this.client = client;
        this.filterExpression = filterExpression;
    }
    
    internal IBoundClient<T> FilteredClient
    {
        get { return this.client.Filter(filterExpression); }
    }
    
    // ... returning FilteredClient if a "leaf"
    
    public Task<IEnumerable<T>> FindEntriesAsync()
    {
        return FilteredClient.FindEntriesAsync();
    }
    
    public Task<IEnumerable<T>> FindEntriesAsync(CancellationToken cancellationToken)
    {
        return FilteredClient.FindEntriesAsync(cancellationToken);
    }
    
    // Perform actions on our client and return 'this' for all non-leaf
    
    public IBoundClient<T> Set(object value)
    {
        this.client = this.client.Set(value);
        return this;
    }
    
    // ...etc etc...
}  
```
Which you would use in the prior example:

```csharp
public class MultiCompanyODataApi : IDisposable
{
    private readonly ODataClient client;
    private readonly int companyId;
    
    public MultiCompanyODataApi(ODataClient client, int companyId)
    {
        if (client == null) throw new ArgumentNullException(nameof(client));
        
        this.client = client;
        this.companyId = companyId;
    }
    
    public IBoundClient<T> For<T>()
    {
        return new FilteredBoundClient<T>(this.client, $"CompanyID eq {companyId:0}");
    }
    
    // ...
}
```

**Comment by RavindraBarapatre** [comment]
This is really awesome. :+1:  :)
It will help us.

Thanks for efforts.

**Comment by object** [comment]
Thank you Christopher, very well explained.
