### ISSUE TITLE
query inherited  class

### ISSUE THREAD

**Issue by egarim** [object/Simple.OData.Client#211]
is there any special syntax to query inherited classes
lets say that we have class A with a property name, and class B that inherit from A,

lets say I want to filter Class B by name

IEnumerable<IDictionary<string, object>> Activities = await _Client
                                          .For("ClassB")
                                          .Filter("name eq 'Jose'")
                                          .FindEntriesAsync();

this return an error like this
Could not find a property named 'name ' on type 'ClassA'.

**Comment by object** [comment]
Hi,

Please have a look at some tests:
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Tests.Net40/FindTypedTests.cs

Scroll down until you find tests for base class and derived class. Let me know if this doesn't answer your question.
