### ISSUE TITLE
Windows solution doesn't compile

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#212]
If I load the Simple.OData.Client.Win solution I get a couple of issues that means it won't compile
1. Source file "AdHocTests.cs" could not be found - Simple.OData.Client.IntegrationTests
2. Allow unsafe code is not supported by one or more of the project's target types - Simple.OData.Client.Core
3. Simple.OData.ProductService fails to load

I can fix these if you want

**Comment by object** [comment]
Sorry for your problems. Here is a quick workaround:

1. Just remove AdHostTests.cs from the project. These are just... well ad-hoc tests that are not supposed to be checked in, I will update the project file later.
2. This should not prevent project from being built, just ignore this one.
3. Not sure why it fails to load, need more information, but you should be able to compile the rest of solution without it. Let me know specific error details.

**Comment by phatcher** [comment]
Vagif

No problem, I can remove the file...
Simple.OData.ProduceService fails as it's bound to IIS and I typically don't run as an admin, if you bind it to IISExpress instead that would work.

**Comment by object** [comment]
Thanks for the input, that's reasonable suggestion.
