### ISSUE TITLE
Error missing concurrency-token property

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#215]
Hi,

I was able to reproduce the same issue #177 when referencing the source code of the Master branch from https://github.com/object/Simple.OData.Client but do not get the same issue when referencing the latest dll directly from NuGet.

![image](https://cloud.githubusercontent.com/assets/13030742/13768186/f7888f7a-eaad-11e5-929b-85c47f707c30.png)

I then dig deeper and found out that the Master branch does not seem to be the latest code as the code was failing because it did not have the optional parameter "bool includeAnnotationsInResults = false" in GetResponseAsync method in the V4 Response reader class.  Looks this it was removed in June. Was this done on purpose?

https://github.com/object/Simple.OData.Client/commit/f53269f9f2887f247e2d7c683248a8cbd83533e0

Thanks!

**Comment by object** [comment]
Hi,
Yes it was removed on purpose due to changes in annotation implementation in version 5 (master represents future v5 while current version is in the branch v4). So in order to compile current code you should use branch v4.

**Comment by mwchan** [comment]
Thanks for the confirmation!
