### ISSUE TITLE
UpdateEntryAsync ignores PreferredUpdateMethod

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#216]
This was fixed in #152 but then "broken/changed" when fixing #205. I am wondering what the reason is for changing 

`var usePatch = _session.Settings.PreferredUpdateMethod == ODataUpdateMethod.Patch || !hasPropertiesToUpdate || !HasUpdatedKeyProperties(collection, entryKey, entryData);`

to

```
var usePatch = _session.Settings.PreferredUpdateMethod == ODataUpdateMethod.Patch || !hasPropertiesToUpdate;
if (HasUpdatedKeyProperties(collection, entryKey, entryData))
                usePatch = false;
```

Can I force PATCH to be the preferred method?

Thanks!!

**Comment by object** [comment]
The reason for chaning it was simple: there was a bug that incorrectly chose the verb. In case update payload contains changed key, PATCH can not be used. Is this the case?

**Comment by mwchan** [comment]
Yup. One of the key was changed. Thanks for your explanation.
