### ISSUE TITLE
Action with Enum parameter

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#218]
Hi,

In versions 4.16.0 and before, I was calling an Action using the following method:

```
var paramDict = new Dictionary<string, object>
                                {
                                    {"stringParam", "myStringParam"
                                    { "enumParam", new ODataEnumValue("myEnumValue")
                                };
await client.For("MyEntity").Action("MyAction").Set(paramDict).ExecuteAsSingleAsync();
```

And in Fiddler, you can see that the enumParam is being sent as

`"enumParam":"myEnumValue"`

However, with the latest version 4.17.2, the same query shows the following in Fiddler:

`"enumParam":"Microsoft.OData.Core.ODataEnumValue"`

And to get pass this issue, I would have to change my code to pass in the string value directly.

```
var paramDict = new Dictionary<string, object>
                                {
                                    {"stringParam", "myStringParam"
                                    { "enumParam", "myEnumValue"
                                };
```
I think this relates to issue #210 that was fixed which seems to have changed its behaviour. Is this a bug or should I be doing it differently now?

Thanks!

**Comment by object** [comment]
Hm, that's not good, I will look into it. Again, there was a bug related to enum handling, but now you're probably facing a regression. What happens if you specify enum value directly, without using ODataEnumValue. This should be preferred method anyway.

**Comment by mwchan** [comment]
Yup. It works if I specify the enum value directly as stated above.

```
var paramDict = new Dictionary<string, object>
                                {
                                    {"stringParam", "myStringParam"
                                    { "enumParam", "myEnumValue"
                                };
```

I will do that if that is the preferred method. Thanks!
