### ISSUE TITLE
Simple.Odata.Client in UWP

### ISSUE THREAD

**Issue by battermaster** [object/Simple.OData.Client#219]
I try it in winform, It run well.
But when I put the same code in UWP,  it can't get data from server.

what is  the problem?

**Comment by object** [comment]
Can't say anything without looking at your code example. Make sure you are using async/await properly, avoid using "Wait" and "Result" on async methods, it can block the call.

**Comment by battermaster** [comment]
var client = new ODataClient("http://localhost:60698/odata/");
            var response = client.FindEntriesAsync("ExpInfos");
            response.Wait();

I just try the very simple code.

**Comment by object** [comment]
First reaction: don't do response.Wait(). Especially in mobile apps. More about it here for example:

http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by object** [comment]
In other words: you will get the same behavior (blocking) whatever asyn call you use. Try using HttpClient async methods, they will all block in such code. The bottom line: no Wait() or Result on async calls.

**Comment by battermaster** [comment]
ok, thanks, i will try it.
