### ISSUE TITLE
Question: How to map type to pluralized endpoints

### ISSUE THREAD

**Issue by ac4simms** [object/Simple.OData.Client#220]
I have a question similar to #31 in that I have a call that is not being pluralized and I get a 404. Is there a way I can specify pluralization manually on a call?  Currently my call looks like:

```
await this.Client
    .For<LoggerEntry>()
    .Set(new LoggerEntry()
    {
        Title = title,
        Message = message,
    })
    .InsertEntryAsync();
```

The endpoint is named LoggerEntriesController.

I also posted to StackOverflow to see if I can do something different on the api end. http://j.mp/1WCPwCt

**Comment by object** [comment]
Hi,
I proposed a workaround on SO (specifying entity set name explicitly). In addition you can use a method SetPluralizer to specify your own pluralizer that will take control of naming.

**Comment by ac4simms** [comment]
Thanks! I will give that a try.
