### ISSUE TITLE
Calling an Action with POST Content

### ISSUE THREAD

**Issue by cjrosa** [object/Simple.OData.Client#228]
Thank you in advance!

How might I construct the following (from the [CRM Web Api Documentation](https://msdn.microsoft.com/en-us/library/mt607600.aspx#bkmk_boundActions)):

**Note: The GUIDs are different**

`POST [Organization URI]/api/data/v8.0/queues(56ae8258-4878-e511-80d4-00155d2a68d1)/Microsoft.Dynamics.CRM.AddToQueue HTTP/1.1
Accept: application/json
Content-Type: application/json; charset=utf-8
OData-MaxVersion: 4.0
OData-Version: 4.0
{
 "Target": {
  "activityid": "59ae8258-4878-e511-80d4-00155d2a68d1",
  "@odata.type": "Microsoft.Dynamics.CRM.task"
 }
}`

                var target = new Dictionary<string, object>()
                {
                    {
                        "Target", new Dictionary<string,object>()
                        {
                            { Models.EntityBase<T>.Key.Name , entity.Id },
                            { "@odata.type", "Microsoft.Dynamics.CRM." + Models.EntityBase<T>.LogicalName }
                        }
                    }
                };

                var query = service
                    .For<Models.Queue>()
                    .Key(queue.Id)
                    .Action("AddToQueue")
                    .Set(target);

                var cmd = await query.GetCommandTextAsync();

                await query.ExecuteAsync();

This results in a Microsoft.OData.Core.ODataException as follows:

`The property 'activityid' does not exist on type 'Microsoft.Dynamics.CRM.crmbaseentity'. Make sure to only use property names that are defined by the type.`

I have a feeling that the metadata is being honored (to strictly) given the action's metadata is defined as:

**Note: Target's Type of crmbaseentity**

`      <Action Name="AddToQueue" IsBound="true">
        <Parameter Name="entity" Type="mscrm.queue" Nullable="false" />
        <Parameter Name="Target" Type="mscrm.crmbaseentity" Nullable="false" />
        <Parameter Name="SourceQueue" Type="mscrm.queue" />
        <Parameter Name="QueueItemProperties" Type="mscrm.queueitem" />
        <ReturnType Type="mscrm.AddToQueueResponse" Nullable="false" />
      </Action>`

**Comment by object** [comment]
Hi,
There is no "activityId" among AddToQueue parameters, you have to set parameters "entity", "Target", "SourceQueue" and "QueueItemProperties".

**Comment by cjrosa** [comment]
public async System.Threading.Tasks.Task ExecuteAsync()
            {
                var target = new Dictionary<string, object>()
                {
                    {
                        "Target", new Dictionary<string,object>()
                        {
                            { EntityBase<T>.Key.Name , entity.Id },
                            { "@odata.type", "Microsoft.Dynamics.CRM." + EntityBase<T>.LogicalName }
                        }
                    }
                };

                // SODC to Build URL
                var query = service
                    .For<Queue>()
                    .Key(queue.Id)
                    .Action("AddToQueue");

                // FLURL to Send
                var s = await service.Uri.ToString()
                    .AppendPathSegment(await query.GetCommandTextAsync())
                    .WithHeader("Accept", "application/json")
                    .WithOAuthBearerToken(service.Token)
                    .PostJsonAsync(target);

                if (s.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    var r = JsonConvert.DeserializeObject<AddToQueueResponse>(await s.Content.ReadAsStringAsync()); 
                }
            }

**Comment by object** [comment]
This means that in addition to OData protocol your service supports some other methods of posting/querying the data. Since Simple.OData.Client relies on OData metadata, it can't support these types of requests.

**Comment by mkmk89** [comment]
I think it actually might be a bug. 

Here is my example, same problem:
```
Dictionary<string, object> accountRef = new Dictionary<string, object>();
accountRef.Add("accountid", new Guid("B5262003-769C-E711-80F8-C4346BAC4304"));
accountRef.Add("@odata.type", "Microsoft.Dynamics.CRM.account");
Dictionary<string, object> actionSubParameters = new Dictionary<string, object>();
actionSubParameters.Add("listid", new Guid("EDF76AF5-91DF-E311-B8E5-6C3BE5A8B200"));
Dictionary<string, object> actionParameters = new Dictionary<string, object>();
actionParameters.Add("List", actionSubParameters);
actionParameters.Add("Members", new object[] { accountRef });
client2.Unbound().Action("AddListMembersList").Set(actionParameters).ExecuteAsync().Wait();
```
throws:
> ODataException: The property 'accountid' does not exist on type 'Microsoft.Dynamics.CRM.crmbaseentity'. Make sure to only use property names that are defined by the type.

Now why I think it is a bug - that is true, crmbaseentity doesn't contain that property, it doesn't contain any properties in fact. However that is base entity from which account entity inherits, see metadata dump:
```
<EntityType Name="crmbaseentity" Abstract="true" />
...
<EntityType Name="account" BaseType="mscrm.crmbaseentity">
...
```

**Comment by id0001** [comment]
I too have this issue with  0365 Dynamics CRM.

I found that the [SetBusinessSystemUser ](https://msdn.microsoft.com/en-us/library/mt593023.aspx)Action requires a parameter of the type 'crmbaseentity' which is the base class for pretty much every class in the API. 
On further inspection this parameter actually uses the SystemUser type which, when setting '@odata.type' in the parameter also works as intended.
Simple.Odata.Client does not allow this property to be set because it will set it itsself.

A solution would be to allow setting '@odata.type' and let it override the original type.

**Comment by vandsh** [comment]
Love the library but it doesn't play nice with CRM out of box. Found a workaround (albeit, a sledgehammer approach):

```
oDataClientSettings.AfterResponse += delegate (HttpResponseMessage message)
{
    if (message.RequestMessage.RequestUri.OriginalString == $"{apiBase}/$metadata")
    {
        var metadataContent = message.Content.ReadAsStringAsync();
        var metadataDoc = new XmlDocument();
        metadataDoc.LoadXml(metadataContent.Result);
        foreach (XmlNode child in metadataDoc.GetElementsByTagName("EntityType"))
        {
            if (child.Attributes["BaseType"] != null && child.Attributes["BaseType"].Value == "mscrm.crmbaseentity")
            {
                child.Attributes.Remove(child.Attributes["BaseType"]);
                var openTypeAttr =  metadataDoc.CreateAttribute("OpenType");
                openTypeAttr.Value = true.ToString();
                child.Attributes.Append(openTypeAttr);
            }
        }
        message.Content = new StringContent(metadataDoc.OuterXml);
    }
};
```

In short it "transforms" the metadata that's requested and stored in memory, replacing the `BaseType` with an `OpenType=true`. I am sure there will be cases where I regret this approach and ignoring any validation, but time will tell.
