### ISSUE TITLE
Unable to load OData adapter from assembly Simple.OData.Client.V3.Adapter

### ISSUE THREAD

**Issue by spettifer** [object/Simple.OData.Client#229]
Hi

I've seen this issue coming up in this project before and there were different resolutions each time. Neither fills me with confidence, but I really quite like the client otherwise.

We have a simple REST api built using Web API 2.2 which has an OData controller. Querying it with Postman works perfectly. We're trying to query this API from an MVC controller with the following snippet:

    
    [HttpPost]
    public async Task<string>GetData()
    {
        try
        {
            Simple.OData.Client.V4Adapter.Reference();
            var simpleClient = new ODataClient(new Uri("http://localhost/Product-Catalogue/odata/");

            var products = await simpleClient
            .For("ProductCatalogueQuery")
            .FindEntriesAsync() as IEnumerable<dynamic>;

            }
        catch (Exception ex)
        {
            { Console.WriteLine(ex.ToString()); }
            throw;
        }
        //This would theoretically return data to a UI, but we don't get that far so just add 
        //an arbitrary value to satisfy ReSharper.
        return string.Empty;
    }

As you can see we have even tried the solution given to [this issue](https://github.com/object/Simple.OData.Client/issues/53), adapted to V4, but to no avail. We are using the Simple.OData.V4.Client package and Microsoft.Odata.Core and Microsoft.Odata.Edm both at version 6.15.0. We'd really like to use this component but as it stands it's a dead stick. Is it a bug or are we missing some vital configuration? We think we've done everything right but we could have missed something.

Thanks

**Comment by spettifer** [comment]
Just switched to using the full-fat Simple.OData.Client and the problem goes away - looks like the V4 only library (which we would prefer for it's smaller footprint) is busted somehow.

**Comment by object** [comment]
Thanks for the issue report. This looks quite strange, I will investigate it.

**Comment by object** [comment]
BTW, you called the issue "Unable to load OData adapter from assembly Simple.OData.Client.V3.Adapter", you meant V4.Adapter, did you?

**Comment by spettifer** [comment]
No, that's what puzzled us so much: We were using the V4 library quite specifically, but it was saying it couldn't find V3 which had us completely confused. Really odd.

**Comment by object** [comment]
This is what puzzles me too. Unless the error message is wrong.

**Comment by object** [comment]
I have just pushed version 4.19.0 and tested all its 3 packages. Should work fine, please check it out.
