### ISSUE TITLE
Unable to convert value of type System.String to OData type [Edm.Guid Nullable=True]

### ISSUE THREAD

**Issue by ashuthinks** [object/Simple.OData.Client#230]
Hi,

My User class is like below when I try to update record using below query it gives me exception.

 public class User
    {
        public User();

        public Guid Id { get; set; }
        public virtual Language Language { get; set; }
        public Guid? LanguageId { get; set; }
        public virtual City City { get; set; }
        public Guid? CityId { get; set; }
    }

     var city = userData.FirstOrDefault();
                Guid cityId = city.Id;
     await myClient.For< User >()
                                                                .Filter(t=>t.CityId == cityId)
                                                                .Set(new { LanguageId = languageId  })
                                                                .UpdateEntryAsync();

**Comment by object** [comment]
Hi,
Impossible to say anything without knowing your service metadata and what kind of exception you are getting.

**Comment by object** [comment]
Fixed, will be released in 4.20.
