### ISSUE TITLE
Search() missing in nuget binaries

### ISSUE THREAD

**Issue by zivillian** [object/Simple.OData.Client#232]
The following methods are missing in the binaries distributed via nuget:

[FluentClientBase.Search(string search)](https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Core/Fluent/FluentClientBase.cs#L133)
[IFluentClient.Search(string search)](https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Core/Fluent/IFluentClient.cs#L97)

As a workaround I have to cast the client returned by ODataClient.For<T>() from IBoundClient<T> to BoundClient<T> to use the [search](https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Core/Fluent/FluentClientBase.cs#L133) functionality.

**Comment by object** [comment]
This is correct, Search is defined right on BoundClient (which is a problem of course), I will look into it.

**Comment by object** [comment]
Search is something that is a part of version 5 (where it is defiend on IFluentClient interface). The implementation is ported back to v4 but interface has not been updated. Since this is just a new method it should be safe to add it, I will do it for v 4.19.

**Comment by object** [comment]
Fixed in 4.19.
