### ISSUE TITLE
Delete returns 204 with content

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#235]
I've noticed that Delete is returning a 204 with content, which is a protocol violation...

HTTP/1.1 204 No Content
Content-Length: 110
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8
Server: Microsoft-IIS/8.5
DataServiceVersion: 3.0
Date: Mon, 18 Apr 2016 22:26:30 GMT

{
  "odata.metadata":"https://myservice/api/odata/v3/$metadata#Edm.String","value":"Deleted"
}

I then get an exception on the next call to the OData client.

**Comment by object** [comment]
Thanks for the observation, working on it.

**Comment by object** [comment]
I may need more information about what kind of exception you get. The protocol violation (204 with content) comes from the server but why SOD raises exception on the next call is rather strange. So if you have more data to share, please do.

**Comment by phatcher** [comment]
Here's a debug trace of what happens from a unit test that creates, then deletes an entity..

    2016/04/23 10:33:14:179 [DEBUG] Client.SensorsClient - Coating
    2016/04/23 10:33:14:187 [DEBUG] Client.SensorsClient - POST request: https://service.com/api/odata/v3/Coating
    2016/04/23 10:33:14:243 [DEBUG] Client.SensorsClient - Request completed: Created
    2016/04/23 10:33:14:248 [DEBUG] Client.SensorsClient - Coating: Id=1183
    2016/04/23 10:33:14:262 [DEBUG] Client.SensorsClient - DELETE request: https://service.com/api/odata/v3/Coating(1183)
    2016/04/23 10:33:14:289 [DEBUG] Client.SensorsClient - Request completed: NoContent
    2016/04/23 10:33:14:290 [DEBUG] Client.SensorsClient - Coating: Id:1183
    2016/04/23 10:33:14:294 [DEBUG] Client.SensorsClient - GET request: https://service.com/api/odata/v3/Coating(1183)
    2016/04/23 10:33:14:325 [ERROR] Client.SensorsClient - Coating: Id:1183 - An error occurred while sending the request.
    2016/04/23 10:33:14:327 [ERROR] Client.SensorsClient - System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
        at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
        at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
        --- End of inner exception stack trace ---
        at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
        at Simple.OData.Client.FluentClientBase`1.<RectifyColumnSelectionAsync>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        at Client.SensorsClient.<FindAsync>d__25`1.MoveNext() in C:\Devel\SensorsClient.cs:line 157

SensorsClient is a wrapper around IODataClient...

        public async Task<T> FindAsync<T>(object id)
            where T : class
        {
            try
            {
                if (Logger.IsDebugEnabled)
                {
                    Logger.DebugFormat("{0}: Id:{1}", typeof (T).Name, id);
                }
                return await For<T>()
                    .Key(id)
                    .FindEntryAsync();
            }
            catch (Exception ex)
            {
                Logger.ErrorFormat("{0}: Id:{1} - {2}", typeof(T).Name, id, ex.Message);
                Logger.Error(ex);
                throw;
            }
        }

**Comment by object** [comment]
And this happens only if you first call Delete (and server violates the protocol by returning content)? So the exception is not raised in Delete but on a next call? I am suspecting that there is a pending content after Delete that triggers the exception in ODataLib.

**Comment by object** [comment]
Hmm, not sure what to do about it. See a similar issue: http://stackoverflow.com/questions/18496451/c-httpclient-the-server-committed-a-protocol-violation-section-responsestatu

The core problem is on the server side. For libraries using WebRequest it is possible to set a flag in app.config (useUnsafeHeaderParsing) but HttpClient doesn't support that. Right now I can't think of a resolution that will not affect performance (trying to read response even though server returned 204 is out of the question).

I can only think about some workaround on the client side: knowing that it's dealing with bad server and guard DELETE request with some dummy GET that will swallow exception.

**Comment by phatcher** [comment]
That's what I've done - I'll also report it as a bug against OData 3....

        public async Task DeleteAsync<T>(object id)
            where T : class
        {
            try
            {
                if (Logger.IsDebugEnabled)
                {
                    Logger.DebugFormat("{0}: Id={1}", typeof(T).Name, id);
                }

                await For<T>()
                    .Key(id)
                    .DeleteEntryAsync();

                try
                {
                    await FindAsync<T>(id);
                }
                catch (HttpRequestException re)
                {
                    // Swallow
                    var inner = re.InnerException;
                }
            }
            catch (Exception ex)
            {
                Logger.ErrorFormat("{0}: Id={1} - {2}", typeof(T).Name, id, ex.Message);
                Logger.Error(ex);
                throw;
            }
        }
