### ISSUE TITLE
Nullable enums

### ISSUE THREAD

**Issue by ChristofferBergkvist** [object/Simple.OData.Client#236]
Exception when downloading one or many entities that contains nullable enums.

Ok if all of those rows are set to null. Exception occurs if any of them has a value other then null.

**Exception**
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Nullable`1[TEMCommon.Enums.Units]'.

**Entity**
EntityType Name="Set">
Key>
PropertyRef Name="GUID"/>
Key>
...
Property Name="QualityUnit" Type="TEMCommon.Enums.Units"/>
...
/EntityType>

**Nullable enum**
EnumType Name="Units" UnderlyingType="Edm.Byte">
Member Name="Position" Value="0"/>Member Name="Speed" Value="1"/>
Member Name="Acceleration" Value="2"/>
Member Name="Force" Value="3"/>
Member Name="Power" Value="4"/>
Member Name="Time" Value="5"/>
/EnumType>

**Comment by object** [comment]
Thank you for the issue report. It's fixed now and will be released as a part of version 4.20.

**Comment by object** [comment]
Fixed in 4.20.
