### ISSUE TITLE
Function <name> not found

### ISSUE THREAD

**Issue by jeevsure724** [object/Simple.OData.Client#237]
I am trying to call an SAP odata function using V3 .net adaptor but keep getting function not found.

i am using this call;

 var input = new BITAL()
            {
                Prop1= "Test",
                BITTOALLOC = new List<ALLOC>()
                 {
                    new ALLOC()
                    {
                        Prop1= "Test",
                        Prop2 = "Test1" ,
                        Prop3 = string.Empty,
                        Messagetype = string.Empty,
                        Message = string.Empty
                    }       ,
                      new ALLOC()
                    {
                        Prop1= "Test2",
                        Prop2 = "Test12" ,
                        Prop3 = string.Empty,
                        Messagetype = string.Empty,
                        Message = string.Empty
                    }
                }
            };
var result = await client.For<BITAL>().
                    Function("FUNCTION_NAME_ENTITY").
                    Set(input).
                    ExecuteAsSingleAsync();

I need to do a POST call to the service.

**Comment by object** [comment]
Hi,
How does your service metadata look like?

**Comment by jeevsure724** [comment]
Hello Vagif,

Thanks for your reply.

The metadata only contains the entity types, associations and entity sets. I am making a function call against a specific entity type.

**Comment by object** [comment]
Thanks, but still, since the library obviously doesn't find something I would like to have a look at the metadata document to be able to reproduce the problem. If you have a possibility to share the access to your service, it will be even better.

**Comment by jeevsure724** [comment]
I have sent it to you over your email. Kindly check and please let me know if I am missing something.

Thanks again.

**Comment by object** [comment]
I replied to your mail. The metadata doesn't have any function defined, there must be some misunderstanding.

**Comment by object** [comment]
Simple.OData.Client relies on OData protocol, in particular on its metadata, how else otherwise can it match .NET types and properties to elements of HTTP URIs and POST payloads? OData uses HTTP protocol underneath but not every HTTP request is an OData request. It looks like in addition to OData protocol your service supports some extensions that (unfortunately) are not mapped to OData resources, functions and actions. If so, I am afraid you are out of like with Simple.OData.Client and have to handle these extended operations using HttpClient.

**Comment by jeevsure724** [comment]
Thanks a bunch for clarifying this for me.

**Comment by bdjema** [comment]
Hi, I havethe same issued.
From POSTMAN working, but not working from Simple Client Odata.

**Server Code** 
Config:
`
            builder.EntitySet<Product>("Products");

            //builder.Namespace = "DemoOdataAPI";
            builder
                .Entity<Product>().Collection
                .Action("FindByName")
                .ReturnsCollectionFromEntitySet<Product>("Products")
                .Parameter<string>("name");`
controllers:
`  [HttpPost]
        public  IQueryable<Product> FindByName([FromODataUri] string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var models = db.Products.Where(x => x.Name.Contains(name));
                return models;
            }
            else
            {
                var models = db.Products;
                return models;
            }
        }`


**Simple Client Odata:**
` var results = await client
                    .For<Product>("Products")
                            //.Function("FindByName")
                            .Action("FindByName")
                            .Set(new Dictionary<string, object>() { { "name", "Something" } })
                            .ExecuteAsArrayAsync<Product>();
                    var person = await client.For<Product>("Products").FindEntriesAsync();`

The Metadata:
`<edmx:Edmx Version="1.0"><edmx:DataServices m:DataServiceVersion="3.0" m:MaxDataServiceVersion="3.0"><Schema Namespace="DemoOdataAPI.Models"><EntityType Name="Product"><Key><PropertyRef Name="Id"/></Key><Property Name="Id" Type="Edm.Int32" Nullable="false"/><Property Name="Name" Type="Edm.String"/><Property Name="Description" Type="Edm.String"/><Property Name="Price" Type="Edm.Decimal" Nullable="false"/></EntityType></Schema><Schema Namespace="Default"><EntityContainer Name="Container" m:IsDefaultEntityContainer="true"><EntitySet Name="Products" EntityType="DemoOdataAPI.Models.Product"/><FunctionImport Name="FindByName" ReturnType="Collection(DemoOdataAPI.Models.Product)" IsBindable="true" EntitySet="Products" m:IsAlwaysBindable="true"><Parameter Name="bindingParameter" Type="Collection(DemoOdataAPI.Models.Product)" Nullable="false"/><Parameter Name="name" Type="Edm.String" FixedLength="false" Unicode="false"/></FunctionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>`


Whats wrong with my code?
Thanks and Regards,
