### ISSUE TITLE
How to enable gzip compression?

### ISSUE THREAD

**Issue by Rydra** [object/Simple.OData.Client#238]
I've noticed that whenever I execute any request, the simple odata client receives all the data non-compressed. If I have to retrieve a huge amount of entities, the size I have to download scales up very quickly.

Is there any easy way to enable gzip compression and decompression in simple odata client?

Thank you.

**Comment by object** [comment]
Hi,
I didn't try this but can't you set ODataClientSettings.OnApplyClientHandler and set AutomaticDecompression flag, i.e. DecompressionMethods.Deflate | DecompressionMethods.GZip?

**Comment by Rydra** [comment]
Hi,

thanks object, your suggestion worked perfectly! Yet I have another related question. It seems that the first time I do a query, it first retrieves and caches the $metadata. My metadata has around 4MB of data, and while the actual query is sent compressed, the metadata is not.

Any suggestion on that regard?

Thank you for your assistance!

**Comment by object** [comment]
You can use MetadataDocument property for the ODataClientSettings to point to a local file. Then it will the file instead of requesting it from the server.

**Comment by Rydra** [comment]
Assigning metadata really sped up the process, so thanks for the tip!

I'm having another issue, but that may be fit for another post.

**Comment by pedromgm** [comment]
Hello,

I try assigning metadata, but i haver a erro "leve 1 xml invalid", can you help me?

Thanks.

**Comment by Rydra** [comment]
Hi pedromgm,

If you do not provide any metadata, upon the first request that property is autofilled. What I did is to extract the contents of that property on a separate file, load that file and assign the metadataDocument property.

I hope it helps.

**Comment by phatcher** [comment]
Could you share the code for this please

**Comment by Rydra** [comment]
Of course,

```
settings.OnApplyClientHandler = handler =>
            {
                handler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
            };
```

**Comment by sbpatil1975** [comment]
I have assigned to MetadataDocument property as below but it's shows error as 'Data at the root level is invalid. Line 1, position 1.'

var clientSettings = new ODataClientSettings();
clientSettings.MetadataDocument = "C:\\MetaData\\metadata.xml";

Please advice

**Comment by sixlettervariables** [comment]
@sbpatil1975 please open a new issue as your problem has nothing to do with this issue.

**Comment by kingcomxu** [comment]
in batch mode, Deflate or GZip reponse throw exception
