### ISSUE TITLE
Bound function - UnresolvableObjectException: Function [GetRowVersionSum] not found

### ISSUE THREAD

**Issue by ChristofferBergkvist** [object/Simple.OData.Client#241]
Exception when trying to execute a bound function:
long data = await context.For&lt;ExerciseType&gt;.Function("GetRowVersionSum").ExecuteAsScalarAsync&lt;long&gt;();

Is there a bug in Simple.OData or am I just doing something wrong?

This works via browser:
http://localhost:58206/ExerciseTypes/Default.GetRowVersionSum

Unbound functions works however:
bool b = await context.Unbound().Function("IsOnline").ExecuteAsScalarAsync&lt;bool&gt;();

**Metadata bound function**
&lt;Function Name="GetRowVersionSum" IsBound="true">
&lt;Parameter Name="bindingParameter" Type="Collection(TEMCommon.Database.ExerciseType)"/>
&lt;ReturnType Nullable="false" Type="Edm.Int64"/>
&lt;/Function>

**Metadata unbound function**
&lt;Function Name="IsOnline">
ReturnType Nullable="false" Type="Edm.Boolean"/>
&lt;/Function>

**WebApiConfig:**
builder.EntityType<ExerciseType>().Collection.Function("GetRowVersionSum").Returns<long>();
builder.Function("IsOnline").Returns<bool>();

**ExerciseTypesController**
[HttpGet]
[EnableQuery]
public IHttpActionResult GetRowVersionSum()
{
      var sum = db.ExerciseTypes.Sum(x => x.RowVersion);
      return Ok(sum);
}

**Comment by object** [comment]
Thank you, I will investigate.

**Comment by object** [comment]
How does metadata for ExerciseType look like?

**Comment by ChristofferBergkvist** [comment]
Well this is embarrassing, I targeted the wrong uri in my client!

The code works!

However, issue 239 (chaining multiple .Filter(...)) does not work still.
