### ISSUE TITLE
Is Simple OData Client thread safe?

### ISSUE THREAD

**Issue by vojtechvit** [object/Simple.OData.Client#242]
Hi, we're developing a client proxy library for our API with the use of Simple OData Client. This library will probably be used as singleton across threads. My question therefore is - is Simple OData Client thread safe?

The critical parts could be the creation and use of HttpClient (which is thread safe, but it depends on the use of it) and getting service metadata from an endpoint.

**Comment by object** [comment]
Hi, I believe is should be safe to use. The only thing that will require synchronization is its metadata cache which is using ConcurrentDictionary in .NET4.0 DLL and custom SimpleDictionary in PCL. And both dictionary classes are thread safe.

**Comment by vojtechvit** [comment]
Ok, thanks for swift answer! ;)
