### ISSUE TITLE
Odata with Entity Framework and navigation properties

### ISSUE THREAD

**Issue by ChristofferBergkvist** [object/Simple.OData.Client#244]
Hi

I'm using Simple.Odata together with Entity framework code-first. I use EF on server to communicate with SQL database and odata on client side which is written in c#. I use exactly the same model classes on both sides. Example model classes below:

```
public class Parent
{
    public Parent()
    {
        Children = new HashSet<Child>();
    }

    [Key]
    Guid GUID { get; set; }

        public string Name { get; set; }

    public virtual ICollection<Child> Children { get; set; }
}

public class Child
{
    [Key]
    Guid GUID { get; set; }

        public string Name { get; set; }

    public Guid ParentGUID { get; set; }

    public Parent Parent { get; set; }
}
```

Everything works (querying, adding, updating etc) but I have a very annoying problem that occurs with updates. I does not matter if I use PUT or PATCH.

When I try to update a child record using this line of code from client side:
`Child child = await client.For("Child").Key(myGUID).Set(myChild).UpdateEntryAsync();`

This line of code is run on server side in ODataController:
`return Updated(child);` 

The update works but the following output is printed in debug console on server:
Exception thrown: 'System.Web.Http.HttpResponseException' in System.Web.OData.dll

Also on client side:
Exception thrown: 'Simple.OData.Client.WebRequestException' in mscorlib.dll

Only way to make it dissaper is to mark Parent in Child as [NotMapped]
`[NotMapped]`
`public Parent Parent { get; set; }`

This however removed navigation property Parent from Child in metadata which I don't want.

So my question, is I doing something wrong? What is the correct way of creating POCO classes with one-to-many relations?

**Comment by object** [comment]
Hi,
Your entity classes look good and from your description I don't know what's causing the problem. Are you sure the error isn't server side? Judging from the exception type ( 'System.Web.Http.HttpResponseException' in System.Web.OData.dll) it looks like it's the server and I'd investigate it first.
