### ISSUE TITLE
Why is Prefer=return-no-content?

### ISSUE THREAD

**Issue by scastria** [object/Simple.OData.Client#245]
I am very new to OData.  I am using the v3 nuget package and am trying to read all entries like this:

			try {
				ODataClientSettings odataSettings = new ODataClientSettings("https://test.fielddirect.com/DataServices/OData/") {
					PayloadFormat = ODataPayloadFormat.Atom
				};
				odataSettings.BeforeRequest += delegate (HttpRequestMessage message) {
					message.Headers.Authorization = new AuthenticationHeaderValue("Basic", App.CurrentUser.Token.ToString());
					message.Headers.Remove("Prefer");
					Console.WriteLine(message);
				};
				odataSettings.AfterResponse += delegate (HttpResponseMessage message) {
				};
				ODataClient client = new ODataClient(odataSettings);
				IEnumerable<sumDailyProduction> results = await client.For<sumDailyProduction>().Top(50).FindEntriesAsync();
				foreach (sumDailyProduction prod in results) {
				}
			} catch (Exception e) {
			}

I have a few issues.  First, my OData service uses tokens for basic authentication.  I could not find a way to submit a token using the ICredentials interface so I had to do a BeforeRequest.  Is that the right way?

Second, more important, is when I am trying to call FindEntriesAsync, simple odata client is putting a Prefer=return-no-content header so I get 0 results back.  I had to remove the Prefer header manually.  Am I doing something wrong?

**Comment by object** [comment]
1. ODataClientSettings has Credentials  property. Can you use that?
2. I confirmed that in some scenarious "Prefer" is incorrectly set. I will make a fix, thanks for reporting it.

**Comment by scastria** [comment]
I can't use the credentials for 2 reasons:
1. searching the source code, I can only see one place where the credentials are actually used and I think it was in something related to web API. if debug my app that provides credentials, it NEVER uses them and never hits the breakpoint in the code that actually uses them. 
2. my Odata service uses an external service to perform login which gives me a token (Guid). I then must add that token to the Odata headers with the Authorization:Basic <token> format. since ICredentials is based on username/password, I can't use it. I need something more general like an IAuthorization interface where I can specify whatever I want to be added to the headers as Authorization:XXXXXXXXX

**Comment by object** [comment]
I see. I need to figure out how this can be solved.

**Comment by object** [comment]
But actually I don't see any better way than assigning AuthenticationHeaderValue in BeforeRequest. Anything else will be just syntactic sugar that will do the same. So yes you are doing it right.

And of course I will fix the other issue ("Prefer").

**Comment by object** [comment]
Fixed in 4.20.
