### ISSUE TITLE
ODataClientSettings.PreferredUpdateMethod  not working as expected

### ISSUE THREAD

**Issue by ykeysergit** [object/Simple.OData.Client#257]
Despite using Set to update all the fields, BoundClient still sends HTTP Patch. Why is the PreferredUpdateMethod not taking precedence??

**Comment by object** [comment]
Hi,
PreferredUpdateMethod only hints the library what verb to use, in some scenarios it's not possible to use PUT over PATCH or vice versa. If you give me a code example plus extract from your schema I can look into it.

**Comment by ykeysergit** [comment]
Could you please change it to so that it takes precedence, or add a setting to take precedence? It would really help to take advantage of PUT/PATCH explicitly!  Schema and code snippets below...


fixture.getClient().ForPeople().Key("SLane").Set(new Person{ FirstName = "Agent", LastName = "Smith", UserName="SLane" }).UpdateEntryAsync().Result


<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="MockODataService.Models">
<EntityType Name="Person">
<Key>
<PropertyRef Name="UserName"/>
</Key>
<Property Name="UserName" Type="Edm.String" Nullable="false"/>
<Property Name="FirstName" Type="Edm.String"/>
<Property Name="LastName" Type="Edm.String"/>
</EntityType>
</Schema>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Default">
<EntityContainer Name="Container">
<EntitySet Name="People" EntityType="MockODataService.Models.Person"/>
</EntityContainer>
</Schema>
</edmx:DataServices>
</edmx:Edmx>

**Comment by object** [comment]
This is quite strange. Since the entity key is not updated it should respect the value of PreferredUpdateMethod according to the code in https://github.com/object/Simple.OData.Client/blob/v4/Simple.OData.Client.Core/Adapter/RequestWriterBase.cs.

I can investigate it further but it may take some time (have a large pile of issues). In the meantime if you have a possibility to debug the project, it can speed the things up.

**Comment by ykeysergit** [comment]
I found a bug in my code where I clone the settings and missed the PreferredUpdateMethod. Let me verify again and get back to you.

**Comment by ykeysergit** [comment]
After I fixed clone, now it does Put! Sorry for the inconvenience. Thanks for confirming it should be working!

**Comment by object** [comment]
No problem! Glad the issue is solved.
