### ISSUE TITLE
Return value of function not assigned correctly - null returned

### ISSUE THREAD

**Issue by monczszilard** [object/Simple.OData.Client#259]
I have a schema as:
 `<edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:sap="http://www.sap.com/Protocols/SAPData" Version="1.0">
<edmx:DataServices m:DataServiceVersion="2.0">
<Schema xmlns="http://schemas.microsoft.com/ado/2008/09/edm" Namespace="/ECC_BP_IF_SRV" xml:lang="en" sap:schema-version="1">
<EntityType Name="Resource" sap:content-version="1">
<Key>
<PropertyRef Name="ResourceId"/>
</Key>
<Property Name="ResourceId" Type="Edm.String" Nullable="false" MaxLength="8" sap:label="Work center" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Name" Type="Edm.String" Nullable="false" MaxLength="8" sap:label="Work center" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Description" Type="Edm.String" Nullable="false" MaxLength="20" sap:label="Name" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="ParentId" Type="Edm.String" Nullable="false" MaxLength="8" sap:label="Object ID" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Istrimpossible" Type="Edm.String" Nullable="false" MaxLength="1" sap:label="Single-Character Indicator" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Type" Type="Edm.String" Nullable="false" MaxLength="30" sap:label="30 Characters" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Productionrate" Type="Edm.String" Nullable="false" MaxLength="8" sap:label="Production Rate" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Site" Type="Edm.String" Nullable="false" MaxLength="4" sap:label="Plant" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Quantityunit" Type="Edm.String" Nullable="false" MaxLength="5" sap:label="R/2 table" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Slotbufferpercent" Type="Edm.Decimal" Nullable="false" Precision="5" Scale="4" sap:label="DEC1_4" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Slotbufferminamount" Type="Edm.Decimal" Nullable="false" Precision="7" Scale="2" sap:label="Dummy Dec07" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<Property Name="Slotbuffermaxamount" Type="Edm.Decimal" Nullable="false" Precision="7" Scale="2" sap:label="Dummy Dec07" sap:creatable="false" sap:updatable="false" sap:sortable="false" sap:filterable="false"/>
<NavigationProperty Name="ToProducts" Relationship="/ECC_BP_IF_SRV.ResourceProductAssociation" FromRole="FromRole_ResourceProductAssociation" ToRole="ToRole_ResourceProductAssociation"/>
<NavigationProperty Name="ToSlots" Relationship="/ECC_BP_IF_SRV.ResourceSlotAssociation" FromRole="FromRole_ResourceSlotAssociation" ToRole="ToRole_ResourceSlotAssociation"/>
</EntityType>
<Association Name="ResourceProductAssociation" sap:content-version="1">
<End Type="/ECC_BP_IF_SRV.Resource" Multiplicity="0..1" Role="FromRole_ResourceProductAssociation"/>
<End Type="/ECC_BP_IF_SRV.Product" Multiplicity="*" Role="ToRole_ResourceProductAssociation"/>
<ReferentialConstraint>
<Principal Role="FromRole_ResourceProductAssociation">
<PropertyRef Name="ResourceId"/>
</Principal>
<Dependent Role="ToRole_ResourceProductAssociation">
<PropertyRef Name="ResourceId"/>
</Dependent>
</ReferentialConstraint>
</Association>
<Association Name="ResourceSlotAssociation" sap:content-version="1">
<End Type="/ECC_BP_IF_SRV.Resource" Multiplicity="1" Role="FromRole_ResourceSlotAssociation"/>
<End Type="/ECC_BP_IF_SRV.Slot" Multiplicity="*" Role="ToRole_ResourceSlotAssociation"/>
<ReferentialConstraint>
<Principal Role="FromRole_ResourceSlotAssociation">
<PropertyRef Name="ResourceId"/>
</Principal>
<Dependent Role="ToRole_ResourceSlotAssociation">
<PropertyRef Name="ResourceId"/>
</Dependent>
</ReferentialConstraint>
</Association>
<EntityContainer Name="/ECC_BP_IF_SRV_Entities" m:IsDefaultEntityContainer="true" sap:supported-formats="atom json xlsx">
<EntitySet Name="Slots" EntityType="/ECC_BP_IF_SRV.Slot" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:pageable="false" sap:content-version="1"/>
<EntitySet Name="Products" EntityType="/ECC_BP_IF_SRV.Product" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:pageable="false" sap:content-version="1"/>
<EntitySet Name="Resources" EntityType="/ECC_BP_IF_SRV.Resource" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:pageable="false" sap:addressable="false" sap:content-version="1"/>
<AssociationSet Name="ResourceProductAssociationSet" Association="/ECC_BP_IF_SRV.ResourceProductAssociation" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:content-version="1">
<End EntitySet="Resources" Role="FromRole_ResourceProductAssociation"/>
<End EntitySet="Products" Role="ToRole_ResourceProductAssociation"/>
</AssociationSet>
<AssociationSet Name="ProductSlotAssociation_AssocSet" Association="/ECC_BP_IF_SRV.ProductSlotAssociation" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:content-version="1">
<End EntitySet="Products" Role="FromRole_ProductSlotAssociation"/>
<End EntitySet="Slots" Role="ToRole_ProductSlotAssociation"/>
</AssociationSet>
<AssociationSet Name="ResourceSlotAssociation_AssocSet" Association="/ECC_BP_IF_SRV.ResourceSlotAssociation" sap:creatable="false" sap:updatable="false" sap:deletable="false" sap:content-version="1">
<End EntitySet="Resources" Role="FromRole_ResourceSlotAssociation"/>
<End EntitySet="Slots" Role="ToRole_ResourceSlotAssociation"/>
</AssociationSet>
<FunctionImport Name="LockEntries" ReturnType="/ECC_BP_IF_SRV.Resource" EntitySet="Resources" m:HttpMethod="POST" sap:action-for="/ECC_BP_IF_SRV.Resource">
<Parameter Name="Site" Type="Edm.String" Mode="In" MaxLength="4"/>
<Parameter Name="ResourceId" Type="Edm.String" Mode="In" MaxLength="8"/>
</FunctionImport>
<FunctionImport Name="UnLockEntries" ReturnType="/ECC_BP_IF_SRV.Resource" EntitySet="Resources" m:HttpMethod="POST" sap:action-for="/ECC_BP_IF_SRV.Resource">
<Parameter Name="Site" Type="Edm.String" Mode="In" MaxLength="4"/>
<Parameter Name="ResourceId" Type="Edm.String" Mode="In" MaxLength="8"/>
</FunctionImport>
</EntityContainer>
<atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="self" href="http://localhost/ECC_BP_IF_SRV/$metadata"/>
<atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="latest-version" href="http://localhost/ECC_BP_IF_SRV/$metadata"/>
</Schema>
</edmx:DataServices>
</edmx:Edmx>`

I calling a function:
`            var res = await client
                .Unbound()
                .Function("LockEntries")
                .Set(new Entry() { { "Site", "M110" }, { "ResourceId", "10000223" } })
                .ExecuteAsScalarAsync<Resource>();`

res is null, but the call is successful, I get the following response:
Is there a way how to store the function result in a dynamic variable?

`<?xml version="1.0" encoding="utf-8"?><entry xml:base="http://localhost/ECC_BP_IF_SRV/" xmlns="http://www.w3.org/2005/Atom" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"><id>http://localhost/ECC_BP_IF_SRV/Resources('10000223')</id><title type="text">Resources('10000223')</title><updated>2016-06-09T21:36:34Z</updated><category term="/TIETO/ECC_BP_IF_SRV.Resource" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/><link href="Resources('10000223')" rel="self" title="Resource"/><link href="Resources('10000223')/ToProducts" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ToProducts" type="application/atom+xml;type=feed" title="ToProducts"/><link href="Resources('10000223')/ToSlots" rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/ToSlots" type="application/atom+xml;type=feed" title="ToSlots"/><content type="application/xml"><m:properties><d:ResourceId>10000223</d:ResourceId><d:Name>MP_PM1</d:Name><d:Description>Machine 1</d:Description><d:ParentId>00000000</d:ParentId><d:Istrimpossible>0</d:Istrimpossible><d:Type>MACHINE</d:Type><d:Productionrate>      0</d:Productionrate><d:Site>M110</d:Site><d:Quantityunit>KG</d:Quantityunit><d:Slotbufferpercent>0.0000</d:Slotbufferpercent><d:Slotbufferminamount>0.00</d:Slotbufferminamount><d:Slotbuffermaxamount>0.00</d:Slotbuffermaxamount></m:properties></content></entry>
`

**Comment by object** [comment]
Hi, ExecuteAsScalar assumes the result will be a primitive scalar value. I suggest you try ExecuteAsSingleAsync. Here are some examples:

https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Tests.Net40/FunctionTests.cs

**Comment by monczszilard** [comment]
Hi,
I tried ExecuteAsSingleAsync too. The result is exactly the same.

**Comment by monczszilard** [comment]
My code is:
`            var res = await client
                .Unbound<Resource>()
                .Function("LockEntries")
                .Set(new Entry() { { "Site", "M110" }, { "ResourceId", "10000223" } })
                .ExecuteAsSingleAsync();`

**Comment by monczszilard** [comment]
I compared the result with the sample from http://services.odata.org/V2/(S(ozmcrxwvdfo5kkcfbmdkre0h))/OData/OData.svc/GetProductsByRating?rating=4
and found some differences:
in my response there is no feed tag and the id refers to the result entity where in the sample it is the function. May be this the problem?

**Comment by object** [comment]
Might be, can't say for sure. But there seems to be a difference between official samples and how your service returns the data. I will investigate if this is allowed deviation.

**Comment by monczszilard** [comment]
I finally was able debug the library and check the problem. It is simple - the function call is done using the POST method and this causes request.ResultRequired = false.
I assume the function always returns a aresult so adding request.ResultRequired = true; into CreateFunctionRequestAsync fixes this problem.

**Comment by monczszilard** [comment]
Please fix this issue, the reproduction case is easy: Function called as POST does not return a value.

**Comment by object** [comment]
Sorry for the delay, this is my after-hours project, have to take it in between other stuff. I will get back to you soon.

**Comment by object** [comment]
Fixed, will be soon released as a new NuGet pack.
