### ISSUE TITLE
Is there handling for OData error response?

### ISSUE THREAD

**Issue by monczszilard** [object/Simple.OData.Client#261]
Is there any support to handle the standard OData error messages?
Could you provide some sample code or documentation or workaround?

`<?xml version="1.0" encoding="utf-8"?>
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
  <code>/IWBEP/MC_SB_DPC_USR/003
  </code>
  <message xml:lang="en">User defined error message there...
  </message>
  <innererror>
    <application>
      <component_id>CA
      </component_id>
      <service_namespace>/MYNAMESPACE/
      </service_namespace>
      <service_id>ECC_BP_IF_SRV
      </service_id>
      <service_version>0001
      </service_version>
    </application>
    <transactionid>575EC51B0E161F3AE10000000AFE6443
    </transactionid>
    <timestamp>20160613212925.4381760
    </timestamp>
    <Error_Resolution>
      <SAP_Transaction>Run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details
      </SAP_Transaction>
      <SAP_Note>See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
      </SAP_Note>
    </Error_Resolution>
    <errordetails>
      <errordetail>
        <code>/IWBEP/CX_SD_GEN_DPC_BUSINS
        </code>
        <message>User defined error details there...
        </message>
        <propertyref/>
        <severity>error
        </severity>
        <target/>
      </errordetail>
    </errordetails>
  </innererror>
</error>`

**Comment by object** [comment]
Hi,
Currently all errors are wrapped into WebRequestException object that contains the actual response data, so you should be able to extract it from there. There is no explicit support for OData error XML.
