### ISSUE TITLE
Unable to add filter

### ISSUE THREAD

**Issue by kvde** [object/Simple.OData.Client#262]
I want to add a simple filter. When I add the filter I get the following error:

Exception: Microsoft.Data.OData.ODataException
Message: The type '' is not supported when converting to a URI literal.

My code is:
 var premise =
                await
                client.Container.For<Contract>()
                    .Key(contractId)
                    .NavigateTo<Premise>()
                    .Filter(p => p.Company == this.Company)
                    .FindEntryAsync();

When I remove the filter it is working.
I have looked at the examples and I don't see what I'm doing wrong.

**Comment by object** [comment]
Can you try assigning this.Company to a local variable "companyName" prior this statement, to the filter expression will look like "p => p.Company == companyName". I suspect the error might have something to do with "this" qualifier.

**Comment by kvde** [comment]
Yes that was the problem! It works now!
I do have one question. Why don't you support the following? Is that incorrect OData?

 ```
await client.Container.For<Account>()
                            .Key(accountID)
                            .Filter(p => p.Company == "contoso")
                            .FindEntryAsync();
```

The following error is thrown: 

```
if (command.HasKey && command.HasFilter)
                throw new InvalidOperationException("OData filter and key may not be combined.");
```

**Comment by object** [comment]
I will fix handling of "this.", it should be possible to use it in the expression.

Regarding your other question. OData protocol defines different URI for key-based and filter-based queries, and they can not be combined. By definition key based lookup is the one that results in 0 or 1 result, so if you want to run a non-key based request you should rewrite your call to only use Filter.

**Comment by kvde** [comment]
Ok thanks!

**Comment by object** [comment]
"this" qualifier is fixed. Will be released in a few days.
