### ISSUE TITLE
Filtering using Lambda expressions not adding grouping parenthesis

### ISSUE THREAD

**Issue by roly445** [object/Simple.OData.Client#264]
I have create a query using a lambda expression like this one
`query.Filter((x => x.WhenFrom >= from && x.WhenFrom <= to) || r(x => x.WhenTo >= from && x.WhenTo <= to))
`
when I use the `GetCommandTextAsync` method, I get the following (I have decoded the url)
`$filter=WhenFrom ge datetime'2016-06-10T00:00:00' and WhenFrom le datetime'2016-06-17T00:00:00' or WhenTo ge datetime'2016-06-10T00:00:00' and WhenTo le datetime'2016-06-17T00:00:00'`

Is this the right way of grouping multiple or statements or is there another?

Thanks

**Comment by object** [comment]
But why should it add parenthesis? AND has higher precedence than OR, so parenthesis should not be necessary.

**Comment by roly445** [comment]
If that's the case then OK, but will it start to add parenthesis as the query requires it, i.e. becomes more complex? I'm refering to [http://www.odata.org/documentation/odata-version-3-0/url-conventions/](http://www.odata.org/documentation/odata-version-3-0/url-conventions/) section _5.1.2.5. Operator Precedence_ regarding grouping.

**Comment by object** [comment]
Yes it should. If if you find an example where it doesn't please let me know.
