### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by konytskyy** [object/Simple.OData.Client#268]
Hi
I have this situation

    public enum TipoAddetto
    {
        Dipendente = 0,
        Consulente = 1,
    }

    public class Addetto
    {
        public int Oid { get; set; }          // Key
        public string Acronimo { get; set; }
        public TipoAddetto TipoAddetto { get; set; }
        public string Codice { get; set; }
        public Sede SedePrincipale { get; set; }

        public Addetto()      {     }
    }

     public class Rimborso
    {
        public int Oid { set; get; }           // Key
        public DateTime Data { set; get; }
        public string Descrizione { set; get; }
        public decimal RimborsoKM { set; get; }
        public decimal IndennitaTrasferta { set; get; }
        public decimal RimborsoSpese { set; get; }
        public Addetto Addetto { set; get; }

        public Rimborso()    {      }
    } 

  The query : 

            var rimborsi = await client.For<Rimborso>()
                                 .Expand(r=>r.Addetto)
                                 .Filter(r=> r.Addetto.Oid == 3)
                                 .FindEntriesAsync();

will produce this request :

GET request: http://localhost:60085/Si.JobTime.ODataService.svc/Rimborso(3)?$expand=Addetto

which is not correct !!!

I expect this request - the filter on Addetto.Oid

GET request: http://localhost:60085/Si.JobTime.ODataService.svc/Rimborso?$filter=Addetto%2FOid%20eq%203&$expand=Addetto

this is strange because this query

            var rimborsi = await client.For<Rimborso>()
                                 .Expand(r=>r.Addetto)
                                 .Filter(r => r.Addetto.Acronimo == "AG")
                                 .FindEntriesAsync();

produce correct request

GET request: http://localhost:60085/Si.JobTime.ODataService.svc/Rimborso?$filter=Addetto%2FAcronimo%20eq%20%27AG%27&$expand=Addetto

**Comment by object** [comment]
This is actually correct, because Oid is a key, so the filter Oid == 3 is converted to a key lookup Rimborso(3). Acronimo is not a key so its filter is converted into a Filter expression.

**Comment by konytskyy** [comment]
Hi,
thank you for quick replay.
But how can I filter by  .Addetto.Oid in this case? This is child property and I have no clue how to do it. Yes of course I can use this

.Filter(String.Format("Addetto/Oid eq {0}", adetto.Oid))

but I prefer LINQ way query

**Comment by object** [comment]
You can still use typed syntax in Filter, but for key fields it will be replaced in the generated URI with a key lookup. In other words, the library will build the URI according to the schema no matter if you use Key or Filter syntax. But you can't use greater or less in filters for key fields, only equality.

**Comment by konytskyy** [comment]
Hi, thank you for clarification !!!
In other words for Filter :  Rimborso.Oid  and Rimborso.Addetto.Oid always converted in  Rimborso.Oid in generated uri as I understand.

**Comment by konytskyy** [comment]
I should say that this

       var rimborsi = await client.For<Rimborso>()
                             .Expand(r=>r.Addetto)
                             .Filter(r => (r.Addetto.Oid == adetto.Oid) && (r.Data > someDate))
                             .FindEntriesAsync();

works as expected and fortunately I need this type of filter

than you

**Comment by object** [comment]
Good to know it worked for you!
