### ISSUE TITLE
Is there a way to query the service root (i.e. the service path without any other parameters) or skip the response processing?

### ISSUE THREAD

**Issue by monczszilard** [object/Simple.OData.Client#270]
I need to execute some simple GET request to be able to fetch the csrf-token value.
When I trying to use
`client.FindEntriesAsync("").Wait();`
it throws an exception during response parsing.
Is there some way how to do this special request or generally how to do a request without parsing the response? I retrieve the wanted csrf token in the AfterResponse interceptor so don't need further response processing.
Of course I can fetch any object by (non-existing) key as a workaround, just curious if there is another alternative.

**Comment by object** [comment]
Try FindScalarAsync. This one expects a single value of a specific type.
