### ISSUE TITLE
Get status code on successful request

### ISSUE THREAD

**Issue by barangutan** [object/Simple.OData.Client#278]
Hi there. I'm aware that you can extract the status code for unsuccessful requests via the `WebRequestException` object, however I want access to the status code for a _successful_ request.

Given: 
```
public async Task<Product> UpdateProductAsync(int key, object update)
{
   return _client.For<Product>().Key(key).Set(update).UpdateEntryAsync();
}
```
Instead of returning a Product object, I want to return my own implementation of an "ApiResponse" object, which as a Product property as well as information about the status code, maybe response headers etc.

```
public async Task<IApiResponse> UpdateProductAsync(int key, object update)
{
    IApiResponse<T> response;

    try
    {
        Product updated = _client.For<Product>().Key(key).Set(update).UpdateEntryAsync();

        response = new ApiResponse<T>
        {
            Payload = updated,
            StatusCode = // ???
        };
    }
    catch(WebRequestException ex)
    {
        response = new ApiResponse<T>
        {
             StatusCode = ex.Code.ToString()
         };
    }
            
    return response;
}
```
I hope you understand my intention and apologies if this isn't the best place to ask!

**Comment by object** [comment]
First what comes to my mind is to use AfterResponse to intercept the response and read its data:

var settings = new ODataClientSettings
            {
                BaseUri = _serviceUri,
                AfterResponse = x => { /* do something with the response */  },
            };
var client = new ODataClient(settings);
client...
