### ISSUE TITLE
Unable to identify OData protocol version [New bug introduced to 4.20.0 & 4.21.0]

### ISSUE THREAD

**Issue by cdotnet** [object/Simple.OData.Client#280]
I've been using v4.19.0 for awhile, decided to update to 4.20.0 and now all my queries return a "Unable to identify OData protocol version" error message. 

Using the client to query ProjectServer Odata API. 

Query example: 

https://siteserver.sharepoint.com/sites/pwa/_api/ProjectData/Projects?$filter=ProjectId eq guid'ef2a052f-5609-e511-80c8-00155d68241d'&$select=ProjectId,ProjectModifiedDate,ProjectName,ProjectWorkspaceInternalUrl,EnterpriseProjectTypeDescription,EnterpriseProjectTypeId

Please let me know if you need more information.

**Comment by object** [comment]
Hi,
This is very strange indeed. I don't see in the change log anything that could cause such major regression.
Unfortunately I don't have access to siteserver.sharepoint.com, so I have no possibility to test this. Perhaps you can trace HTTP traffic in Fiddler and send me the response? My mail address is vagif.abilov at gmail.

**Comment by cdotnet** [comment]
Hi,

Thank you very much for your prompt response. I played around with it a bit more but removing the client and few dependencies entirely and adding them again seems to have solved the issue. 

Apologies for raising an issue needlessly. If I find out how to replicate the issue I'll keep you posted. 


Regards,
Ali

**Comment by object** [comment]
No problem. This one really scared me. I reran all my tests, including those I ran agains Microsoft reference services (using various OData versions), and they all passed. So I hope there's nothing in the library on this matter. Otherwise let me know, I am closing the issue for now.
