### ISSUE TITLE
Collection Parameters

### ISSUE THREAD

**Issue by ChristofferBergkvist** [object/Simple.OData.Client#282]
Hi

According to this:
http://odata.github.io/WebApi/#04-07-action-parameter-support

Collection parameters of primitive types but also ComplexTypes and EntityTypes should be supported as parameters in odata actions and functions.

I am using Web API 2.2 on server and I can create actions and functions that accepts collection parameters of primitive types (ints, strings etc).

However I can't figure out how to get Simple.OData to work when the parameter is a collection of ComplexType or EntityType!

**Error message:**
Unsupported primitive type. A primitive type could not be determined for an instance of type 'TestComplexType'

What I am trying to do is to invoke a bound action on the entity MotionGroup and send a parameter containing a list of TestComplexType. TesComplexType only has two properties, an int and a string. 

**WebApiConfig.cs:**
`builder.ComplexType<TestComplexType>();`
`builder.EntityType<MotionGroup>().Collection.Action("ComplexAction").CollectionParameter<TestComplexType>("ComplexTypes");`		

**MotionGroupsController**
`[HttpPost]
public async Task<IHttpActionResult> ComplexAction(ODataActionParameters parameters)
{
return StatusCode(HttpStatusCode.NoContent);
}`

**Client**
`await client.For<MotionGroup>().Action("ComplexAction").Set(new Dictionary<string, object>() { { "ComplexTypes", complexTypes } }).ExecuteAsync();`

or
`await client.For<MotionGroup>().Action("ComplexAction").Set(new { ComplexTypes = complexTypes }).ExecuteAsync()`

where complexTypes is a list of TestComplexType

**Comment by ChristofferBergkvist** [comment]
It works if I manually create a ODataComplexValue object instead. 
`ODataComplexValue complex = new ODataComplexValue();
ODataProperty p1 = new ODataProperty();
p1.Name = "TestProperty1";
p1.Value = 123;

ODataProperty p2 = new ODataProperty();
p2.Name = "TestProperty2";
p2.Value = "Hejjefker";

complex.TypeName = "TEMCommon.Database.TestComplexType";
complex.Properties = new[] { p1, p2 };
await client.Unbound().Action("TestComplexAction").Set(new { TestComplexType = complex }).ExecuteAsync()`

**Comment by ChristofferBergkvist** [comment]
Hi again

It works if I manually build a list of ODataComplexValue instead and pass this list as an argument. But then I also need to manually set property names and copy values for each item. 

As described in this post:
http://stackoverflow.com/questions/33720502/odatacomplexvalue-actions-and-casting

So my server code is fine but I suspect there is a bug in Simple.OData...

**Comment by object** [comment]
Thank you for detailed information. Yes, it seems this is a bug in the library. I will investigate it further.

**Comment by object** [comment]
Should work in 4.24.
