### ISSUE TITLE
Request metadata document

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#283]
Is there an easy way of just requesting the metadata document - I want to prove that I'm authenticated to my service, and I figure that this is the easiest way to determine that; authorization may disallow access to various entities so I don't want to ask for real data.

**Comment by object** [comment]
Yes, check out GetMetadataAsync and GetMetadataDocumentAsync.

**Comment by phatcher** [comment]
Thanks Vagif - any timeline on V5, can I help at all?

**Comment by object** [comment]
I've uploaded V5 alpha with enabled streaming, but there were some bugs reported, I have to investigate them.
