### ISSUE TITLE
Simple.OData.Client Insert issue 

### ISSUE THREAD

**Issue by ramireddyraam** [object/Simple.OData.Client#288]
I am unable to insert data to odata service 
service do not have authentication but when i am trying to insert data it giving Unauthorized issue 
 **Exception Details: Simple.OData.Client.WebRequestException: Unauthorized**.

Note : I am able to insert and Get data

**Comment by object** [comment]
Can you trance the call in Fiddler and check what's going on with HTTP traffic. Since service doesn't have authentication you should be able to post data directly from Postman or some other HTTP utility.

**Comment by ramireddyraam** [comment]
string StrUrl = "https://ebiztest.aoa.org/PersonifyDataServices/PersonifyDataAoaCustom.svc";
        private const string _user = "aoa_sso";
        private const string _password = "@St34m3dH4m$";

        protected void Page_Load(object sender, EventArgs e)
        {
            SharePointGetDemoList();
        }



        public async void SharePointGetDemoList()
        {
       
            ODataClientSettings settings = new ODataClientSettings()
        {
            UrlBase = StrUrl,
            Credentials = new NetworkCredential(_user, _password)
        };
            
            var client = new ODataClient(settings);

            var DemoList = await client
           .For("Countries")
           .FindEntriesAsync();

        }




when i am trying with valid Details also it giving same Error.
Exception Details: Simple.OData.Client.WebRequestException: Unauthorized

**Comment by ramireddyraam** [comment]
![image](https://cloud.githubusercontent.com/assets/21074950/17732033/a4735f0e-648d-11e6-8b38-5578d852905f.png)

**Comment by object** [comment]
But it must be something with authentication then, as you can see in the Fiddler: No Proxy-Authenticate header is present. And is also fails on GET requests, you previously said GET was working?

Can't really say what this could be apart from that there were no changes in authentication implementation lately, and all related tests work.

**Comment by ramireddyraam** [comment]
Thanks for replay .
