### ISSUE TITLE
Replace Microsoft.Net.Http with System.Net.Http in V5

### ISSUE THREAD

**Issue by object** [object/Simple.OData.Client#290]
Here's a summary of what needs to be done
1. V4 will continue using Microsoft.Net.Http (and dependencies on Microsoft.Bcl.Build and Microsoft.Bcl). It will not be upgraded to use the new System.Net.Http Nuget package.
2. V5 will stop using Microsoft.Net.Http and will use System.Net.Http instead.
3. Simple.OData.Client.Net40 and Simple.OData.Client.SL5 will only live in V4. V5 will exclude these legacy platforms.
4. All V5 libraries will be PCLs: Simple.OData.Core, Simple.OData.V3.Client and Simple.OData.V4.Client.
5. Simple.OData.Client.Tests projects for Net40 and SL5 will only live in V4.
6. Simple.OData.Client.Net45.Tests in V4 includes references to test source code (from Net40.Tests folder). Source files from Net40.Tests folder will be moved to Net45.Tests folder so they can be included directly.

**Comment by Maxwe11** [comment]
I have tried to do something against this issue but got stuck with some problems.
For using System.Net.Http we need to drop support of Windows Phone Silverlight 8.1 platform and  update version of Microsoft.OData.Core up to 7.0.0. 
Is these changes acceptable?

**Comment by object** [comment]
I just discussed ODataLib 7.0 in another issue:
https://github.com/object/Simple.OData.Client/issues/298

Yes, this is acceptable and probably the right way to make a clean next major version. V4 will structurally stay the same, I will only apply bug fixes to it. It will support legacy platforms, and by "legacy" I mean both .NET FX 4 and OData V3. It will use profile 259 like it is now.

Version 5 is another story, it's OK not to drag any legacy stuff that would compromise. Modern System.Net.Http like you suggested, Microsoft.OData.Core 7.0 etc. New PCL profile supported by ODataLib 7. No Silverlight or WP Phone SL 8.1.

To make tests for it more lightweight I am changing now tests from using Microsoft SQL Server CE to use in-memory EF context. Should complete sometimes next week.

**Comment by phatcher** [comment]
I'd agree about not taking OData 3 into S.O.D 5 - they are not patching the OData 3 libraries even when it would be simple to do so.

**Comment by object** [comment]
Which is quite sad because it's still used a lot and as you said the fix would be quite simple.

**Comment by phatcher** [comment]
They seem to be very resource constrained for what should be a major library - but then they avoid communicating for months about intent etc so they don't get much community support.

Also, the whole .NET Core stuff is still a distraction for any project which needs to deliver in the next 18 months, because the 1.0 target has so little in it compared to the standard .NET

**Comment by NetTecture** [comment]
Is there an idea of a timeframe for v5 availability, both in possible release and as published prerelease? I am quite eager for both streaming and this issue.

**Comment by object** [comment]
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7. So this issue should be resolved.
