### ISSUE TITLE
Unable to insert Data

### ISSUE THREAD

**Issue by ramireddyraam** [object/Simple.OData.Client#300]
![image](https://cloud.githubusercontent.com/assets/21074950/18161147/5f17b6e0-704e-11e6-8297-4b322da5a29b.png)

string StrUrl1 = "http://services.odata.org/V3/OData/OData.svc";

            var settings = new ODataClientSettings()
            {
                UrlBase = StrUrl1
               // ,Credentials = new NetworkCredential(_user, _password)
            };

            var client = new ODataClient(settings);

            var category = await client
        .For("Categories")
        .Set(new { Name = "Test5" })
        .InsertEntryAsync();

**Comment by object** [comment]
The project contains a large set of tests against services.odata.org. Please check out the project Simple.OData.Client.IntegrationTests. You will find tests for all major scenarios. In your code you may need to specify category ID when inserting a new record.
