### ISSUE TITLE
MetadataDocument cached ,So updation in server OData service model causing issue

### ISSUE THREAD

**Issue by beforeyousreejesh** [object/Simple.OData.Client#301]
Hi,
 we have a OData service which is consumed using Simple.OData.Client. As per your documentation Metadata will get cached at first request and the same will reuse for the following requests. Our issue is like we have updated our Odata service model but our client still uses the old Metadata document. So it is throwing an error like _**"An internal error occurred.  The property 'propertyName' does not exist on type 'TypeName'. Make sure to only use property names that are defined by the type"**_ unless we do an IISRESET( as our application is windows based and deployed in IIS). Which will eventually clear the cache. The error is throwing from 
`Microsoft.OData.Core.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderEntryState entryState, String propertyName, Boolean propertyWithValue)`
 and while going thorugh the source code we found that we need to set `UndeclaredPropertyBehaviorKinds` to ` ODataUndeclaredPropertyBehaviorKinds.IgnoreUndeclaredValueProperty;` in ODataMessageReaderSettings for the ODataMessageReader.
                                         But when we checked your code you are not providing a way to extend or override this property. Is it possible to load MetdataDocument every time from server rather than keeping in cache and load it from there or override that property as i mentioned before?. Meanwhile we have tried for
  

- ` odataClientSettings.MetadataDocument =  client.GetMetadataDocumentAsync().Result;
     var test = client.For<Organization>().Key(1).FindEntryAsync().Result;`  in order to reload and override existing Metadata but seems its getting from the Cache not from the server.

- `odataClientSettings.IgnoreUnmappedProperties=true;`. does not work.

**Comment by object** [comment]
If you don't set odataClientSettings.MetadataDocument then it will load the metadata from the server first time the client accesses the service. Can't your client app just leave MetadataDocument unset?

**Comment by beforeyousreejesh** [comment]
Hi,

**Comment by vojtechvit** [comment]
Hi @object, the Metadata Document is not set manually in the described scenario - it's loaded automatically into the cache on the first request to the OData service. However, it does not refresh when the OData service changes its model (on deployment of a new version for instance) and consequently causes problems even on non-breaking changes like when new fields are added to a type in the model. Such changes to the Service Model should be expected by OData v4 compliant clients and therefore they should not break them - see [OData v4 Model Versioning](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752210).

**Comment by object** [comment]
Oh I see, so you want the client to be able to respond on service metadata updates as they happen.
There is a static method ODataClient.ClearMetadataCache() that you can of course use, but the challenge is that the client doesn't know when exactly the metadata changes. And reloading metadata is an expensive operation so I wouldn't recommend doing this before each request.

But I agree with you that the client should survive compatible model changes. I will look into it. Thank you for the sample solution.

**Comment by Allann** [comment]
Would it be an idea to look for a specific error, and then automatically retry a Metadata fetch on failure.  Only retry once.  I agree doing a fetch on each request would destroy performance, and double bandwidth.

**Comment by object** [comment]
This can be a complicated check because such error can be raised in different places, depending on when an attempt to access changed entity type was made. And from that place it can be complicated to come back to the beginning of the call chain. So I woudn't bet on this strategy. It's better to fix it properly.

**Comment by beforeyousreejesh** [comment]
How about considering this one https://msdn.microsoft.com/en-us/library/microsoft.data.odata.odatamessagereadersettings.undeclaredpropertybehaviorkinds(v=vs.113).aspx

**Comment by object** [comment]
Yes, this is reasonable option.

**Comment by object** [comment]
Ignoring undeclared properties is added in 4.24.
