### ISSUE TITLE
Expand 3 Levels deep all One To One relationships

### ISSUE THREAD

**Issue by jmfronsee** [object/Simple.OData.Client#309]
Lets say I have this data setup:   A Computer has 1 Store.  A Store has 1 Group.  A Group can have 1 Corporation.
Corp
     Group
          Store
                 Computer.

It looks like I can Expand MOST of these levels in one Expand call (all the way up to Groups), like:

var saList = await client
           .For<computer>()
           .Expand(x => x.store.groups)
           .FindEntriesAsync();

- BUT if I add in the last level (corporation) in the Expand, like this below, it fails / Not Found:
.Expand(x => x.store.groups.corporation)

How do I go about expanding all the way up to Corporation on a Computer like this?

**Comment by jmfronsee** [comment]
No multiple groups, disregard the s's.  Yes LINQ select would make sense with multiple, not sure with the 1 to 1 though?  Is there a limitation on the "levels" of entities we can go up from the main entity?

Get Outlook for iOS

		_____________________________

**Comment by object** [comment]
No there is no limit on number of levels. To investigate this I need to know what URL is generated and the service metadata, at least the entity types and entity sets involved in this query.

**Comment by jmfronsee** [comment]
http://workstationmanage-env.us-west-2.elasticbeanstalk.com/odata/

I might delete this URL after we figure this out.   Again disregard the s's, and the objects are named different in the above url.  Basically I want to:

.For<workstation>()
.Expand(x => x.restaurant.restaurant_groups.dealer)

Expand everything associated to the workstation up to the dealer.   Thank you for your time.

**Comment by object** [comment]
I see. So if everything works correct, it should generate a URI restaurants?$expand=restaurant_groups($expand=dealer)

I've made a copy of your service metadata. This should be sufficient for me to reproduce the error.

**Comment by object** [comment]
I wrote a small test, and it works OK, here's the code:

        class restaurant
        {
            public int id { get; set; }
            public int restaurant_group_id { get; set; }
            public string name { get; set; }
            public restaurant_groups restaurant_groups { get; set; }
        }

        class restaurant_groups
        {
            public int id { get; set; }
            public int dealer_id { get; set; }
            public string name { get; set; }
            public dealer dealer { get; set; }
        }

        class dealer
        {
            public int id { get; set; }
            public string name { get; set; }
        }

        [Fact]
        public async Task ExpandWorkstation()
        {
            var client = CreateClient("Workstation.xml");

            var expectedResult = @"restaurants?$expand=restaurant_groups($expand=dealer)";

            var command = client.For&lt;restaurant&gt;()
                .Expand(x => x.restaurant_groups.dealer);

            string commandText = await command.GetCommandTextAsync();
            Console.WriteLine(commandText);

            Assert.Equal(expectedResult, commandText);
        }

Can you compare with your code?

**Comment by jmfronsee** [comment]
The example you posted above works, and has always worked - any query I can get to work when it is only going 2 levels deep like that, but my concern was on this example:.For<workstation>().Expand(x => x.restaurant.restaurant_groups.dealer)- Notice For workstation not restaurant, one more level deep adding in the Workstation and then it fails / Not Found or Bad Request it was one of the 2.   In my example here, if I remove the .dealer part it works, it just cant seem to get that 3rd level (and im assuming any level beyond that)Joe Fronsee


-------- Original Message --------
Subject: Re: [object/Simple.OData.Client] Expand 3 Levels deep all One
To One relationships (#309)

**Comment by object** [comment]
I first wrote an example with fewer levels but then updated it to reflect what you mean. Note how the recent version looks: client.For<workstation>().Expand(x => x.restaurant.restaurant_groups.dealer);

Isn't this what you are after?

**Comment by jmfronsee** [comment]
That is what im after, but when I add the .dealer part to the end I get a "Bad Request" error...  it only lets me go as far as restaurant_group .Joe Fronsee


-------- Original Message --------
Subject: Re: [object/Simple.OData.Client] Expand 3 Levels deep all One
To One relationships (#309)

**Comment by object** [comment]
Ha! I guess I know. I only ran the test and verified that generated URL was correct, I didn't run it agains the actual service. Now when I am doing this:

http://workstationmanage-env.us-west-2.elasticbeanstalk.com/odata/workstations?$expand=restaurant($expand=restaurant_groups($expand=dealer))

I get the error from the server:

{
  "error":{
    "code":"","message":"The query specified in the URI is not valid. The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings."
  }
}

So the error is on the service side and you have to reconfigure your service to support deeper expansions.

**Comment by jmfronsee** [comment]
Sorry to have you debug my server then :/Figured the .net Web API Odata stuff would allow that by default.   There is no way to "bubble" the server errors to the client?  "Bad Request" and "Not Found" drives me nuts .   Thanks again

Get Outlook for iOS




On Tue, Sep 20, 2016 at 3:10 AM -0700, "Vagif Abilov" <notifications@github.com> wrote:












Ha! I guess I know. I only ran the test and verified that generated URL was correct, I didn't run it agains the actual service. Now when I am doing this:



http://workstationmanage-env.us-west-2.elasticbeanstalk.com/odata/workstations?$expand=restaurant($expand=restaurant_groups($expand=dealer))



I get the error from the server:



{

  "error":{

    "code":"","message":"The query specified in the URI is not valid. The request includes a $expand path which is too deep. The maximum depth allowed is 2. To increase the limit, set the 'MaxExpansionDepth' property on EnableQueryAttribute or ODataValidationSettings."

  }

}



So the error is on the service side and you have to reconfigure your service to support deeper expansions.

**Comment by object** [comment]
You can always get HTTP status code from the server, but in many cases this is not enough. What I usually do when such things happen is to start Fiddler and inspect HTTP traffic. Then I can see both generated URLs and response to them. It is often important to distinguish between server and client-side error. For me as a client library writer is a must.

**Comment by HEBOS** [comment]
I was struggling with this issue also and it took me two days to figure this out.
Simple.OData has nothing to do with it. It works as expected.
WebApi service is the cause of this.
If you take a look at source of EnableQueryAttribute you will see that you have to override it and change MaxExpansionDepth and LevelsMaxLiteralExpansionDepth value.
Source for this is [here](https://github.com/OData/WebApi/blob/master/OData/src/System.Web.OData/OData/EnableQueryAttribute.cs).

This is my override:
`    public class EnableSecureQuery : EnableQueryAttribute
    {
        public EnableSecureQuery()
        {
            MaxExpansionDepth = 10;
        }
		
		public override void ValidateQuery(HttpRequestMessage request, ODataQueryOptions queryOptions)
        {
            if (queryOptions.SelectExpand != null)
                queryOptions.SelectExpand.LevelsMaxLiteralExpansionDepth = 10;

            base.ValidateQuery(request, queryOptions);
        }
    }
`

**Comment by jmfronsee** [comment]
OH! That sounds promising.  Sorry I was assuming this was an issue with Simple.Odata.  I should have thought to look into the default API settings a bit.  Will look into this more when I have to make any edits to the API, as I coded up a work around...  Thanks for reply HEBOS!
