### ISSUE TITLE
Passing username and password in querystring

### ISSUE THREAD

**Issue by achmadmulyadi** [object/Simple.OData.Client#311]
Is there any way to pass my username and password into querystring? I pass the credential using this format: http://myServer/MyDataService.svc/MaritalStatus?$filter=Description%20eq%20%27Single%27&UserName=myUserName&Password=myPassword.
I have tried setting the NetworkCredential but no luck, everything works like charm if I turn off the authentication. 

Regards,

Achmad Mulyadi

**Comment by phatcher** [comment]
@achmadmulyadi if you have any choice in the matter, change the service so that the username and password are not in the url - they will get recorded in the web server logs, proxies etc so it is not at all secure.

**Comment by object** [comment]
I second what Paul wrote and advice you from sending your credentials in a URL string. However, in the forthcoming version 5 there will be support for adding custom query options in addition to standard OData query words. Right now you have to rewrite the URL using HTTP request interception (the library offers support for it in ODataClientSettings).

**Comment by achmadmulyadi** [comment]
@phatcher Thanks for the advice, will surely changed to a better way.

@object What a wonderful library you have, and thanks'
