### ISSUE TITLE
Unable to set the queue

### ISSUE THREAD

**Issue by MilindKothavade** [object/Simple.OData.Client#315]
How queue needs to be set using Simple.Odata.Client?
Tried using AddtoQueue option but it does not helps to set the queue.
Pls. note that we need to set queue using C# code.

Kindly advise.

**Comment by object** [comment]
Again, as I wrote in the comment to another issue, OData protocol has nothing to do with queues. Please read about OData services, its metadata documents and how to consume and manage OData services from OData clients.
