### ISSUE TITLE
Setting ActivityPartyType

### ISSUE THREAD

**Issue by MilindKothavade** [object/Simple.OData.Client#316]
How are we supposed to set the ActivityPartyTypes in CRM using Simple.Odata.Client nuget in C# code?
Kindly advise.

**Comment by object** [comment]
Simple.OData.Client is just an OData client, it has no special knowledge of your CRM. Everything that is exposed by your OData service via its metadata document is available to the library. Please have a look at Wiki pages and the library tests for better understanding how it works.
