### ISSUE TITLE
Fetching child details

### ISSUE THREAD

**Issue by MilindKothavade** [object/Simple.OData.Client#317]
How to fetch child details of Parents child using Simple.Odata.Client nuget in c# code?
Currently we have used EXPAND to get the details but it is fetching data of Parent and its all Child details. But, we are not able to get Childs child details
For better understanding refer following example
Object A (Parent)
Object B (Child of Parent i.e. Object A)
Object C (Child of Object B)

We are able to fetch details till Object B but we are not able to fetch details of Object A, B & C in one  call using this nugget. There is a need to fetch all child details of single parent in proper hierarchy.

Would highly appreciate if you can share any way which would solve this problem.

Thanks.

**Comment by object** [comment]
Please have a look at these tests:

https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Tests.Core/ExpansionTests.cs

You will find various examples of expansion and selection of expanded entities.

Some examples here might also be interesting:
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.IntegrationTests/TripPinTests.cs
