### ISSUE TITLE
oData not able to parse FetchXml response 

### ISSUE THREAD

**Issue by sbpatil1975** [object/Simple.OData.Client#318]
Hi Christopher, 
I am trying to execute fetchxml on MS CRM 2016 Webapi using below code but not able to parse jSON result as showing below error

The property **'phonecall1_x002e_new_phonetype' does not exist on type 'Microsoft.Dynamics.CRM.new_loan'. Make sure to only use property names that are defined by the type.**

Fetchxml as below
![fetchxml](https://cloud.githubusercontent.com/assets/22682977/19235835/092ce5ae-8eec-11e6-8c31-1b0761b09b24.JPG)

var entityData = await client.FindEntriesAsync("new_loans?fetchXml="+ Uri.EscapeUriString(fetchXml));
var jsonResult = JsonConvert.SerializeObject(entityData.ToList());
return jsonResult;

I am seeing that jSON result prefixes the **x002e_** for each link-entity property due to that parser failed. Is there any way to get rid of this

Fiddler response shows properly as expected

![json](https://cloud.githubusercontent.com/assets/22682977/19235904/563f706e-8eec-11e6-80b3-e0a6e13b5ab7.JPG)

Regards,
Sanjay Patil

**Comment by sixlettervariables** [comment]
`\x002E` is the unicode escape for a period. So apparently CRM is returning these as `phonecall1.createdby`, which is escaping the period as `_x002e_`.

This appears to be a CRM issue rather than a Simple.OData.Client issue.
