### ISSUE TITLE
Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter

### ISSUE THREAD

**Issue by sbpatil1975** [object/Simple.OData.Client#321]
Hi, 
"Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter"
this issue appers again when you update package like odata.edm, odata.core etc.

even after puting below line doesn't work
V4Adapter.Reference();

Please advice

**Comment by MilindKothavade** [comment]
Does Simple.Odata.Client 4.2.4/5.0.0-alpha supports Microsoft.Odata.Core V7.0.0 nuget package?
Combination of Simple.Odata.Client 4.2.4 + Microsoft.Odata.Core 6.15 also gives above error.

Pls. advise.

**Comment by object** [comment]
No, not yet. Version 4.x most likely will never support ODataLib 7.0 due to major changes. I plan to update version 5 to support ODataLib 7.0, but unfortunately can't give any time estimate due to time pressure from other projects.

**Comment by phatcher** [comment]
@object Can I suggest that you put a NuGet restriction on Microsoft.OData.Core for the next release so that it won't let us update inadvertently.

**Comment by object** [comment]
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7.
