### ISSUE TITLE
Unable to use expand or select on lookup field of crm entity

### ISSUE THREAD

**Issue by MilindKothavade** [object/Simple.OData.Client#322]
Hi,

Following is the scenario for subject mentioned issue

Name of parent entity : entityparent
Name of relationship present on parent entity: new_entityparent_annotation
createdby field is present in 'new_entityparent_annotation' which is 'lookup' field.

Tried lot of ways to get createdby details but it is giving error as multiple level expansion is not supported.

Exact error is as below:
{
  "error":{
    "code":"","message":"The \"new_entityparent_annotation\" navigation property can't be expanded. Multiple levels of expansion aren't supported.","innererror":{
      "message":"The \"new_entityparent_annotation\" navigation property can't be expanded. Multiple levels of expansion aren't supported.","type":"Microsoft.Crm.CrmHttpException","stacktrace":"   at Microsoft.Crm.Extensibility.OData.QueryOptionsConverterBase`4.ThrowIfExpandItemsExist(ExpandedNavigationSelectItem navigationItem)

Is there any way to fetch such detail?

Kindly advise.

**Comment by object** [comment]
Multilevel expansion is in fact supported by Simple.OData.Client. I guess you should configure your OData service to enable multi-level expansion (in case it can be enabled).

**Comment by MilindKothavade** [comment]
I'm using .Net code to fetch the details and while building the OdataClient I did set the attribute 'IncludeAnnontationInResults' to true but this also does not helps to solve the issue.

I'm sure I might have missed on something in the code but I'm not able to find anything which will enable/ disable multi-level expansion.

This is how I'm fetching the details using simple.odata.client (just in case if this helps)
Step 1. Build the OdataClient
Step 2. Acquire the token
Step 3. Execute the query to fetch the details using 'Expand' option

Is there any attribute available in simple.odata.client which can enable/disable  multi-level expansion.

Pls. share any test case which is fetching details like Parent > Child > sub child details which is 'Lookup Property'.

Do let me know if you need any further details from my end to look into this issue.

Also, even 'LookUp' property details are not getting loaded in Fiddler.

Thanks.

**Comment by object** [comment]
I am pretty sure this is the server issue. Here's a similar one:

https://github.com/object/Simple.OData.Client/issues/309

The exception Microsoft.Crm.Extensibility.OData.QueryOptionsConverterBase`4.ThrowIfExpandItemsExist is thrown from the MS CRM. And the exception clearly say "Multiple levels of expansion aren't supported". There is nothing you can on the client side if the server side denies to expand. You can verify it like this: note the URL that ODataClient generates with this request (you can see it for example in Fiddler), and then paste this URL in the browser. You should see the same exception raised by the service.

And here is a link to an article that says about limitations of expansion in Microsoft Dynamic CRM (don't know if this is the one you are using):
http://www.inogic.com/blog/2016/01/querying-data-in-microsoft-dynamics-crm-2016-using-web-api/
