### ISSUE TITLE
Tag for v4.24.0

### ISSUE THREAD

**Issue by arch-imp** [object/Simple.OData.Client#324]
I would like to download the source for nuget package v4.24.0.  I can't find that tag under releases or in the github tags list.  Has it been tagged?  If not, what changeset equates to v4.24.0?

**Comment by object** [comment]
Thank you for pointing this out. Yes, I didn't push the tag for 4.24 (will do it shortly), but this release corresponds to the last commit in "v4" branch:

https://github.com/object/Simple.OData.Client/commit/99ea5066dfa7afdeeab21751c88d9daa99938611

**Comment by object** [comment]
That tag is applied to the Git repo.
