### ISSUE TITLE
BestMatch can't distinguish between Actions/Functions of same name on different EntityTypes

### ISSUE THREAD

**Issue by jdunkerley** [object/Simple.OData.Client#328]
I was having an issue POSTing to an Action where the same name is used on two different Entity Types:

`<Action Name="AppendToPoints" IsBound="true">
<Parameter Name="bindingParameter" Type="JDunkerley.VectorTimeSeries"/>
<Parameter Name="Points" Type="Collection(JDunkerley.VectorPoint)"/>
</Action>
<Action Name="AppendToPoints" IsBound="true">
<Parameter Name="bindingParameter" Type="JDunkerley.PriceBarSeries"/>
<Parameter Name="Points" Type="Collection(JDunkerley.PriceBarPoint)"/>
</Action>`

It detects whichever one it finds first in the metadata, I tried a quick fix passing the entity type down the stack: https://github.com/jdunkerley/Simple.OData.Client/commit/db9322ad03b721e3fd08d08c5cf93e92754919f0

I was having difficulties with Expands when running off the source code to test but think this resolved the action issue.

**Comment by object** [comment]
This is a known limitation (actuall a bug). I plan to fix it in version 5 where use of OData actions/functions will be rewritten. No exact date unfortunately.

**Comment by jdunkerley** [comment]
thanks for getting back. 

I couldn't find the 4.24 source code and was having difficulty with making a patched version. Could you point me in the direction?

**Comment by object** [comment]
I pushed the tag for version 4.24.0 just now.

**Comment by jdunkerley** [comment]
thanks.

**Comment by object** [comment]
I checked your fix and I believe I can use your code in version 4 because it really fixes this issue. The fix will be published soon.

**Comment by jdunkerley** [comment]
great. I have rebased onto the 4.24 version (thanks for pushing) up.

Do you want me to open a PR for it?

**Comment by object** [comment]
Thanks. No need for PR. I have applied the fix using your code but encountered a few test failures for some special scenarios. I will need to revise the code a little.

**Comment by object** [comment]
Release in 4.24.1.
