### ISSUE TITLE
Failed to install on an Xamarin.Forms Portable Project

### ISSUE THREAD

**Issue by ahmed-sherien** [object/Simple.OData.Client#333]
Every time it gives me this error:
```
Could not install package 'Microsoft.OData.Edm 6.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content 
files that are compatible with that framework. For more information, contact the package author.
```

**Comment by object** [comment]
Which version of Simple.OData.Client are you trying to use? Can you paste the content of your packages.config?

**Comment by richardalmonte** [comment]
Hi,

I'm having the same problem with this package and I'm using Simple.OData.Client 4.24.0.

**Comment by candidodmv** [comment]
I'm having the same problem @object my package.config follows

```
> <?xml version="1.0" encoding="utf-8"?>
> <packages>
>   <package id="Fody" version="1.29.4" targetFramework="portable45-net45+win8+wp8+wpa81" developmentDependency="true" />
>   <package id="FreshMvvm" version="2.2.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="Microsoft.Bcl" version="1.1.10" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="Newtonsoft.Json" version="9.0.1" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="Plugin.Share" version="4.0.3" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="PropertyChanged.Fody" version="1.52.1" targetFramework="portable45-net45+win8+wp8+wpa81" developmentDependency="true" />
>   <package id="Xam.Plugin.FilePicker" version="1.1.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
>   <package id="Xamarin.Forms" version="2.3.2.127" targetFramework="portable45-net45+win8+wp8+wpa81" />
> </packages>
```

**Comment by erikcordeiro** [comment]
I'm have the same problem. Any solution?

**Comment by object** [comment]
As I can see from the error message in the first comment, the project uses Profile 111 which Simple.OData.Client currently doesn't support due to its compatibility with of ODataLib that it depends on. In order to use Simple.OData.Client you need to target a different PCL profile (259 is among supported ones).

Profile 111 will be supported by future version of Simple.OData.Client that will targer Microsoft.OData.Core vesrion 7.

**Comment by AndreaSteiner** [comment]
I'm having the same issue as above, but with profile 259.  Thoughts?

`Could not install package 'Microsoft.OData.Edm 6.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by TonyHenrique** [comment]
`Could not install package 'Microsoft.OData.Edm 6.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by Abenezer** [comment]
me 2

**Comment by object** [comment]
This should work in the version 5 that uses .NETStandard 2.0.
