### ISSUE TITLE
Supporing .NET 4.0

### ISSUE THREAD

**Issue by daeyeonjoo** [object/Simple.OData.Client#334]
Hi.
According to your description, your package is supporting .NET 4.0.
But I can 't because your package doesn't have assemblies for .NET 4.0"
The below text is a part of error messages from (Simple.OData.V3.Client).

`" the package does not contain any assembly references or content files that are compatible with that framework"`

Of Simple.OData.Client, I can install, but it causes dependency error (System.Runtime, System.Threading.Task, System.Net.Http).

`2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3268: The primary reference "D:\GEPAClient\DataLayer\bin\Debug\GEPADataLayer.dll" could not be resolved because it has an indirect dependency on the framework assembly "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "D:\GEPAClient\DataLayer\bin\Debug\GEPADataLayer.dll" or retarget your application to a framework version which contains "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
`

Could you fix this?

**Comment by object** [comment]
Hi,
If you want to use it with .NET 4.0 you should be using Simple.OData.Client NuGet package as you did. From your error message I get an impression that there is a conflict with other DLL (GEPADataLayer) that references different version of System.Net.Http. You may try fixing it by specifying assemblyBinding in your application app.config (a similar problem is described here: http://stackoverflow.com/questions/18370360/could-not-load-file-or-assembly-system-net-http-primitives-located-assemblys-m).

**Comment by daeyeonjoo** [comment]
I read the article and fixed the problem.
GEPADataLayer uses Simple.OData.Client and Simple.OData.Client uses them.
So I added four packages listed below from Nuget to all projects which is using GEPADataLayer assembly.
    Microsoft.Bcl
    Microsoft.Bcl.Build
    Microsoft.Bcl.Async
    Microsoft.Net.Http

It was very helpful.
Thanks :D
