### ISSUE TITLE
Credentials are "lost" in batch request

### ISSUE THREAD

**Issue by vladascibulskis** [object/Simple.OData.Client#338]
In my web application I'm using Forms authentication. User is authenticated against Windows and impersonation context is created so that all the code would process under this users account. In this impersonation context I'm creating BatchClient as follows:

    Log.Debug($"Impersonating as user: {WindowsIdentity.GetCurrent().Name}");
    var clientSetting = new ODataClientSettings("some url");
    clientSetting.Credentials = CredentialCache.DefaultCredentials;
    this.batchClient = new ODataBatch(clientSetting);

Log entry shows correct impersonated user, but when this batch requests is executed I see that OData backend receives request as IIS application pool user running the web app, instead of user who authenticated and whose credentials should have been used.

**Comment by vladascibulskis** [comment]
After further investigation of the issue, it appears to be related to Asp.Net impersonation context rather than directly to OData client. After reconfiguring ASP.Net as described in following article:
https://msdn.microsoft.com/en-us/library/ms229553(v=vs.110).aspx it works now.

**Comment by object** [comment]
Thank you for the update. Good to know it worked eventually.
