### ISSUE TITLE
Modify data only to single column 

### ISSUE THREAD

**Issue by RajeshwariML** [object/Simple.OData.Client#342]
Hi,

I need to update the data to Microsoft Dynamics Nav using OData Service in Xamarin Project.

Scenario : Only one column  is writable in the page and  renaming fields are read only.

Please share me the sample code for this.  I am new to OData service.

**Comment by object** [comment]
Sorry, I didn't fully understand your scenario. Can you first check out the project wiki pages, in addition I advise you to browse various project tests (it has several hundreds covering various scenarios).
