### ISSUE TITLE
Ignore properties

### ISSUE THREAD

**Issue by richardalmonte** [object/Simple.OData.Client#345]
Hi,

I'm using Simple.OData.Client (4.24.0.1) on a Xamarin.Forms (4) project and the "NotMapped" attribute is not available. How can I exclude some properties of my Model class when retrieving/sending data from/to my OData service?

Where can I find documentation or any info of the available features as Attributes? 
Thanks
@object

**Comment by beforeyousreejesh** [comment]
You can make use of IgnoreUnmappedProperties in ODataClientSettings. Which will handle with both properties decalred in your model but not present in the Service model(EdmModel/Metadata) and properties present in the service model(EdmModel/Metadata) but not decalred in your model.

**Comment by object** [comment]
Thank you for the answer, @beforeyousreejesh.
