### ISSUE TITLE
Guid passed in as string

### ISSUE THREAD

**Issue by devkeydet** [object/Simple.OData.Client#346]
When I pass a guid as a string in .Key("AEA6C1D8-ABD3-46E6-8023-17FDE9D66B85"), it is represented like so in the actual request:
baseruri/entity(%27AEA6C1D8-ABD3-46E6-8023-17FDE9D66B85%27)

However, OData v4 requires it to look like:
baseruri/entity(AEA6C1D8-ABD3-46E6-8023-17FDE9D66B85)

So I get a BadRequest.  Is there a way to tell .Key() to not wrap with %27?

**Comment by phatcher** [comment]
@devkeydet Have you tried passing it in as a Guid e.g. .Key(Guid.Parse("AEA6C1D8-ABD3-46E6-8023-17FDE9D66B85")

**Comment by object** [comment]
Hi and sorry for the late response.

I added some tests to the project to investigate what's happening and as long as you are passing a key as GUID (not as string), in OData V4 it should correctly format it. E.g.:

var cmd = client.For&lt;TypeWithGuidKey&gt;().Key(Guid.NewGuid()).GetCommandTextAsync().Result();

produces in OData V3:
TypeWithGuidKey(guid%2729ab73c1-a6b9-4638-8430-e4184d8c6dfb%27)

produces in OData V4:
TypeWithGuidKey(74230728-9333-424b-b128-d7953aa08a43)

Hope this helps.
