### ISSUE TITLE
ExpressionFromFunction - Execution fails

### ISSUE THREAD

**Issue by nrusitska** [object/Simple.OData.Client#356]
When I create a ODataExpression with ExpressionFromFunction the execution fails. 
`var functionExpression = ODataDynamic.ExpressionFromFunction(
       "myFunctionName",
       "myTarget",
       new object[] { argument });`

If a query is executed the formatting fails at ODataExpression.FormatCallerReference()
(_functionCaller.Reference is null)

**Comment by nrusitska** [comment]
I've created a pull request that fixes this #358

**Comment by object** [comment]
Released in 4.25.1.
