### ISSUE TITLE
 Request executes before BeforeRequest handle completes

### ISSUE THREAD

**Issue by TimesliceTechnologies** [object/Simple.OData.Client#364]
Using V 4.25.2 in a Xamarin Forms Android client using a PCL.

I use ODataClientSettings to specify a handler for BeforeRequest and for AfterResponse.  Both are flagged as async methods.  When I make a request (POST) BeforeRequest gets invoked, however the actual request doesn't wait until BeforeRequest completes.  Example - if I place a single await Task.Delay(5000) in BeforeRequest, my expectation is that the client will not continue and execute the request until the delay in BeforeRequest is complete and BeforeRequest handler returns.  BeforeRequest definitely executes as does AfterResponse. However the request simply doesn't wait for BeforeRequest to finish.  Given the Task.Delay(5000) example, the event order I have logged is:

1. Client is called: var rslt = await client.For<HSOshow>("HSOshows").FindEntriesAsync();
2. BeforeRequest starts (all it does is:  await Task.Delay(5000); )
3. client seems to execute the query immediately without waiting, gets the data from server.
4. AfterRequest starts
5. client finishes and returns its result
6. BeforeRequest ends after the 5 second delay.

It seems that OdataClient is not **awaiting** on BeforeRequest before continuing to run its FindEntriesAsync query.

Am I missing something possibly?
My objective is not to create a delay, but to acquire some data to add to the request headers.  This can take some time.  I'm  just using Task.Delay() to simulate that in the above scenario.

Feels like a bug, or possibly something boneheaded on my behalf.  
Hope you can clarify this.  Here are a few snippets to provide some detail:

**OdataSettings:**
`            var clientSettings = new Simple.OData.Client.ODataClientSettings
            {
                RequestTimeout = new TimeSpan(0, 0, 30),
                BaseUri = new Uri(ServiceURL),
                BeforeRequest = OnBeforeRequest,
                AfterResponse = OnAfterResponse
            };
            //Create the Odata client
            client = new ODataClient(clientSettings);`

**BeforeRequest handler:**
`        private async void  OnBeforeRequest(HttpRequestMessage requestMessage) 
        {
            Debug.WriteLine(DateTime.Now.ToString("HH:mm:ss") + "START OnBeforeRequest.");
            await Task.Delay(5000);
            Debug.WriteLine(DateTime.Now.ToString("HH:mm:ss") + "END OnBeforeRequest." );
        }`

**After Response handler:**
`private async void OnAfterResponse(HttpResponseMessage responseMessage)
        {
                Debug.WriteLine("START OnAfterResponse: " + responseMessage.StatusCode.ToString());
        }`

**The client query:**
`var rslt = await client.For<show>("shows").FindEntriesAsync();`

**Comment by object** [comment]
This is weird indeed. The request execution logic is in Http/RequestRunner.cs, here's a code snippet:

```
                httpConnection = _session.Settings.RenewHttpConnection
                    ? new HttpConnection(_session.Settings)
                    : _session.GetHttpConnection();

                PreExecute(httpConnection.HttpClient, request);

                _session.Trace("{0} request: {1}", request.Method, request.RequestMessage.RequestUri.AbsoluteUri);
                if (request.RequestMessage.Content != null && (_session.Settings.TraceFilter & ODataTrace.RequestContent) != 0)
                {
                    var content = await request.RequestMessage.Content.ReadAsStringAsync().ConfigureAwait(false);
                    _session.Trace("Request content:{0}{1}", Environment.NewLine, content);
                }

                var response = await httpConnection.HttpClient.SendAsync(request.RequestMessage, cancellationToken).ConfigureAwait(false);
                if (cancellationToken.IsCancellationRequested) cancellationToken.ThrowIfCancellationRequested();

                _session.Trace("Request completed: {0}", response.StatusCode);
                if (response.Content != null && (_session.Settings.TraceFilter & ODataTrace.ResponseContent) != 0)
                {
                    var content = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    _session.Trace("Response content:{0}{1}", Environment.NewLine, content);
                }

                await PostExecute(response).ConfigureAwait(false);
                return response;

```
BeforeRequest runs inside PreExecute. Can you compile the library from sources and debug? Does this happen when if you try on Windows? What if you replace Task.Delay with Thread.Sleep?

**Comment by TimesliceTechnologies** [comment]
In the code snippet I notice that PreExecute(httpConnection.HttpClient, request); is called without await.  I'm no expert with async/await, but shouldn't this be using await?  I see that you do use await at the end of requestrunner when you call PostExecute.  
IE: 
`await PostExecute(response).ConfigureAwait(false);` 

Before I dig deeper, I'd appreciate your review of whether PreExecute(httpConnection.HttpClient, request) should be prefixed with **await** in your code snippet above. 
IE:
`await PreExecute(httpConnection.HttpClient, request);`
instead of just:
`PreExecute(httpConnection.HttpClient, request);`

I haven't tried this with Windows, but can confirm the same problem running the same code in iOS.  Note that I'm using Xamarin Forms and all this stuff is in a PCL.  Thread.Sleep() is not supported in PCL, so that's not something I can try.  I see some other users have posted similar issues previously regarding unexpected problems with BeforeRequest support, that don't seem to have been fully resolved.

I appreciate your very quick response to my post btw.

**Comment by object** [comment]
PreExecute is void, it doesn't return Task therefore it can't be awaited. The reason I await PostExecute is because internally it calls async method and awaits for it.

**Comment by object** [comment]
So I appreciate you try it on Windows and check how it works.

**Comment by TimesliceTechnologies** [comment]
Back to you shortly with results after testing in windows…

**Comment by TimesliceTechnologies** [comment]
Tested in regular Windows - after getting nugget package references installed with precise versions.  Not entirely sure what that's about, other than Nuget installed 6.0 of MS Odata, but apparently Client needs 6.15.  Anyway...

Same issue, and no doubt because PreExecute cannot be awaited.  Thread.sleep works but of course that's to be expected..

Instead of using "await Thread.Delay" let me  better describe what I'm trying to accomplish.  I may have to re-evaluate this if we can't make PreExecute awaitable.

My app is using bearer token authentication with short lived tokens.  Before I send a request to the resource server (IE Inside PreExecute), I check to see if my current auth token is expired.  If the token is still valid, I add it to the request Authorization header and carry on.  If the token is expired, then I want to get a new token from the Authorization server and after getting the new token use that new token in the request Authorization header.  I'm doing this inside the PreExecute handler (IE: BeforeExecute).  To get a new auth token, I make an async call using a regular HTTPclient eg: AuthToken=Await GetAuthTokenAsync().

This is where the issue is.  My call to GetAuthToken is awaitable and may take a few seconds to get the token (or timeout of course).  I was simply using Task.Delay() to simulate the GetAuthTokenAsync call for the purpose of debugging this issue.

PreExecute seems like an ideal place to do this centrally without having to do the AuthToken check/refresh inside every method that invokes an Odata.Client query .

Fundamentally, I need to centrally handle 401 Unauthorized exceptions and then update the auth token and retry the original call.  I'm trying to ensure I have a good auth token BEFORE the initial call and I also need to handle / retry a request if I get a 401 after the call.

I'm open to suggestions on the best way to handle this.  Basically, ensure I have a valid token before a call, and if I get a 401 after a call, then refresh Auth token and retry (once).

BTW, Great to have your very quick assistance with this.  Overall, this is a great package.

**Comment by TimesliceTechnologies** [comment]
Would there be a problem with making PreExecute method return a task instead of void?  This would make it awaitable and add support for making awaitable calls within PreExecute.

**Comment by object** [comment]
Thank you for a detailed explanation. I will investigate this further, making PreExecute awaitable is of course an option but first I need to understand why this happens in first place (not everything must be awaited).

**Comment by TimesliceTechnologies** [comment]
In the bigger picture the objective is to (easily) handle Oauth authentication using bearer tokens.
Specifically the need to add the token to calls that are protected on the resource server.  The token must be refreshed from time to time when it expires.  

In my case I simply go and get a new token from the Auth server if I get a 401 Unauthorizd exception.  I don't see a nice clean pattern that makes this simple.  

Consider a library with 50+ various Odata.Client calls that retrieve data from a resource server.  Of those 50 calls, some are protected and require the bearer token in the header.  Further more, some methods have different user claim requirements (roles).  The client must send a valid bearer token, but must also have sufficient privileges to access the resource.  A 401 can result from an expired/missing token or a user that doesn't have sufficient rights to the server resource.

In general, we expect a 401 Unauthorized exception if the token isn't provided, has expired, or user doesn't have sufficient privileges.  

Currently it seems I have to trap that in each of the 50 methods, grab a new token and then retry the request with the new token assuming the 401 is because of an expired token and not insufficient user rights.  

I suppose I could do the token refresh in the PostExecute rather than catching in each individual method, but I probably still need to re-call the original Odata.Client call with the refreshed token.  Caution is required however to make sure that one doesn't enter an infinite loop of Get Auth Token / Retry.  The token may in fact be valid but the user simply doesn't have sufficient privileges in some cases due to their Role / Claims.  In this case (IE: Token is valid, but user has insufficient rights to the resource), the retry should not be performed.

I'm think out loud a bit.  I suspect you understand what I'm trying to accomplish and I'm sure this is an extremely common scenario.  IE: Bearer token authentication with refresh, Protected API methods, Various permission levels to different methods on the resource server.

A nice clean pattern for handling bearer tokens, refresh token, retry upon the first "Unauthorized" exception would be helpful to many users.

I look forward to your thoughts.  I'll continue pounding away at this while you cogitate on a solution.
Again, thanks for your assistance...

**Comment by TimesliceTechnologies** [comment]
For the benefit of others working with Oauth Bear tokens, here's the basic routine I use for wrapping the call to Odata.Client in order to centralize all Simple.Odata.Client requests in a single routine and to automatically refresh the authorization token and consolidate various exceptions that might occur like Timeout.

Note that a timeout typically throws a TaskCanceled exception by OdataClient and not a Timout Exception.  I have defined several Exception types that consolidate the possible errors. 

Reference to "client" in the snippets refer to the Simple.Odata.Client instance within the class.  Authorization tokens (an Oauth2 JWT bearer token) are obtained from the Authorization server using a regular HTTPclient which I have not documented here.  I haven't provided the complete class, but these are the important snippets.


**Define a handler for Simple.Odata.Client BeforeRequest to add the bearer token to every request:**
Make sure you reference this in your OdataSettings when instantiating the client.

```
        private void OnBeforeRequest(HttpRequestMessage requestMessage)
        {
            // PreExecute in Odata.Client is void so cannot be awaited.  DO NOTcall async methods here.
            //Add the current authorization token if it exists
            if (CurrAuthToken.IsValid)
                requestMessage.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", CurrAuthToken.Token.access_token);
        }
```


**Delegate and OdataRequestRunner:**
```
    public delegate Task<object> OdataClientCallDelegate();

        async public Task<object> OdataRequestRunnerAsync(OdataClientCallDelegate OdataClientCall)
        {
            object rslt;
            int Tries = 0;
            retry:
            try
            {
                Tries += 1;
                await CheckAuthTokenAsync(Tries > 1).ConfigureAwait(false); //Refresh current authorization token if not valid, Force a refresh on 2nd attempt.
                rslt = await OdataClientCall();
            }
            catch (Simple.OData.Client.WebRequestException ex) when (ex.Message == "Unauthorized")
            {
                if (Tries < 2) goto retry;
                throw new MYnotAuthorizedException(innerException: ex);
            }
            catch (MYauthorizeException) { throw; } //Problem connecting to Authorization server trying to get an Authorization Token.
            catch (Exception ex) when (ex is TimeoutException || ex is TaskCanceledException) { throw new MYtimeoutException(innerException: ex); } //Timeout
            catch (Exception ex) { throw new MYexception(innerException: ex); } //Unexpected or general exception
            return rslt;
```

**Usage:** 
A typical GET request can be sent throught the OdataRequestRunnerAsync as follows.
The actual request is the lambda and the result is cast to the expected result:
```
async public Task<List<Record>> GetRecordsAsync()
        {
            var objRslt = await OdataRequestRunnerAsync(async delegate ()
            {
                var Items = new List<Record>();
                try
                {
                    var rslt = await client.For<Record>("Records").FindEntriesAsync().ConfigureAwait(false);
                    Items.Clear();
                    Items.AddRange(rslt.ToList());
                }
                catch (Exception ex) { throw (ex); }
                return Items;
            });
            return (List<Record>)objRslt;
        }
```
Hope that helps anyone working with bearer tokens.
In general wrapping the call to Odata.Client with the above request runner may help you better handle timeout and other exceptions within a single routine.

Comments and improvements welcome...

**Comment by phatcher** [comment]
@object Any objections to me picking this up as well - I have similar issues with OAuth and making PreExecute async seems to be the way to go.

We then add OnBeforeRequestAsync and OnAfterRequestAsync handler methods which would allow async callouts by user code. Advantage of this is that it doesn't break the existing API and can just be used by clients who need the async behaviour.

**Comment by object** [comment]
Thank you for the initiative, Paul. Of course just go ahead.

**Comment by phatcher** [comment]
@TimesliceTechnologies I've extended ODataClientSettings with BeforeRequestAsync/AfterRequestAsync on the v4 branch.

There is a simple test, but can you build/test with your scenario please

**Comment by TimesliceTechnologies** [comment]
I'm on a different project and won't be able to return to this for a month or so unfortunately.  I look forward to working with this however and hope to provide some feedback as soon as time permits.

**Comment by object** [comment]
PreExecute is awaitable in 5.3, I also added BeforeRequestAsync/AfterResponseAsync, as @phatcher suggested.
