### ISSUE TITLE
Simple.OData.Client.UnresolvableObjectException: Association [Location] not found

### ISSUE THREAD

**Issue by chinna1023** [object/Simple.OData.Client#368]
I was trying to automate below OData call from Sample OData calls mentioned [`here`](http://www.odata.org/odata-services/)

OData call:
http://www.odata.org/odata-services/

code:
 ```
var location = await client
                .For<Airport>()
                .Key("KSFO")
                .NavigateTo<Location>()     
                .FindEntryAsync();  

```
Error:
Simple.OData.Client.UnresolvableObjectException: Association [Location] not found. 

Here are the classes:
 ```
class Airport
    {
        public string IcaoCode { get; set; }
        public string IataCode { get; set; }
        public string Name { get; set; }
        public AirportLocation Location { get; set; }
    }

  class Location
    {
        public class LocationCity
        {
            public string CountryRegion { get; set; }
            public string Name { get; set; }
            public string Region { get; set; }
        }

        public string Address { get; set; }
        public LocationCity City { get; set; }
    }

```

**Comment by object** [comment]
Hi,

"Location" is a regular property, not a navigational one, so you can't navigate to it. This code works:

            var airport = await client
                .For<Airport>()
                .Key("KSFO")
                .FindEntryAsync();
            Assert.Equal("San Francisco", airport.Location.City.Name);
