### ISSUE TITLE
Support for CSDL version 1.1

### ISSUE THREAD

**Issue by abiratsis** [object/Simple.OData.Client#370]
Hello everyone,

We have a Dynamics 2011 ODATA service which is based on CSDL 1.1 does Simple.OData.Client support it? If not is there any work around by using another client?

This is the XML response header

`<?xml version="1.0" encoding="utf-8"?>
<Schema Namespace="Microsoft.Crm.Sdk.Data.Services" xmlns="http://schemas.microsoft.com/ado/2007/05/edm">`

Thank you in advance
Alex

**Comment by object** [comment]
Hi,
Simple.OData.Client supports OData protocols versions 1 to 4 (http://www.odata.org/documentation/). So the question is whether Dynamics 2011 has a proper support for OData? Can you compare its metadata with the metadata of references OData services here (http://www.odata.org/odata-services/)? As long as Dynamics can expose data according to OData protocol of either of these protocol versions, you should be fine. If not, then it's not an OData service in a formal sense and the library can't be used to consume its data.

Hope this helps

**Comment by abiratsis** [comment]
Hello Vagif and thank you, 

Yes it helps a lot although I need still to be sure if provided OData version of Dynamics 2011 is at least 1.0.
