### ISSUE TITLE
Can't parse/deserialize property type from @odata.type

### ISSUE THREAD

**Issue by neitsab94** [object/Simple.OData.Client#374]
Hi,

Thank you for your Simple oData library !
We have a problem parsing the property "@odata.type" sent from our oData service.
When I query the service from postman, the "@odata.type" is visible, but I can't find a way to parse it and use it from my code.
Does the Simple oData deserializer take this json propery into account ?

Thanks,
Bastien

**Comment by object** [comment]
Sorry for the late response. Yes, it's possible to obtain the value of @odata.type and other annotations if you set the ODataClientSettings.IncludeAnnotationsInResults property. Then you can do the following:


    class PersonWithAnnotations : Person
    {
        public ODataEntryAnnotations Annotations { get; set; }
    }
            var client = new ODataClient(new ODataClientSettings
            {
                BaseUri = _serviceUri,
                IncludeAnnotationsInResults = true
            });
            var person = await client
                .For<PersonWithAnnotations>("Person")
                .Filter(x => x.UserName == "russellwhyte")
                .FindEntryAsync();

            Assert.NotNull(person.Annotations.Id);
