### ISSUE TITLE
Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter

### ISSUE THREAD

**Issue by uuksu** [object/Simple.OData.Client#378]
Fresh project, trying to run sample code from odata.org. Throws exception when trying to fetch data with client.

```
        static void Main(string[] args)
        {
            var x = ODataDynamic.Expression;
            var client = new ODataClient("http://services.odata.org/v4/TripPinServiceRW/");
            var people = client.For(x.People).FindEntriesAsync().Result;
        }
```

Installed latest version from NuGet (Simple.OData.V4.Client, 4.25.4).

Deep down from the stack I can see that it tries to load Microsoft.OData.Core, Version=6.15.00 and fails. From my package.config and App.config I can see that package has loaded downgraded version.

package.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Bcl" version="1.1.9" targetFramework="net452" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="net452" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net452" />
  <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="net452" />
  <package id="Microsoft.OData.Core" version="6.0.0" targetFramework="net452" />
  <package id="Microsoft.OData.Edm" version="6.0.0" targetFramework="net452" />
  <package id="Microsoft.Spatial" version="6.0.0" targetFramework="net452" />
  <package id="Simple.OData.V4.Client" version="4.25.4" targetFramework="net452" />
</packages>
```
App.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.28.0" newVersion="2.2.28.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.OData.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.OData.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Spatial" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Workaround for this seems to be manually updating Microsoft.OData.Core to 6.15.0 and then everything seems to be working fine. I think problem is that in package configuration you have set dependant version to libraries too low and it fetched lowest possible version when my NuGet Depedency behavior is set to Lowest.

**Comment by object** [comment]
Thanks for the feedback. The library references the correct version of OData V3 lib (6.15), it's the nuspec file that specifies the range between 6 and 7. I'd say this should be a task of the package resolver to fetch the matching version within the supported range. If I change the range from [6,7) to [6.15,7) then it won't be possible to use OData 6.0 in case it's really needed (with adjusted bindingRedirects).

So I am not really I should specify the currently used ODataLib version instead of the supported range. Yes, it is inconvenient to manually update packages if it fails but in practice the library supports the whole range of versions (via proper bindingRedirects).

**Comment by object** [comment]
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7. Please check it out.

**Comment by onslaughtq** [comment]
I'm currently having this issue with the latest OData libraries and v5.2.1 of Simple.OData.Client.  Working on trying to figure it out...

**Comment by object** [comment]
@onslaughtq 
That's very strange because they should be copied from the NuGet package. If you can extract a sample that reproduces the problem, I can take a look.

**Comment by onslaughtq** [comment]
[ODataIssue.zip](https://github.com/object/Simple.OData.Client/files/2084339/ODataIssue.zip)

Here's a sample solution with the problem.  It appears the issue is that, when Simple.OData.Client is part of library project, the adapters don't get put into the main project's bin folder, because they are being loaded dynamically at runtime. I'm not sure why this wasn't an issue with previous versions though.

**Comment by object** [comment]
Thanks! I will check this out.

**Comment by object** [comment]
Actually this issue can not be resolved on the library level, it's a client's concern. ODataClient doesn't have a hard reference to either of adapters, its NuGet package includes references to both V3 and V4 OData adapters, but in case of transitive reference the client needs to explicitly include necessary references.
 In your particular case the best is to add Simple.OData.V4.Client NuGet package to both library and the main application. This should solve the problem.

**Comment by frankfajardo** [comment]
> Actually this issue can not be resolved on the library level, it's a client's concern. ODataClient doesn't have a hard reference to either of adapters, its NuGet package includes references to both V3 and V4 OData adapters, but in case of transitive reference the client needs to explicitly include necessary references. In your particular case the best is to add Simple.OData.V4.Client NuGet package to both library and the main application. This should solve the problem.

I think this needs to be mentioned in the Nuget Readme or the Github Readme.
