### ISSUE TITLE
Can I ignore some properties using the fluent API?

### ISSUE THREAD

**Issue by olvd** [object/Simple.OData.Client#38]
Hi,

I use the client's fluent API with the same POCOs used to create my entity framework DbContext and data service.
Some classes have properties that are not persisted (decorated with [NotMapped] for EF to ignore).

Is there anyway I can instruct Simple.OData.Client to ignore them too and avoid [Simple.OData.Client.UnresolvableObjectException] {"No property or association found for XXX" } on insert?

Thank you

**Comment by olvd** [comment]
Hi,
Would it be possible to also add an IgnoreUnresolvableObjectException option to the ODataClientSettings?
I have a case where I cannot decorate my entities properties with the [NotMapped] attribute so it would be convenient to have such an option.
Thanks

**Comment by object** [comment]
This seems to be a reasonable proposition. I will check what consequences it might have and let you know.

**Comment by object** [comment]
Implemented in version 4.3.0.
