### ISSUE TITLE
Bad request - $metadata appended to retrieve action

### ISSUE THREAD

**Issue by martijnvdbranden** [object/Simple.OData.Client#381]
Hi,

My apologies is if this is a non-issue. I'm using the OData client from .NET as follows:

```
var contacts = await client
.For<Contact>()
.FindEntriesAsync();
```

I'm expecting an ` IENumerable<Contact>` as a result. However, whatever syntax I try,
the client library seems to call my OData endpoint like:

../api/data/v8.2/contacts/$metadata

This throws an exception:

_The request URI is not valid. Since the segment 'contacts' refers to a collection, this must be the last segment in the request URI_

Many thanks,

Martijn

**Comment by martijnvdbranden** [comment]
My apologies for submitting this as an issue- this was a configuration issue. Thanks for the awesome library!

**Comment by stevenb9** [comment]
> My apologies for submitting this as an issue- this was a configuration issue. Thanks for the awesome library!

I'm having the same issue, could you please share what configuration issue caused this $metadata to append?
