### ISSUE TITLE
Question: What is the proper way to get 200 response with body on UpdatedOdataResult<T> instead of the 204 response?

### ISSUE THREAD

**Issue by Makison** [object/Simple.OData.Client#383]
Hi,
I figured out that I can receive 200 response with content if I add
Prefer: return=representation 
to the requst header manually.

Does Simple.Odata.Client has some configuration to make it return content on UpdatedOdataResult response?

Thanks!

**Comment by object** [comment]
Sure. If you specify resultRequired parameter (set it to "true"), the library will add "return=representation" header.

Hope this helps.

**Comment by Makison** [comment]
Thank you,
missed that point, 
but I'm using ExecuteAsSingleAsync to call function, and looks it doesn't have such overload.

Thanks!

**Comment by Makison** [comment]
Never mind,
my bad, ExecuteAsSingleAsync by default has enabled resultRequired.
Works like a charm!

Thank you!

**Comment by object** [comment]
Good to know it worked for you!
