### ISSUE TITLE
Simple OData Client only accepts up to 3 logical condition in Filter method?

### ISSUE THREAD

**Issue by DennisRodriguez** [object/Simple.OData.Client#388]
Hi,

I'm trying to filter my result using the Filter method, but it seems to only accept 3 logical condition and if I pass 4 conditions I always get a Not Found error.

`var filter = new ODataExpression<terminal>(f => f.ter_number == t.ter_number);
filter = filter && new ODataExpression<terminal>(f => f.ter_comcode == t.ter_comcode);
filter = filter && new ODataExpression<terminal>(f => f.ter_strcode == t.ter_strcode);
filter = filter && new ODataExpression<terminal>(f => f.ter_type == "2");`

If I remove any of the 4 conditions I get a successful result.  I'm using 4.25.5 that support both V3 and V4 and my OData Service uses OData V3.

What could be the reason why it behave that way?

**Comment by object** [comment]
Hi Dennis,
I suspect this is a server rather than a client issue. What happens if you manually generate OData URL and execute in the browser? If you get a correct result than it's a client but then it would be useful to compare that URL with what is generated by the library.

**Comment by DennisRodriguez** [comment]
Hi @object 

I was able to get the result when I execute the following filter in the browser.

> http://192.168.254.12:8086/terminals?$filter=(ter_number eq '001' and ter_comcode eq 'GT' and ter_strcode eq 'HO' and ter_type eq 2)

I have changed the data type of ter_type back to sbyte since it is sbyte originally, I just thought that changing it to varchar would correct the issue.

Executing the following code in the Client:
`var filter = new ODataExpression<terminal>(f => f.ter_number == t.ter_number);
                                            filter = filter && new ODataExpression<terminal>(f => f.ter_comcode == t.ter_comcode);
                                            filter = filter && new ODataExpression<terminal>(f => f.ter_strcode == t.ter_strcode);
                                            filter = filter && new ODataExpression<terminal>(f => f.ter_type == t.ter_type);`

Gives me a NotFound error as seen below.

> {"Not Found"}
    Code: NotFound
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: null
    Message: "Not Found"
    RequestUri: {http://localhost:8086/terminals(ter_number='001',ter_comcode='GT',ter_strcode='HO',ter_type=2)}
    Response: ""
    Source: "Microsoft.Threading.Tasks"
    StackTrace: "   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)\r\n   at Simple.OData.Client.FluentClientBase`1.<RectifyColumnSelectionAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at SyncClient.ViewModels.SyncViewModel.<Download>d__40.MoveNext() in C:\\Users\\bluegates\\Desktop\\Source Code\\Bluesgates\\SyncClient\\ViewModels\\SyncViewModel.cs:line 389"
    TargetSite: {Void ThrowForNonSuccess(System.Threading.Tasks.Task)}

Attached is the image of the return value in the browser
![result](https://cloud.githubusercontent.com/assets/18585718/24441539/8ded7d14-148c-11e7-97d8-2b6c16db17bd.png)

**Comment by DennisRodriguez** [comment]
Hi Vagif,

After encountering the same problem, but with only 2 conditions I started to doubt that the issue I am facing has something to do with the composite key which is actually the case.

After correcting my service controller to support composite key the filter now works fine.
But there is still one thing that kept me wondering. Why filter works in the browser when executed directly but not in my client using Simple OData Client? Could it be that  Simple OData Client still uses the key underneath if possible to filter the data? Because I want to believe that this is not the case with the OData Service using filter? Otherwise my filter in the browser should not work also,

**Comment by object** [comment]
Hi Dennis,
Your assumption is correct. Simple.OData.Client uses the key wherever possible so apparently this is what caused the problem. It's great that you investigated it so thoroghly and found the solution.

**Comment by DennisRodriguez** [comment]
Hi Vagif,

Thank you for your input. 
This is really a great tool.
