### ISSUE TITLE
Save Entity with Navigation in one go

### ISSUE THREAD

**Issue by DennisRodriguez** [object/Simple.OData.Client#389]
Hi,

Is it possible to update/insert a entity with navigation properties in one go?
Basically I have 2 OData Service. 1 running in the cloud and one in the local area network.
The purpose is to grab the MySQL Data from the cloud and save it to the local area network.

Let's say I have this to get the records from the cloud

`var userClient = await cloud.For<employee_useraccesslevel>().Expand(e => new { e.employee_useraccesssettings }).FindEntriesAsync();`

Now what I need is to be able to save both employee_useraccesslevel and employee_useraccesssettings in one go or in the same transaction.

I thought by simply running the below code would save both of them as Simple OData Client would do the saving of navigation property internally.
`foreach (employee_useraccesslevel ua in userClient)
{
var userUpdate = LAN.For<employee_useraccesslevel().Key(ua.code_accesslevel).Set(ua).UpdateEntryAsync();
}`

But it doesn't seems to be the case. Is this possible with Simple OData Client? I had similar problem with this concern [How can I insert entity with navigation properties](https://github.com/object/Simple.OData.Client/issues/281) Unfortunately the thread didn't get an answer so I am assuming that saving an entity with navigation property all at once is not yet supported in Simple OData Client?

**Comment by TonyHenrique** [comment]
I also have this doubt.

**Comment by object** [comment]
Please look at my answer in issue #390. Deep updates/upserts are not currently supported by OData, deep inserts are supported but not implemented by the library. However you can use OData batch operations to achieve the same in many cases.

**Comment by DennisRodriguez** [comment]
Hi Vagif,

Thank you for your answer, but how I understand batch operations is that you can send multiple commands in one HTTP request and has nothing to do with transaction, so my question is if let's say I send 2 inserts 1 for parent and 1 for the details (this is the order of my batch command) what happen if my parent insert succeeded and the child failed? Should I assume that my parent record will be saved? Also, if my parent command fails will it still execute the child? Logically speaking if my first command fails it should not continue to execute the rest of my commands am I right?

**Comment by object** [comment]
Hi Dennis,

OData batches may be treated as transactions but this is completely up to the server. For example, Microsoft WCF Data Services (one of Microsoft's OData implementations) when using Entity Framework on the server implements transaction behavior so all commands from the HTTP payload are cancelled if one fails. Pleast have a look at this page for more information: https://damienbod.com/2014/08/14/web-api-odata-v4-batching-part-10/

**Comment by DennisRodriguez** [comment]
Hi Vagif,

While the example is for V4 and I am using V3, but luckily the example was excerpted from V3,

Although I have one problem with the sample code provided from V3 EntityFrameworkBatchHandler class. This part of the code will not run as SetContext method do not exist in HttpRequestMessage class.

`foreach (HttpRequestMessage request in changeSet.Requests)
                {
                    request.SetContext(context); 
                }`

Would you be kind to take a look of the sample provided if it really works and what I am missing?

Additionally,
Let's say I took the batching path and made the changes provided in the link what changes do I need to make in Simple OData Client? Or I just need to follow your batch example?

**Comment by object** [comment]
I don't remember out of my head these details (not working with EF or Web API at the moment) but here's one of discussions about similar issues: http://stackoverflow.com/questions/14349557/getting-httprequest-context-in-self-hosted-webapi

And regarding client application code: look at plenty of OData batch tests in Simple.OData.Client source code. They should help.

**Comment by DennisRodriguez** [comment]
Hi Vagif,

Sorry for being dumb, but I'm not really quite sure how is that related to my concern. Basically this service will be hosted in IIS (Web Hosted). Additionally, it does not mentioned why SetContext method is missing from HttpRequestMessage nor give an alternative solution. The issue there doesn't seem to be resolved as well. 

Basically the SetContext method is mark with Red Line and wont compile/build due to the following error: 

> Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	CS1061	'HttpRequestMessage' does not contain a definition for 'SetContext' and no extension method 'SetContext' accepting a first argument of type 'HttpRequestMessage' could be found (are you missing a using directive or an assembly reference?)	iPOSServiceV3	C:\Users\bluegates\Desktop\Source Code\Bluesgates\iPOSServiceV3\Extension\EntityFrameWorkBatchHandler.cs	88	IntelliSense	Active

As for the batch sample were you referring to [Batch requests](https://github.com/object/Simple.OData.Client/wiki/Batch-requests)?

Sorry for taking too much of your time, but getting this batch request to work as you have explained would finally solve all my problems.

**Comment by object** [comment]
Hi Dennis,

When it comes to Simple.OData.Client batch examples, I meant following ones:
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.IntegrationTests/BatchODataTests.cs
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Tests.Net40/BatchTypedTests.cs
https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.Tests.Net40/BatchTests.cs

And I am afraid I can't help you with setting up request handling on the server site. I am too far from it right now. My library is dealing with building client requests, and servers handle batches differently. I was using batch implementation using WCF Data Services and Entity Framework OData provider (prior to Web API 2), I suggest you use StackOverflow to find a solution.

**Comment by DennisRodriguez** [comment]
I think I now understand why you gave that link. So the SetContext is no longer supported in the new version? I have downloaded the sample project and the code looks fine without the error using the .Net Framework 4.5, but I'm currently using 4.6.1.

Could it be replaced by doing `request.Properties["Batch_DbContext"] = context;`?
This is my first time working on OData and I am a newbie in Web Api in general.

**Comment by DennisRodriguez** [comment]
Thank you for those links

**Comment by object** [comment]
It _may_be_ possible to use request.Poperties but I didn't check it and in that SO discussion it was not recommended by principal reasons. So I'd explore other possibilites but again I am not working with Web API, can't help you there.

**Comment by DennisRodriguez** [comment]
Hi Vagif,

You have already given me enough help. I know this is no longer part of your library. Will ask my concern in Stockoverflow as you have suggested.

Thank you for all the help. Will post the solution here once I get one.

**Comment by object** [comment]
Good luck!

**Comment by DennisRodriguez** [comment]
The HttpRequestMessageExtensions  static class actually works. 

Upon seeing this [HttpRequestMessageExtension](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Http/HttpRequestMessageExtensions.cs) I know that the HttpRequestMessageExtensions class I copied should also work.

HttpRequestMessageExtensions and the EntityFrameworkBatchHandler name spaces were kind of mixed up. The latter has additional s in its name space iPOSServiceV3.Extensions instead of just iPOSServiceV3.Extension.

Sorry this is just all my fault.

**Comment by object** [comment]
Glad to know it finally worked for you!
