### ISSUE TITLE
Best way to delete a navigation property?

### ISSUE THREAD

**Issue by DennisRodriguez** [object/Simple.OData.Client#393]
Hi,

I would like to ask if there's a cleaner way to delete a navigation property without creating a controller?

I have this batch command
`var empUpdateBatch = new ODataBatch(LAN);
                                        
                                        empUpdateBatch += c => c
                                            .For<employee>()
                                            .Key(e.emp_id)
                                            .Set(e)
                                            .UpdateEntryAsync(false);
                                        empUpdateBatch += c => c
                                            .For<employee_config>()
                                            .Key(e.emp_id)
                                            .DeleteEntryAsync();
                                        empUpdateBatch += c => c
                                            .For<employee_education>()
                                            .Filter(f => f.Emp_ID == e.emp_id)
                                            .DeleteEntriesAsync();
                                        empUpdateBatch += c => c
                                            .For<employee_employmenthistory>()
                                            .Filter(f => f.Emp_ID == e.emp_id)
                                            .DeleteEntriesAsync();
                                        empUpdateBatch += c => c
                                            .For<employee_dependents>()
                                            .Filter(f => f.emp_id == e.emp_id)
                                            .DeleteEntriesAsync();
                                        empUpdateBatch += c => c
                                            .For<employee_trainings>()
                                            .Filter(f => f.emp_id == e.emp_id)
                                            .DeleteEntriesAsync();`

But deleting a navigation property on its own requires a controller, would it be possible to delete a navigation property inside its parent? I thought since I can use Expand method to query the collection/navigation property to retrieve the data, so I am thinking that it could be possible to do similar thing in delete,update and insert?

**Comment by DennisRodriguez** [comment]
Intead of the above what I would really want is to be able to delete multiple entries in navigation properties using foreignkey fields instead of primary.

**Comment by DennisRodriguez** [comment]
Ok it seems that I need to create my own version of the object without the navigation so that navigation properties will be removed automatically.

[Delete after patch](https://github.com/object/Simple.OData.Client/issues/182)

**Comment by DennisRodriguez** [comment]
I guess there is no other best way? since deletion will be by key eventually regardless whether you use filter or key.

**Comment by object** [comment]
Hi Dennis, and sorry for the late response. I am not sure what you mean by "deleting a navigation property on its own requires a controller". There is no "controller" concept in OData protocol, perhaps you mean Web API controller?
According to OData spec, in order to update or delete related entities you need to execute a series of single deletions. Even though Simple.OData.Client offers UpdateEntriesAsync and DeleteEntriesAsync methods, these are just wrappers around individual UpdateEntryAsync and DeleteEntryAsync calls to simplify code on the client side.
So I guess you are doing this correctly and there is no easier way unfortunately.

**Comment by DennisRodriguez** [comment]
Hi Vagif,

Thank you for your reply, Yes I meant Web API controller. and Yes I understand about the update and delete. Simple OData Client  will still update or delete each row using the key.

Anyways, as of now everything seems to be working fine and extending the batch operation  actually solved my problem with transactions. 

.Again thank you for this great tool I just hope that you can support the Deep Insert and Deep update soon.

Dennis
