### ISSUE TITLE
ODataClient.ClearMetadataCache() doesnt work

### ISSUE THREAD

**Issue by malichishti** [object/Simple.OData.Client#394]
HI,

 I have a requirement of forcing the metadata to be updated after specific intervals. I have tried:
`
if(expired== true)
{
       ODataClient.ClearMetadataCache();
}

await client.InsertEntryAsync("entity", data);//i expect this to call metadata first if the cache has been cleared
`
In above code it never call the metadata even if the ClearMetadataCache method has been called.

Regards,
Ali

**Comment by object** [comment]
Hi,
I tested this scenario and apparently metadata will be renewed once a new session created, i.e. you will need to create another instance of ODataClient. But the instance that is already running will continue using previously obtained metadata document. Do you have an option to renew ODataClient instance after you clear metadata cache?

**Comment by malichishti** [comment]
Hi,
 I have tried assigning null to the client and then re-initiating it but it still did not make a call for metadata.

Ali

Sent from my iPhone

On 24 Apr 2017, at 1:05 am, Vagif Abilov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I tested this scenario and apparently metadata will be renewed once a new session created, i.e. you will need to create another instance of ODataClient. But the instance that is already running will continue using previously obtained metadata document. Do you have an option to renew ODataClient instance after you clear metadata cache?

**Comment by object** [comment]
I wrote and ran the following test:

            // Use Fiddler to inspect metadata requests
            // Should read metadata prior this call
            var client = CreateClientWithDefaultSettings();
            await client.FindEntriesAsync("Products");
            // Should not read metadata prior this call
            await client.FindEntriesAsync("Products");

            ODataClient.ClearMetadataCache();
            // Should not read metadata prior this call
            await client.FindEntriesAsync("Products");

            client = CreateClientWithDefaultSettings();
            ODataClient.ClearMetadataCache();
            // Should read metadata prior this call
            await client.FindEntriesAsync("Products");

And it worked as expected: once I created a new instance of ODataClient, it requested a new copy of metadata after I invoked ClearMetadataCache.

Do you have similar code?

**Comment by malichishti** [comment]
Yes, this code works fine. It seems like i was not calling ODataClient.ClearMetadataCache(); after initialising it.
