### ISSUE TITLE
OData 'not' spacing in queries

### ISSUE THREAD

**Issue by thurfir** [object/Simple.OData.Client#395]
Hello all,

We have a concern with this OData client: from our understanding, and from what we found in the Odata v4 specifications, the 'not' operator should be followed at all times by a white space:

notExpr = 'not' RWS boolCommonExpr
RWS: Required White Space.

http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt

But, in this library's query, a '!' is turned into a 'not(..)'. The Microsoft OData library follow the mentionned rule as it is replaced by 'not (..)', but we don't like the idea of code-generated services too much so we would love to use this more (IMHO) elegant library.

**Comment by object** [comment]
Released a new NuGet package.

**Comment by thurfir** [comment]
Wow, that was incredibly fast, thanks a lot!!
