### ISSUE TITLE
DeleteEntry not working when key contains period in key value.

### ISSUE THREAD

**Issue by chinna1023** [object/Simple.OData.Client#397]
When Key value contains "." it's removing the entire key from request URI and returning 404 not found. We have a . in Key. 

 await client
                .For("Prodcut")
                .Key("Dell")
                .NavigateTo("Details")
                .Key("test.key")
                .DeleteEntryAsync();

After debugging it's removing this key if it has . in below method. is it intended? How can I fix my code?

 private string RemoveTypeSpecification(string entryIdent)
        {
            var segments = entryIdent.Split('/');
            if (segments.Count() > 1 && segments.Last().Contains("."))
            {
                entryIdent = entryIdent.Substring(0, entryIdent.Length - segments.Last().Length - 1);
            }
            return entryIdent;
        }

**Comment by object** [comment]
Hmm, since you debugged the source, can you point me to the source file with this code. I can't find this code in the branch v4 (which is the branch for stable NuGet packages).

**Comment by chinna1023** [comment]
Sorry, I was using an older version of NuGet package and after updating to the latest version it's working fine. Thanks for quick response.
