### ISSUE TITLE
I want to pass my test case when status code is 404

### ISSUE THREAD

**Issue by chinna1023** [object/Simple.OData.Client#398]
Hi,

I'm using AfterResponse to validate my status code and it's woking fine. But after that, it's still throwing WebRequestException and my test case is failing. I need to handle this in try catch and assert in catch block again for Http status code 404. Is there any way to skip this exception and pass my test?

  ```
 var cred = new ODataClientSettings()
            {
                BaseUri = new Uri(url)
            }
            cred.AfterResponse += RespHandler;
            var client = new ODataClient(cred);
            var configuration = await client
                    .For<Products>()
                    .Key("invalid")
                    .FindEntryAsync();

private static void RespHandler(HttpResponseMessage responseMessage)
        {
            if (!responseMessage.RequestMessage.RequestUri.LocalPath.EndsWith("$metadata"))
            {
                Assert.AreEqual(responseMessage.StatusCode, HttpStatusCode.NotFound);
            }
        }

Exception:
Simple.OData.Client.WebRequestException: Not Found

```

**Comment by object** [comment]
Can't you just set ExpectedException for this test? Or run the code in try/catch block? That would be the easiest.

**Comment by chinna1023** [comment]
Yes, both expected Exception and try catch working fine.  Was looking for any option to skip it avoid the exception.

**Comment by object** [comment]
The exception is a part of API contract. A call should either return valid data or raise an exception. So an API implementation can't simply suppress an exception: what should it return instead then? I think you are overcomplicating exception management in your tests. Exceptions are thrown for good reasons and usually provide essential information about what went wrong.
