### ISSUE TITLE
Choosing PUT over Patch

### ISSUE THREAD

**Issue by DennisRodriguez** [object/Simple.OData.Client#399]
Hi,

I have a problem with my update. Regardless of my PreferredUpdateMethod Simple OData always use PUT to update my model on specific records.

Below is my Model in my Client Application that uses the Simple OData Client

```
public partial class subcategory 
{
[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage","CA2214:DoNotCallOverridableMethodsInConstructors")]
    public subcategory()
    {
         this.inventories = new HashSet<inventory>();
    }
    public string sbc_ccode { get; set; }
    public string sbc_code { get; set; }
    public string sbc_name { get; set; }
    public string sbc_createby { get; set; }
    public Nullable<System.DateTime> sbc_createdate { get; set; }
    public string sbc_updateby { get; set; }
    public Nullable<System.DateTime> sbc_updatedate { get; set; }
    public Nullable<sbyte> sbc_Status { get; set; }
    public Nullable<sbyte> sbc_migration { get; set; }
    [NotMapped]
    public Nullable<System.DateTime> sbc_logdatetime { get; set; }
    [NotMapped]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<inventory> inventories { get; set; }
}
```
Here's the value of the above model where Simple OData Client selects PUT over Patch to update.

```
inventories: Count = 0
sbc_Status: 1
sbc_ccode: "00001"
sbc_code: "00002"
sbc_createby: "100000"
sbc_createdate: {6/16/2016 10:27:17 AM}
sbc_logdatetime: null
sbc_migration: 0
sbc_name: "NONE"
sbc_updateby: "100022"
sbc_updatedate: {4/15/2017 1:17:40 PM}
```
However  the below value of the above model was saved successfully and Simple OData selects Patch over Put to update.
```
inventories: Count = 0
sbc_Status: 0
sbc_ccode: "00001"
sbc_code: "00001"
sbc_createby: "100001"
sbc_createdate: {5/4/2016 12:00:00 AM}
sbc_logdatetime: null
sbc_migration: 0
sbc_name: "NONE"
sbc_updateby: "100022"
sbc_updatedate: {4/15/2017 1:17:47 PM}
```

Those values were retrieved from the server with the below command. 
```
var subcatClient = await cloud.For<subcategory>()
                   .Filter(f => f.sbc_logdatetime >= ttd.downloaddate)
                   .FindEntriesAsync();
```
The first record was saved successfully using PATCH, but I don't know why it fails on the second record  and Simple OData Client is selecting PUT to update the second record. The error that I'm getting is with the sbc_logdatetime. I'm using MySQL and the sbc_logdatetime has a default value of CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP and DateTime data type.

Any idea why it's behaving that way? I thought Simple OData will no longer select PUT if I set the Update method to PATCH and I don't really quite understand why one record is being saved using Patch and the other using Put when they both came from one collection and untouched?

Here's the Inner Exception 
`Modifying a column with the 'Identity' pattern is not supported. Column: 'sbc_logdatetime'. Table: 'ServiceModel.Store.subcategory'.`

Here is my code for updating the record.
``` 
var subcatUpdate = await LAN.For<subcategory>()
                        .Key(subcat.sbc_code)
                        .Set(subcat)
                        .UpdateEntryAsync();
```
And I have this setup above.
```
var _settings = new ODataClientSettings();
_settings.IgnoreUnmappedProperties = true;
_settings.PreferredUpdateMethod = ODataUpdateMethod.Patch;
_settings.BaseUri = new Uri(CloudUri);

var _lanSettings = new ODataClientSettings();
_lanSettings.IgnoreUnmappedProperties = true;
_lanSettings.BaseUri = new Uri(LANUri);
_lanSettings.PreferredUpdateMethod = ODataUpdateMethod.Patch;
 
var cloud = new ODataClient(_settings);
var LAN = new ODataClient(_lanSettings);
``` 
Here's the complete update code for that specific Model. 
```
var subcatClient = await cloud.For<subcategory>()
.Filter(f => f.sbc_logdatetime >= ttd.downloaddate)
.FindEntriesAsync();

if (subcatClient.Count() > 0)
{
   DispatcherService.BeginInvoke(() =>
   {
       ttd.updaterecords = subcatClient.Count();
       ttd.finishflag = Utility.ProcessFlag.Downloading;
   });
  
   foreach (subcategory subcat in subcatClient)
   {
       try
       {
           var subcatUpdate = await LAN.For<subcategory>()
                    .Key(subcat.sbc_code)
                    .Set(subcat)
                    .UpdateEntryAsync();
           success = true;
       }
       catch (Exception ex)
       {
           try
           {
               var subcatInsert = await LAN.For<subcategory>()
                  .Set(subcat)
                  .InsertEntryAsync();
            }
            catch (Exception e)
            {
                success = false;
                DispatcherService.BeginInvoke(() =>
                {
                    ttd.finishflag = Utility.ProcessFlag.Error;
                 });
             }
       }
       finally
       {
            if (success)
            {
                DispatcherService.BeginInvoke(() =>
                {
                    ttd.downloadprogress++;
                 });
             }
        }
        if (!success || CanDoStartClick)
            break;
    }
}
else
{
    DispatcherService.BeginInvoke(() =>
    {
        ttd.finishflag = Utility.ProcessFlag.NoUpdate;
    });
}
```
Any help would be highly appreciated.

Thanks

**Comment by object** [comment]
I can think of the case when a record being updated has an updated field that is a part of its key. PATCH can only be applied to an update with no key data modified. For example, if you have a record with compound key Column1 + Column2 and the updated payload contains modified value for Column2, then the library has no choice but run PUT on the update. Can you verify that none of key data is affected by the update?

**Comment by DennisRodriguez** [comment]
Hi Vagif,

I only have sbc_code as the primary key, but your comments gave me an idea that there could be something wrong with my Web API and upon checking I found out that the patch sent to the Web API actually uses sbc_ccode as the primary key and in WebApiConfig I actually have this code.
```
builder.EntitySet<subcategory>("subcategories").EntityType.HasKey(k => k.sbc_ccode);
```
After replacing with the correct primary key field now everything works well.

Thank you for your help and my apology.

Dennis
