### ISSUE TITLE
Consuming metadata from Dynamics CRM Online

### ISSUE THREAD

**Issue by kirilgenov** [object/Simple.OData.Client#400]
Hi,

I'm consuming a Dynamics CRM Online OData web service and while trying to get the metadata I get the following exception:

**System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method. at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task) at Simple.OData.Client.ODataClient.d__25.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)** 

Here is my code:

**ICredentials credentials = new NetworkCredential(security.IntegrationUser, Crypto.DecryptStringAES(security.IntegrationPassword));
            ODataClientSettings settings = new ODataClientSettings(serviceConfiguration.ServiceBaseUrl, credentials);
            settings.IncludeAnnotationsInResults = true;
            this.client = new ODataClient(settings);
            var metadata = this.client.GetMetadataAsync().Result;**

Can you please advise?

Regards,
Kiril

**Comment by object** [comment]
Hi Kirill,

What happens if you try to fetch metadata from the browser? Try service {service_url}/$metadata Does it work? What do you get?

**Comment by kirilgenov** [comment]
Hi,

thank you for your reply!
If i fetch the metadata from the browser all looks good - i get the metadata as expected. I forgot to mention, that i already use this code with Dynamics NAV 2016 and Dynamics NAV Online and it all works as expected.

Thanks!
Kiril

**Comment by object** [comment]
Then it's not easy to guess what might have happened. Can you run a test with Fiddler (or another network traffic watcher) and check what the service return to metadata request. I don't think there's any failure in the library, it's just unable to retrieve metadata.

**Comment by kirilgenov** [comment]
Thank you for pointing me to Fiddler, this way i figured out that authentication was failing and the client was being redirected to the login page and was trying to interpret that page as the metadata document. Now i'm facing another problem but i'm still working on it and will get back on that in a bit.

Thanks!
Kiril
