### ISSUE TITLE
odata lib 7 nuget package

### ISSUE THREAD

**Issue by ysmoradi** [object/Simple.OData.Client#403]
I really appreciated the work you've done in OData lib 7 branch. I cloned that and I find out that covers most requirements I've . Could you please create a nuget package for that? I know that this is in its early stage, but something like nightly build could be useful. Thanks in advance

**Comment by object** [comment]
Hello, and sorry for the late response. Good to know that you find useful my intial ODataLib7 port. Unfortunately it still has some failing tests, so it's not in a good enough shape to be released as NuGet package. I have hard time fixing these tests in the nearest future, so if you have possibility to look at failing tests and fix some of them, I will highly appreciate this.

**Comment by JosephGarrone** [comment]
Are there are any build instruction for how to build the odatalib7 branch? We require OData Lib 7 for its fix - https://github.com/OData/odata.net/issues/88.

**Comment by object** [comment]
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7.
