### ISSUE TITLE
wrong ODataProtocolVersion when setting metadata manually (OData versions 1-3)

### ISSUE THREAD

**Issue by nrusitska** [object/Simple.OData.Client#408]
When passing the metadata as a string to the ODataClientSettings, the ODataProtocolVersion is not parsed correctly.
the OData V3 Adapter is always initialized with the protocol version 1.0 (the edmx-version), ignoring the DataServiceVersion (which may be 1.0 - 3.0).

**Comment by object** [comment]
PR merged, will be released shortly.
