### ISSUE TITLE
Compatibility with .NET Standard

### ISSUE THREAD

**Issue by nla-brandonjames** [object/Simple.OData.Client#425]
I need to build an application that runs on the Universal Windows and .NET Core runtimes to consume the OData v3 data from SAP B1 web service. When I attempt to install any clients I'm unable to restore the package to my UWP project.

**Comment by object** [comment]
This is correct. Simple.OData.Client uses internall two Microsoft's OData libraries: for OData protocol version 1-3 and for OData protocol version 4. None of them currently support .NET Core. It doesn't look like legacy ODataLib (the one that uses OData V3) will have any major update. AFAIK both libraries should be OK with .NET Standard 2.0, this will require repackaging of our library. It will come as a major version upgrade, I will need to investigate more.

**Comment by nla-brandonjames** [comment]
Thanks! Glad you confirmed this is doable!

 I got in contact with a Microsoft OData feedback team member as well, to ask about the WCF layer extension for VS 2017. He said they had a work item for it. Not so sure what the hold-up with Microsoft is. Maybe it's in development too.

The core of our business will be resting on SAP data as we move forward, so I'm hoping to do research ahead of time and fulfill the needs for all the platforms, since we'll be on .NET Core with Linux, UWP with Windows 10.

I really like .NET Standard, and it's so nice that when a library is put on it, that the code will run on all devices.

**Comment by object** [comment]
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7.
