### ISSUE TITLE
Patch support

### ISSUE THREAD

**Issue by adam-fairs** [object/Simple.OData.Client#43]
Hello,

Could you tell me whether PATCH requests are supported and whether more complex PATCH requests are?

An example would be where entity A is updated but records are inserted into a child table at the same time. Eg. Student has many Classes and Class has many Students. A PATCH request to update a student is sent where a reference to one class is removed, a reference to one class is added and references to all other classes stay the same.

If you'd like some more info, let me know. If this is supported, I look forward to getting on and using it.

Cheers,

Adam

**Comment by bradygaster** [comment]
Does the 4.10.0 version still aggressively support PATCH? if not, is there a way to enforce it? i've got a feature that needs this functionality. I'd be okay with changing it in the request myself if required, but some guidance on the method would be helpful. (tight time frame, need all the help...)

**Comment by object** [comment]
Hi, can you clarify what you want to achieve? Yes, the version 4.10 uses patch wherever possible, or do you want to enforce PUT even when PATCH should be sufficient?

**Comment by bradygaster** [comment]
No, I'd prefer to force PATCH in all cases. The client is issuing a PUT, based on what i'm seeing in Fiddler.

**Comment by object** [comment]
In the forthcoming version 4.11 there will be an option to set the preferred method (PATCH or PUT) but client on the API is not issuing PUT or PATCH - client is just calling Update and the library selects PATCH or PUT based on the preference and actual data (the methods are not always interchangeable). The current version always selects PATCH wherever possible so if it is what you want it should work fine for you as it is now.

**Comment by bradygaster** [comment]
Sorry - not sure I understand. So is the default mechanism today that it defaults to PATCH? If that's the case I don't understand why 100% of my update calls are PUT.

**Comment by object** [comment]
That's very strange. PUT is used over PATCH in case the updated properties include entity key. Can this be the case?

**Comment by bradygaster** [comment]
That could be. I'll investigate. Thanks much!

**Comment by object** [comment]
I am reopining this issue until you have investigated. Can you test updating a few non-key fields (e.g. you are not sending the whole object but just a collection of fields). In that case it should use PATCH, I have tests for this that work fine.

**Comment by object** [comment]
Version 4.11 adds an option to choose preferred update methods (PATCH or PUT).

**Comment by bradygaster** [comment]
Very excellent. Any information on how to opt for one versus the other?
