### ISSUE TITLE
Metadata errors are cached in MetadataCache

### ISSUE THREAD

**Issue by zivillian** [object/Simple.OData.Client#435]
If there is a (transient) error while resolving the metadata document, this error is cached forever.
I've already written an unit test to verify this and I'm currently working on a fix and would open a PR as soon, as this fix is ready.

We found this in one of our unit tests, which validates that the service returns a 401 if no credentials are sent. If this test is executed first, all subsequent tests fail with the same error.

This error was introduced in 4.28.0.

**Comment by object** [comment]
@zivillian Actually the change in metadata resolution had a serious impact on performance, because metadata cache is no longer in active use: there is always a call to metadata endpoint. I am checking how to fix it.

**Comment by zivillian** [comment]
@object: Is there anything I can do to help fixing this? Do you have any detail like an issue, test case, version, etc.?

**Comment by object** [comment]
Well, details are simple: metadata cache does not serve it's purpose, there is always a network call to obtain metadata from the service, and it causes major performance problem for scenarios with multiple instances of ODataClient.

**Comment by zivillian** [comment]
This seems to be one of the issues: https://github.com/object/Simple.OData.Client/issues/494#issuecomment-401749147 I'll comment there if I find anything.

**Comment by object** [comment]
Yes, I start getting complaints about performance drop, and I now seem to
understand what is the actual reason.
