### ISSUE TITLE
Issues with netstandard 2.0 library consumed from a .net 4.7.1 project

### ISSUE THREAD

**Issue by bjomi** [object/Simple.OData.Client#438]
The scenario:

I have a netstandard 2.0 library that references 5.0.0-beta2. This library project is then referenced from a .net 4.7.1 project (console project).

Both projects (netstandard 2.0 project by design) uses packagereference style for nuget dependencies.

The issue:

When building the .net 4.7.1 project Nuget determines that the dll that should be used is Simple.OData.Client.Net45.dll. So during runtime we get a FileNotFound exception since the referenced netstandard 2.0 library wants to use Simple.OData.Core.dll, which is nowhere to be found.

I don't really know what is supposed to happen here. One issue that might cause this is that the structure is totally different between netstandard (Simple.OData.Client.Core, Simple.OData.Client.Dynamic, Simple.OData.Client.V4.Adapter) and net45 (Simple.OData.Client.Net45).

Any thoughts about how to fix this?

Thanks,
Björn

**Comment by object** [comment]
The version 5 is finally released with full support for .NET Standard 2.0 (and .NET Core 2). This should fix the problem.
