### ISSUE TITLE
What are the odds if you upgrade from V4 to V5?

### ISSUE THREAD

**Issue by DennisRodriguez** [object/Simple.OData.Client#450]
Hi Vagif,

I would like to ask what are the odds if I upgrade my library from V4 to V5? 
Since its a major change would there be a major change also in the code from the developers perspective? Are there changes in the syntax? or how  Simple OData connects to the server? 
Do you have a documentation that discussed these modifications? Something that I can read or use that   can walk me through?

**Comment by object** [comment]
Sorry for long waiting @DennisRodriguez but I was working with other projects and couldnt have a chance to touch the library. Now version 5.0 is released, so I can finally answer your question. In short, this is mostly release to support .NET Standard 2.0 plus some bug fixes, extended functionality and better testability. This means that all your code written for V4 should work without any problems or modifications.
