### ISSUE TITLE
Compilation error message on dynamic syntax

### ISSUE THREAD

**Issue by jeusdi** [object/Simple.OData.Client#451]
I've coded this:

    var x = ODataDynamic.Expression;
    var products = await client
        .For(x => x.Products)    //<<<<<<<
        .FindEntriesAsync();

You can see it here:

![image](https://user-images.githubusercontent.com/941639/33995483-717fba7e-e0de-11e7-9c4e-7a237208a0f2.png)

The message is:

> Cannot convert lambda expression to type 'string' because it's not a delegate type

Any ideas?

**Comment by gjakovaime** [comment]
@jeusdi this doesn't seem like an issue with the library itself. If you're trying to query typed entities, refer to the instructions here: https://github.com/object/Simple.OData.Client/wiki/Retrieving-all-data-from-a-collection

```
var products = await _client
    .For<Products>()
    .FindEntriesAsync();
```

**Comment by object** [comment]
@jeusdi If you use lambda expression, you should use typed syntax. Otherwise just skip "x =>" and simply write "x.Products".
