### ISSUE TITLE
BeforeRequest clarification

### ISSUE THREAD

**Issue by fandrusi** [object/Simple.OData.Client#453]
I'm sorry if this is a dumb question.  Does the data source version influence the implementation "under the hood"...

I'm using the version agnostic Simple.Odata.Client nuget package (v 4.29), I'm hitting against a OData v3 data source.  Does that mean that the BeforeRequest will not work?

I did this based on a previously referenced code sample:

```
ODataClientSettings settings = new ODataClientSettings { Uri }
settings.BeforeRequest += x =>
{
 x.Headers.Add("Authorization", "Bearer " + token);
};
var client = new ODataClient(settings);
```

When executed, I get the message 

Message: Test XYZZY threw exception: 
System.MissingMethodException: Method not found: 'System.Action`1<System.Net.Http.HttpRequestMessage> Simple.OData.Client.ODataClientSettings.get_BeforeRequest()'.

Am I doing something dumb or should I NOT expect this to work vs. a v3 data source?

**Comment by kirilgenov** [comment]
Hi fandrusi,

I'm using the BeforeRequest in the following way and it works just fine for me:
`
ODataClientSettings settings = new ODataClientSettings(this.PortalService.ServiceBaseUrl, credentials);
settings.BeforeRequest = BeforeRequest;

        private static void BeforeRequest(System.Net.Http.HttpRequestMessage requestMessage)
        {
            
        }
`
