### ISSUE TITLE
5.0.0-beta2 nuget package requires Microsoft.OData.Edm 7.3.1 but uses 6.17

### ISSUE THREAD

**Issue by salgiza** [object/Simple.OData.Client#454]
We are using Xamarin, with a netstandard 2.0 common project.
We have installed the 5.0.0-beta2 nuget package, and everything compiles.

When we try to run the iOS app, however, any calls to the OData service returns an error indicating that the app can't find version 6.17 of the assembly (which is kind of normal, as the nuget package requieres/installs the newer 7.3.1 version)

"Could not resolve type with token 010008b (from typeref, class/assembly Microsoft.OData.Edm, Version=6.17.0.0, Culture=neutral, PublicKeyToken=31bf385ad364e35"

Steps to reproduce:

* Create a Xamarin Multiplatform solution.
* Add a new netstandard 2.0 project.
* Replace the original common project with the new netstandard project.
* Install Simple.Odata.Client in the netstandard project and in the iOS and Android projects.
* Add some code that consumes an OData service.
* Run the iOS app.

Notes:
* 5.0.0-beta1 works without problems, and so does version 4.29.
* I guess the error will also happen even if you don't use a netstandard project (that is, if you just create an empty Xamarin Multiplatform project and try to use beta2 in iOS), but I didn't have such a project to test it.

**Comment by S1r-Lanzelot** [comment]
Please see my issue, https://github.com/object/Simple.OData.Client/issues/460, `5.0.0-beta2` is not usable in my opinion. The same error occurs on Android.

**Comment by object** [comment]
Sorry for this. Fixed in 5.0.0.1.
