### ISSUE TITLE
The problem about Edm.Decimal in OData 3

### ISSUE THREAD

**Issue by yangyang80** [object/Simple.OData.Client#455]
Hi body,
I am a newer for OData. When I access the OData url: http://services.odata.org/Northwind/Northwind.svc/Products?$inlinecount=allpages&$format=json, I get the following data in the browser:

> "odata.metadata":"http://services.odata.org/Northwind/Northwind.svc/$metadata#Products",
> "odata.count":"77",
> "value":[
> {"ProductID":1,"ProductName":"Chai","SupplierID":1,"CategoryID":1,"QuantityPerUnit":"10 boxes x 20 bags",**"UnitPrice":"18.0000"**,"UnitsInStock":39,"UnitsOnOrder":0,"ReorderLevel":10,"Discontinued":false},
> {"ProductID":2,"ProductName":"Chang","SupplierID":1,"CategoryID":1,"QuantityPerUnit":"24 - 12 oz bottles",**"UnitPrice":"19.0000"**,"UnitsInStock":17,"UnitsOnOrder":40,"ReorderLevel":25,"Discontinued":false},
> ...

We will find the value type of UnitPrice is string: "18.0000".
But when I get the meta data for Products, I find it is defined as Edm.decimal

`<Property Name="UnitPrice" Type="Edm.Decimal" Precision="19" Scale="4"/>`

Is there something wrong?
When I want to filter the data with the link:
http://services.odata.org/Northwind/Northwind.svc/Products?$format=json&$inlinecount=allpages&$filter=((UnitPrice%20eq%20%2710.0000%27))
I get the error message from the service:

> A binary operator with incompatible types was detected. Found operand types 'Edm.Decimal' and 'Edm.String' for operator kind 'Equal'...

So what is the correct url for the filter above? How can I do filter on UnitPrice?

**Comment by object** [comment]
I believe @kirilgenov is right. Removing quotes should fix it.

**Comment by yangyang80** [comment]
Thanks all.
