### ISSUE TITLE
V3.Adapter.GetStreamAsync in .net standard 2.0 returns empty result

### ISSUE THREAD

**Issue by robinsmedberg** [object/Simple.OData.Client#457]
Seems casting HttpContent to ContentStream is not valid using System.Net.Http for net standard 2.0.

This seems to fix it but not sure if it's the prefered way to do it...

        public Task<Stream> GetStreamAsync()
        {
            if (_response.Content != null)
            {
                return _response.Content.ReadAsStreamAsync();
            }
            else
            {
                var completionSource = new TaskCompletionSource<Stream>();
                completionSource.SetResult(Stream.Null);
                return completionSource.Task;
            }
        }

**Comment by yuka1984** [comment]
I am in trouble with this problem too.
```
var responseContent = _response.Content as StreamContent;
```
.NET Core uses NoWriteNoSeekStreamContent Class, this method is always null.

I think that it is better to modify it to the code written by @robinsmedberg.
