### ISSUE TITLE
Please push Correct netstandard2.0 packages to Nuget

### ISSUE THREAD

**Issue by Amberg** [object/Simple.OData.Client#458]
If i Download the official packages, the V4.Adapter References Microsoft.OData.Edm, Version=6.17.0.0
https://www.nuget.org/packages/Simple.OData.Client/5.0.0-beta2

If I Checkout the Master branch Label 5.0.0-beta2 and build, the dll reference the correct version
Microsoft.OData.Edm, Version=7.3.1.10814

I Think the error is in the Simple.OData.V4.Client.nuspec file

The line

    <file src="Simple.OData.Client.V4.Adapter\bin\Release\Simple.OData.Client.V4.Adapter.dll" target="lib\netstandard2.0\Simple.OData.Client.V4.Adapter.dll" />

should be

    <file src="Simple.OData.Client.V4.Adapter\bin\Release\netstandard2.0\Simple.OData.Client.V4.Adapter.dll" target="lib\netstandard2.0\Simple.OData.Client.V4.Adapter.dll" />

**Comment by object** [comment]
@Amberg sorry for long waiting. The version 5.0.0.1 should fix this.

**Comment by Amberg** [comment]
Thank you
5.0.0.1 fixed this
