### ISSUE TITLE
EdmxReader has been renamed to CsdlReader

### ISSUE THREAD

**Issue by S1r-Lanzelot** [object/Simple.OData.Client#460]
EdmxReader has been renamed CsdlReader in Microsoft.Odata.Edm per https://github.com/OData/odata.net/issues/632 since v7.0 I believe.

The code still references the old name but requires an Odata.edm version >=7.3.1

I think is best to rename this and require the higher version. I don't mind submitting a PR for this.

#454

**Comment by S1r-Lanzelot** [comment]
It appears the latest code has this fixed.

**Comment by banderson501** [comment]
I am using Odata.edm version 7.4.1 but I am getting the error: "Could not load type 'Microsoft.OData.Edm.Csdl.EdmxReader' from assembly 'Microsoft.OData.Edm..."
What versions of which libraries do I need to get this working?

**Comment by S1r-Lanzelot** [comment]
@banderson501 I think the latest v5 code has not been submitted to nuget yet. What I ended up doing is using  `Version 5.0.0-beta1` from nuget since it targets Microsoft.OData.Core <7.0 (which still has Microsoft.OData.Edm.Csdl.EdmxReader). Unfortunately `Version 5.0.0-beta1` will warn about using 4.6 framework (if your project targets .NetStandard) but it will still work for the time being until the next beta is pushed to nuget; at least this was my conclusion. Hope it helps.

**Comment by banderson501** [comment]
I went back to this combo of versions and it works. Thanks for your help.
  Microsoft.OData.Core 6.19.0, Microsoft.OData.Edm 6.19.0, Microsoft.Spatial 6.19.0
  Simple.OData.V4.Client 5.0.0-beta1
