### ISSUE TITLE
Error executing aggregated function count

### ISSUE THREAD

**Issue by egarim** [object/Simple.OData.Client#462]
Hi, I have tried to use the example on the following link
https://github.com/object/Simple.OData.Client/wiki/Retrieving-data-matching-search-criteria
this is my code

                var annotations = new ODataFeedAnnotations();
                 var products = await Client
                .For<Cliente>()
                .ExecuteAsScalarAsync<Cliente>();

When I run it, I got the following error:

InvalidOperationException: Command is expected to be a function or an action.
When I trying to get the count in the browser using the following URL it works well
http://Localhost/odata.svc/Cliente/$count
I’m using the following version of Simple.OData.Client
"Simple.OData.V3.Client" version="5.0.0-beta2"
Is the aggregated function count supported?

**Comment by object** [comment]
If you need to retrieve a count of the result set, you can use the following syntax:

```
var products = await Client
            .For<Cliente>()
            .Count()
            .FindScalarAsync<int>();

```
(as described in the secion "Find the count of all products with the given name").

**Comment by GSingha** [comment]
I think the [document](https://github.com/simple-odata-client/Simple.OData.Client/wiki/Retrieving-all-data-from-a-collection#typed-syntax-1) needs to be updated.
```
var products = await _client
    .For<Products>()
    .FindEntriesAsync(); 
```
should changed to
```
var products = await _client
    .For<Products>()
    .FindEntriesAsync<int>(); // or FindEntriesAsync<T>();
```

**Comment by sixlettervariables** [comment]
That doesn't get a count.

**Comment by GSingha** [comment]
> That doesn't get a count.

Sorry! bad copy-paste mistake. I have updated my comment.  It should be

**Comment by watfordgnf** [comment]
I have updated the wiki.
