### ISSUE TITLE
Failure to parse metadata from DynamicsCRM 365 v9.0.1.731

### ISSUE THREAD

**Issue by bucktronic** [object/Simple.OData.Client#464]
Attempting to use ODataClient to read from DynamicsCRM I get the following exception: 

System.InvalidOperationException: Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.OData.Edm.Csdl.EdmParseException: Encountered the following errors when parsing the EDMX document: 
UnexpectedXmlElement : The schema element 'NavigationProperty' was not expected in the given context. : (1, 3990752)
...
UnexpectedXmlElement : The schema element 'NavigationProperty' was not expect...
   at Microsoft.OData.Edm.Csdl.EdmxReader.Parse(XmlReader reader)

Curtailed stack trace in attached file and metadata from DynamicsCRM attached also.

[stacktrace.txt](https://github.com/object/Simple.OData.Client/files/1884724/stacktrace.txt)
[metadata.txt](https://github.com/object/Simple.OData.Client/files/1884726/metadata.txt)

**Comment by object** [comment]
Can you try this with the latest release of the library (5.1)? I tried your metadata and it loads correctly in my tests.

**Comment by bucktronic** [comment]
Apologies, I've moved on to another project and don't have Dynamics access any more.
