### ISSUE TITLE
Question: Visual Studio 2015 (Windows) Sample Project

### ISSUE THREAD

**Issue by nemethmik** [object/Simple.OData.Client#465]
Maybe this is not the proper place to ask this question. Is there a sample project with sources, full example on how to use Simple.OData.Client in a Console or any Windows/Xamarin application GUI in C#/Visual Studio 2015?

**Comment by object** [comment]
I'd say the best sample project is the library's integration tests that shows all aspects of it. Take a look at it.
https://github.com/object/Simple.OData.Client/tree/master/Simple.OData.Client.IntegrationTests
