### ISSUE TITLE
Simple.OData.Client 5.0.0-beta2 .net core error Unable to load System.Net.Http.Extensions, Version=1.5.0.0

### ISSUE THREAD

**Issue by ODataSyd** [object/Simple.OData.Client#466]
Hi All ,

 I am trying to create a client in .net core for OData Services and using Simple Odata Client latest release Simple.OData.Client 5.0.0-beta2.

 I am able to read metadata , read properties ..etc but when I am trying to call method "FindEntriesAsync" I am getting an error unable to load "System.Net.Http.Extensions, Version=1.5.0.0".

I am not sure how to resolve this issue (or) is it an existing issue ? Is there any workaround atleast to overcome this issue . 

Thanks in advance for your help . 

Regards,
G.

**Comment by S1r-Lanzelot** [comment]
Could help: https://github.com/object/Simple.OData.Client/issues/460

**Comment by ODataSyd** [comment]
Hi S1r-Lanzelot ,

 I tried the resolution mentioned in your above post , but no luck .

To be clear 

I am using .net standard 2.0

I have a V3and V4 based OData Service to be consumed .

If there is any recommended Simple Odata DLL version and associated dependent dlls could you please let me know .

Primarly I am getting the error System.Net.Http.Extensions not able to load . 

Thanks.
G.

**Comment by ODataSyd** [comment]
Hi @S1r-Lanzelot  , Yes I am using 5.0.0-beta1 . Build is complaining about the mismatch but I am still able to run my logic.

my logic is very simple

![image](https://user-images.githubusercontent.com/38512869/38968260-f59c72be-43cd-11e8-846c-b7daa7a1e61a.png)


Creating a client and calling FindEntriesAsync method to get a record . 

I am getting the System.Net.Http.Extensions error .

I am new to Simple Odata , if i am missing anything please do let me know.

And thanks very much for your time and responses.

Regards,
G.

**Comment by S1r-Lanzelot** [comment]
In addition of beta-1, you must make sure that the following nuget versions are correct for your solution/project:
Microsoft.OData.Core 6.19.0, Microsoft.OData.Edm 6.19.0, Microsoft.Spatial 6.19.0

**Comment by object** [comment]
@ODataSyd @S1r-Lanzelot Sorry for long time to resolve it. This should be fixed in the package 5.0.0.1 (yes, the 5.0 RTM). Can you give it a try?
