### ISSUE TITLE
An unexpected 'EndOfInput' node was found when reading from the JSON reader

### ISSUE THREAD

**Issue by kyleherzog** [object/Simple.OData.Client#467]
I'm using Simple.OData.V4.Client version 4.29.0.  

When i make this call to FindEntriesAsync:
`var items = await Client.FindEntriesAsync("UniqueObservableObject");`

I get this ODataException:
Microsoft.OData.Core.ODataException: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected. Error found near:  <---

The `Client.FindEntriesAsync` call is in a .NET Standard 2.0 assembly.  I'm calling into the assembly from a .NET Core 2.0 unit test project.

The metadata is as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="Acme.DataAccess" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="UniqueObservableObject">
        <Key>
          <PropertyRef Name="Id" />
        </Key>
        <Property Name="Id" Type="Edm.String" Nullable="false" />
        <Property Name="ObjectType" Type="Edm.String" />
      </EntityType>
    </Schema>
    <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityContainer Name="Container">
        <EntitySet Name="UniqueObservableObject" EntityType="Acme.DataAccess.UniqueObservableObject" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

The response from the server is as follows:
`{"@odata.context":"https://localhost:44310/odata/$metadata#UniqueObservableObject","value":[{"Id":"0","ObjectType":"UniqueObservableObject"},{"Id":"1","ObjectType":"UniqueObservableObject"},{"Id":"2","ObjectType":"UniqueObservableObject"}]}`

**Comment by kyleherzog** [comment]
I just tried the following code in a .NET core test project and get the same EndOfInput error.

```
            var settings = new ODataClientSettings("http://services.odata.org/V4/OData/OData.svc/")
            {
                OnTrace = (x, y) =>
                {
                    Console.WriteLine(string.Format(x, y));
                },
                AfterResponse = async x =>
                {
                    var body = await x.Content.ReadAsStringAsync();
                    Console.WriteLine(body);
                }
            };

            var client = new ODataClient(settings);

            var items = await client.FindEntriesAsync("Products");
```

**Comment by kyleherzog** [comment]
Taking that last code snippet I posted and running it in a .NET Framework test project, it works just fine.  So, this seems to be a .NET Core compatibility issue.

**Comment by weitzhandler** [comment]
@object I'm facing this issue in 5.8: #646.

**Comment by ChrisSchaller** [comment]
This comes up from time to time when the server side has mismatched dlls, If you see this issue in the future, first check that the JSON sent to the server contains valid content, if it does then it is a server-side issue.

**Comment by sloscialo** [comment]
I'm seeing this error using Simple.OData.Client 5.22.0 with Microsoft.OData.Core 7.9.0. The Microsoft library is the same on both client and server, also they're .Net Core 5 projects.
