### ISSUE TITLE
Custom authorization on beforerequest

### ISSUE THREAD

**Issue by asierpn** [object/Simple.OData.Client#47]
Hello,

I'm trying to set the authorization property on the BeforeRequest action, but when i debug my WCF service the values added dont arrive on the request headers (I've implemented custom basic authentication on the WCF service).

I've tried the following codes without success:

1)

      var settings = new ODataClientSettings()
      {
        UrlBase = URL_SERVICIO
      };
      settings.BeforeRequest += delegate(System.Net.Http.HttpRequestMessage request)
      {
        String aux = String.Join(":", new String[] { usuario, password });
        var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(aux);
        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", System.Convert.ToBase64String(plainTextBytes));
    };
     var client = new ODataClient(settings);

2)

      var settings = new ODataClientSettings()
      {
        UrlBase = URL_SERVICIO
      };
      settings.BeforeRequest += delegate(System.Net.Http.HttpRequestMessage request)
      {
        String aux = String.Join(":", new String[] { usuario, password });
        var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(aux);
        request.Headers.Add("Authorization", "Basic " + System.Convert.ToBase64String(plainTextBytes));
      };

      var client = new ODataClient(settings);

Whe i debug the client, seems that the delegate is not invoked before doing the request.

Thanks,
Asier

**Comment by abelous1979** [comment]
Hi, I'm using version 4.7.0 of Simple.OData.Client and am attempting to pass through an OAuth2 bearer Authorization header. I'm currently experiencing the same problem as indicated above with initial $metadata call not passing the Authorization header to the source. Here's my setup of the header value: 

var settings = new ODataClientSettings(ProjConfig.EndpointBase);
settings.BeforeRequest = (message) =>
{
	message.Headers.TryAddWithoutValidation("Authorization",
		 "bearer " + authToken);
};
ODataClient client = new ODataClient(settings);

Any help would be greatly appreciated. Let me know if you want me to open up a new issue.

**Comment by object** [comment]
Thank you for the report. I will have a look at it.

**Comment by object** [comment]
Hi again,
I've inspected the code and ran some tests but was not able to reproduce the issue. I need more details about this. Did you debug the code? If so, did you see that BeforeRequest body was executed? I can see it in my debugging sessions.

**Comment by object** [comment]
Unable to reproduce.
