### ISSUE TITLE
nested $orderby on complex properties

### ISSUE THREAD

**Issue by zivillian** [object/Simple.OData.Client#473]
Currently $orderby only supports ordering by sub properties on navigation properties. The TripPin `Airport` has a complex property `Location` and trying to order by any of the Locations property results in an `UnresolvableObjectException Association [Location] not found`.

Example: [http://services.odata.org/TripPinRESTierService/Airports?$top=2&$orderby=Location/City/Name desc](http://services.odata.org/TripPinRESTierService/Airports?$top=2&$orderby=Location/City/Name%20desc)

**Comment by object** [comment]
Merged into v5. Will be released in 5.1.

**Comment by den5000** [comment]
Is same fixed for actions? I'm getting same error when do next: 
            var x = await _client
                .For<Asset>("unhealthyassets")
                .Action("UseFilter")
                .Set(new { AssetFilter = assetFilter })
                .OrderBy(x=>x.Criticality)
                .ExecuteAsEnumerableAsync();

but same without action works fine 

            var x = await _client
                .For<Asset>("unhealthyassets")                
                .OrderBy(x=>x.Criticality)
                .FindEntriesAsync();


same action without ordering works fine.
Thanks
