### ISSUE TITLE
Duplicate property error

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#475]
Same model that I had under 4.29 is breaking under 5.0.0 with an error

Microsoft.OData.ODataException : Multiple properties with the name 'Id' were detected in a resource or a complex value. In OData, duplicate property names are not allowed.
   at Microsoft.OData.DuplicatePropertyNameChecker.ValidatePropertyUniqueness(ODataProperty property)
...
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperty(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, Boolean allowStreamProperty, IDuplicatePropertyNameChecker duplicatePropertyNameChecker)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WriteProperties(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker)
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource)

The class concerned has an inheritance hierarchy Party -> Person | Company and a parent Owner property.

I've ruled out a straightforward problem with a parent relationship by hacking one of my entities locally which works fine and I've added a similar model into the samples but it works :-(

**Comment by object** [comment]
Can this be something with resolution of names? What if you try Strict name resolver (can be set in Settings)?

**Comment by phatcher** [comment]
The problem occurs in V4 RequestWriter.WriteEntryPropertiesAsync line 80...

` await entryWriter.WriteStartAsync(entry).ConfigureAwait(false);`

With any of the NameResolvers I get  

`"An item with the same key has already been added"`

**Comment by object** [comment]
Thanks. I will run your sample and try to figure out what's going on.

**Comment by phatcher** [comment]
Found the actual problem, TypeUtils.GetAllProperties is being too aggressive in that it's not just collecting public properties, its also getting them from interfaces.

So my class looks like this...

```
public class Party : IIdentifiable
{
      public int Id { get; set; }
      
      object IIdentifiable.Id => Id;
      ...
}
```

So when it flattens the properties we get

```
{
  { [Id], 0 },
  [ [IIdentifiable.Id], 0 }
}
```
Which is where the duplicate Id reference comes from.

What I'll do is write some tests for TypeUtils.GetAllProperties so I can see how we can limit it a bit more

**Comment by phatcher** [comment]
I've pushed a simple change to my v5 branch which filters out explicit interface implementation. This is quite tricky from the various SO answers so my one is just a first-try.

The long term solution I think is to refactor to provide a more coherent interface for determining which properties to use and to cache this to avoid the reflection overhead on each process

**Comment by object** [comment]
Thank you. I merged your code into v5 branch in my repo.
