### ISSUE TITLE
Failed to resolve type in IOS projects while Android and Windows runs.

### ISSUE THREAD

**Issue by ugomonte** [object/Simple.OData.Client#477]
Please help. I'm using simple.odata.client in an Xamarin.Forms solution with Visual Studio Community 2017 ver.15.7.2. I created an empty solution for android, ios and windows with .NET Standard code sharing.

I have not modified any project properties except for the installation of the current simple.odata.client package via nuget.

I used the main page to display a product list derived from the url 
"http://va-odata-integration.azurewebsites.net/odata/secure".

This is my code:
	public partial class MainPage : ContentPage
	{
        public MainPage()
	{
			InitializeComponent();
        }
        protected async override void OnAppearing()
        {
            base.OnAppearing();
            try
            {
                string serviceUri = "http://va-odata-integration.azurewebsites.net/odata/secure";
                string _user = "tester";
                string _password = "tester123";
                var config = new ODataClientSettings(new Uri(serviceUri))
                {
                    PayloadFormat = ODataPayloadFormat.Json,
                    BaseUri = new Uri(serviceUri),
                    IgnoreResourceNotFoundException = true,
                    Credentials = new NetworkCredential(_user, _password),
                    OnTrace = (x, y) => Console.WriteLine("UgoClient" + string.Format(x, y)),
                };
                var client = new ODataClient(config);
                var clientfor = client.For<Product>();
                var products = await clientfor.FindEntriesAsync();
                foreach (var product in products)
                {
                    Console.WriteLine(product.Name);
                }
                //// Custom Product List
                //var products = new List<Product>
                //{
                //    new Product {ID=1,Name="First Product",Price=100,Category="Cat1"},
                //    new Product {ID=2,Name="Second Product",Price=200,Category="Cat2"}
                //};
                productsView.ItemsSource = products;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(@"				ERROR {0}", ex.Message);
            }
        }
    }
[Errore Xamarin Progetto IOS.txt](https://github.com/object/Simple.OData.Client/files/2049540/Errore.Xamarin.Progetto.IOS.txt)

**I get the data and I see the list for the Android project and for the Windows project while for IOS project Debugging I see on the istruction "var clientfor = client.For<Product>();" I get the following error:**

"Failed to resolve type {Name =\n  \"System.Collections.Generic.IDictionary`2[[System.String, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]\";\n GenericArgs = [|{Name = \"System.String\";\n                  GenericArgs = [||];\n                  ArrayRank = 0;}; {Name = \"System.Object\";\n                                    GenericArgs = [||];\n                                    ArrayRank = 0;}|];\n ArrayRank = 0;}"

Have you suggestions or indications on how to investigate (attached complete exception). 
Thanks so much.
Bye
Ugo

**Comment by ugomonte** [comment]
It seems I solved my problem. It was sufficient to add this instruction before initializing the client.

Simple.OData.Client.V3Adapter.Reference ();

Greetings

**Comment by object** [comment]
Then it is an issue with a linker stripping out too much. You should google for similar issues in iOS apps, should be fixed in your app project settings.
