### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by worstenbrood** [object/Simple.OData.Client#481]
There are some hardcoded paths in the project files that prevent compiling:

https://github.com/object/Simple.OData.Client/blob/4eeb6243960b25cad45ad1466c5c01a190683e99/Simple.OData.Client.Core/Simple.OData.Client.Core.csproj#L10
https://github.com/object/Simple.OData.Client/blob/4eeb6243960b25cad45ad1466c5c01a190683e99/Simple.OData.Client.Core/Simple.OData.Client.Core.csproj#L13
https://github.com/object/Simple.OData.Client/blob/4eeb6243960b25cad45ad1466c5c01a190683e99/Simple.OData.Client.Dynamic/Simple.OData.Client.Dynamic.csproj#L9
https://github.com/object/Simple.OData.Client/blob/4eeb6243960b25cad45ad1466c5c01a190683e99/Simple.OData.Client.Dynamic/Simple.OData.Client.Dynamic.csproj#L13

**Comment by object** [comment]
Sorry for that. This was generated by Visual Studio that unfortunately puts an absolute path for generated docs. I'll fix it.

**Comment by object** [comment]
Should be fine now.
