### ISSUE TITLE
Dynamic type values are double quoted

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#482]
With ODataLib 7.x dynamic type values are parsed as ODataUntypedValue and everything is returned as a string.

Unfortunately this means that string values are double quoted e.g. "Foo" in the json is returned as RawValue of "\"Foo\""

I've got a fix for this which is just a modification of GetPropertyValue e.g.

```
    else if (value is ODataUntypedValue)
    {
        return ((ODataUntypedValue) value).RawValue;
    }
```
goes to
```
    else if (value is ODataUntypedValue untypedValue)
    {
        var result = untypedValue.RawValue;
        if (!string.IsNullOrEmpty(untypedValue.RawValue))
        {
            // Remove extra quoting as has been read as a string
            // Don't just replace \" in case we have embedded quotes
            if (result.StartsWith("\""))
            {
                result = result.Substring(1);
            }
            if (result.EndsWith("\""))
            {
                result = result.Substring(0, result.Length - 1);
            }
        }
        return result;
    }
```
I'll raise a pull request for this

There's no unit tests ATM as we don't have an open type example in the code base

**Comment by object** [comment]
Actully there were some integration tests that failed after the change, but it was a quick fix. Release 5.2.1.
