### ISSUE TITLE
ODataClient Unexpectedly Wrapping Response

### ISSUE THREAD

**Issue by andrewcot** [object/Simple.OData.Client#486]
As requested, opening this ticket to track this issue. Below is a copy of what I added to issue 478.

I'm working on the same project and we have run into a secondary issue after this fix was applied (we are now at version 5.2.1), We have found that the ODataClient is returning values in an unexpected way. For example, we have a call made using the client as follows:

```
IDictionary<string, object> response = await client
    .For("ExampleEntity")
    .Key(key)
    .Action("ExampleAction")
    .ExecuteAsSingleAsync();
```

Previously this would return a dictionary with keys for the properties like this:
```
SomeProperty : test
SomeOtherProperty : 1
```

However after the update, the dictionary instead contains only a single key called "__result" and contains all the OData information as the value:
```
__result : {"@odata.context" : "http://localhost/ApiActionExample/odata/$metadata#ApiActionExample.Model.ExampleComplex", "SomeProperty" : "test", "SomeOtherProperty" : "1"}
```

I've found that if I pull out the value and desrialize it, everything does work like before, but it seems like the __result shouldn't be returned by the client, it should already be unwrapped when it returns from the Execute method (at least based on past functionality).

We have also tried using the 'For<ExampleComplex>' overload that returns the object rather than a dictionary. While this does return the object, none of the properties are set.

This code worked in version 4.29.0 and then broke when we upgraded to 5. The original issue (478) was found at that point, and now this one was found after that update (the previous issue prevented us from getting to this point so it's possible the issue existed in other versions of 5).

Here is the schema (also copied)
```
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="ApiActionExample.Model" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <ComplexType Name="ExampleComplex">
                <Property Name="SomeProperty" Type="Edm.String" />
                <Property Name="SomeOtherProperty" Type="Edm.Int32" Nullable="false" />
            </ComplexType>
            <EntityType Name="ExampleEntity">
                <Key>
                    <PropertyRef Name="ID" />
                </Key>
                <Property Name="ID" Type="Edm.Int32" Nullable="false" />
                <Property Name="SomeProperty" Type="Edm.String" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <Action Name="ExampleAction" IsBound="true">
                <Parameter Name="bindingParameter" Type="Collection(ApiActionExample.Model.ExampleEntity)" />
                <ReturnType Type="ApiActionExample.Model.ExampleComplex" />
            </Action>
            <EntityContainer Name="Container">
                <EntitySet Name="ExampleEntity" EntityType="ApiActionExample.Model.ExampleEntity" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>
```

All of our javascript calls to the OData methods work correctly, postman also works properly, returning the same data that it did in previous versions. It is only when using the ODataClient object on the server side that we experience any problems.

Here is postman:
![40681808-668ebaca-6347-11e8-9a44-5332b28a3cd0](https://user-images.githubusercontent.com/40039754/41135001-8e9e6848-6a8c-11e8-8155-e21a8831b52e.png)

**Comment by object** [comment]
Released version 5.3. that should fix the issue.
