### ISSUE TITLE
empty collection properties are deserialized as null

### ISSUE THREAD

**Issue by zivillian** [object/Simple.OData.Client#487]
When expanding a collection property this may be an empty collection like in this example:
[TripPinService/People('keithpinckney')?$expand=Trips&$select=Trips,UserName](http://services.odata.org/V4/TripPinService/People('keithpinckney')?$expand=Trips&$select=Trips,UserName)
```json
{
    "@odata.context": "http://services.odata.org/V4/(S(wbn5c1lovxzbzubnfi3a1uz1))/TripPinServiceRW/$metadata#People(Trips,UserName)/$entity",
    "@odata.id": "http://services.odata.org/V4/(S(wbn5c1lovxzbzubnfi3a1uz1))/TripPinServiceRW/People('keithpinckney')",
    "@odata.etag": "W/\"08D5CD60F1CAA892\"",
    "@odata.editLink": "http://services.odata.org/V4/(S(wbn5c1lovxzbzubnfi3a1uz1))/TripPinServiceRW/People('keithpinckney')",
    "UserName": "keithpinckney",
    "Trips@odata.context": "http://services.odata.org/V4/(S(wbn5c1lovxzbzubnfi3a1uz1))/TripPinServiceRW/$metadata#People('keithpinckney')/Trips",
    "Trips": []
}
```
The [ReponseReader](https://github.com/object/Simple.OData.Client/blob/ce33282a2066620f18184a9c40b8382bfd72cb04/src/Simple.OData.Client.Core/Adapter/ResponseReaderBase.cs#L116) currently [does not return empty collection properties](https://github.com/object/Simple.OData.Client/blob/ce33282a2066620f18184a9c40b8382bfd72cb04/src/Simple.OData.Client.Core/Adapter/ResponseNode.cs#L20), which results in them not beeing initialized and thus null. This may cause further unexpected NullReferenceExceptions on explicitly expanded properties.

**Comment by object** [comment]
Merged your PR and released 5.2.2.
