### ISSUE TITLE
Parsing typed fluent API returns null

### ISSUE THREAD

**Issue by bjornmicallef** [object/Simple.OData.Client#495]
Excuse my stupid question as this is probably explained already but I could not find anything within the Wiki pages, or anywhere else on the net. I have just started using the Simple.OData.Client and I managed to get basic API and dynamic fluent API working, but not typed fluent API.

I created a simple class to reflect the data entity I'm interested in. Mind you I did not add all the data entity properties to the class as there are loads and some of them are complex types.

```
public class Project {
    [DataMember(Name = "dataAreaId")]
    public string dataAreaId;

    [DataMember(Name = "ProjectID")]
    public string ProjectID;

    [DataMember(Name = "ProjectName")]
    public string ProjectName;

    [DataMember(Name = "ProjectGroup")]
    public string ProjectGroup;
}
```

I then try to retrieve the projects as follows

```
var client = new ODataClient(clientSettings);

var projects = await client.For<Project>().FindEntriesAsync();

foreach (var project in projects ) {
     Console.WriteLine(project .ProjectID);
}
```

The data is there because I can see it using Fiddler but for some reason when I try to parse it into my object all the properties are null. Can someone point out to me what am i doing wrong please?

Similarly, if I keep using the typed fluent API, is there a quick way to create classes from the data entities?

Thanks in advance,

**Comment by bjornmicallef** [comment]
Great! Thanks, it did work with the getters and setters.

**Comment by bjornmicallef** [comment]
Similarly I have another issue when trying to insert a new record.

Using the same example as above let's say that I want to create a new project. DataAreaID and ProjectID are key values and in my C# code I am setting DataAreaID, ProjectName and ProjectGroup. ProjectID is auto increment with a string format and will be populated automatically by D365.

Using typed fluent I create a new Project instance and try to use the method InsertEntryAsync(). I am getting the following exception - _The property 'ProjectID[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed_.

If I remove ProjectID from my class the insert will work but then I can't retrieve the ProjectID since it is not a property in my class, obviously. I tried just leaving the get, and removing the set for the ProjectID property but the same error comes up. Any help would be appreciated, thanks!

**Comment by object** [comment]
What will happen if you keep ProjectID but set to an empty string (or any non-null string) on Insert? Since it's value on Insert is set by the service it might just overwrite it with a new value.

**Comment by bjornmicallef** [comment]
Good thinking! When I tried that I would get the following error though
_Field validation failed on table of type 'ProjectEntity' for the following fields: PojectID. Infolog: Warning: Field 'Project' does not allow editing.; Warning: ID does not match format XYZ-######.._

There's a format validation on that field. Strangely enough when I do an insert with dynamic syntax it works even though I am not including the ProjectID. Example code below.
```
var project = await client
		.For(x.Project)
		.Set(x.dataAreaId = "XYZ",
			x.ProjectName = "This works",
			x.ProjectGroup = "Even this")
		.InsertEntryAsync();
```

Similarly I have another issue which really and truly is the reason why I have this issue. Sorry for bothering.

At first I found the dynamic syntax quite good and I was using it for CRUD operations. The problem occurred when I had an insert process inside a C# method and was calling it from a loop. Something similar to the below.
```
public async Task<string> CreateProject(string _projectName, string _projectGroup)
{
	string projectId = string.Empty;
	var client = Authentication.CreateOdataClient(); //this is my class where I create the ODataClient
	var x = ODataDynamic.Expression;

	var project = await client
		.For(x.Project)
		.Set(x.dataAreaId = "XYZ",
			x.ProjectName = "This works",
			x.ProjectGroup = "Even this")
		.InsertEntryAsync();
	return projectId = project.ProjectID;
}

// in another class and separate method

foreach (object myObject in myListOfObjects) {
	string projectId = await CreateProject(myObject.ProjectName, myObject.ProjectGroup);
}
```
In this case what is happening is that the projects created all have the same project name and group. Even though the parameters are changing according to the values passed in the loop, for some reason when I go check it out in D365 they are all the same name and group. I could not understand why this is happening because when debugging it was clear that the values are changing. I then tried a different approach (typed fluent) and created the Project model with the intent of creating a new clean instance every time I call the method (from the loop) but I got the problem I am explaining above. Any thoughts would be greatly appreciated!

Thanks

**Comment by bjornmicallef** [comment]
I am still getting familiar with D365 myself too! Yes I understand that OData is not SQL but a framework. Yeah auto-incremental and format specific fields are validations done at D365, I agree. I will try different combinations and research more to get try and get it right.

I'll have a look at the tests, thanks for the links!
