### ISSUE TITLE
Unable to load OData adapter from assembly Simple.OData.Client.V3.Adapter

### ISSUE THREAD

**Issue by theBlueclouds** [object/Simple.OData.Client#501]
How many more bugs need to reported to solve this? 
app config binding redirects enabled or not this error occurs 

**error source**: Microsoft.Threading.Tasks
**stack trace**:

> at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Simple.OData.Client.FluentClientBase`1.<RectifyColumnSelectionAsync>d__35.MoveNext()

**PAckages.config**
`  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.Bcl" version="1.1.9" targetFramework="net452" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="net452" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net452" />
  <package id="Microsoft.Data.Edm" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Data.OData" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Data.Services.Client" version="5.8.1" targetFramework="net452" />
  <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="net452" />
  <package id="Microsoft.OData.Core" version="6.0.0" targetFramework="net452" />
  <package id="Microsoft.OData.Edm" version="6.0.0" targetFramework="net452" />
  <package id="Microsoft.Spatial" version="6.0.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net452" />
  <package id="SAPDotNetConnector3" version="0.3.0" targetFramework="net452" />
  <package id="Simple.OData.Client" version="4.29.0" targetFramework="net452" />
  <package id="System.Spatial" version="5.8.1" targetFramework="net452" />`

**Comment by object** [comment]
"How many more bugs need to reported to solve this?"

This is not the best way to address issue resolution in open source software. I always appreciate pull requests and thankful to many developers who contributed to the project. From your packages.config I can see that you are using an old version of Simple.OData.Client. Did you try the latest one?
