### ISSUE TITLE
Documentation: Multi level expand?

### ISSUE THREAD

**Issue by NetTecture** [object/Simple.OData.Client#509]
Can you just point me (and possibly expand the documentation) towards how to do multi level expands?

?expand=x($expand=y) - how do I express that in typed api?

I manage to get to

            var data = await c
                .For<OdataApi.Account>()
                .Expand(x => x.Roles)

but then I am stuck. x.Roles is an ICollection of an obhect with a navigation property that needs further expansion. No odata funciotns availab.e.

**Comment by object** [comment]
Here are some examples:
https://github.com/object/Simple.OData.Client/blob/master/src/Simple.OData.Client.UnitTests/Core/ExpansionTests.cs

I will always welcome pull requests on improved documentation :-)

**Comment by NetTecture** [comment]
Will sewe what I can do after holidays (September). Why do you not just accept some Patreon? I think I could justify paying for a commercial support license ;)
