### ISSUE TITLE
Metadata parsing performance

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#512]
There seems to be a slow down from the 4.x to the 5.x series which in part I think is attributable to the way that metadata is handled

Below is a profiling snapshot from an app that has imported a few 10s of records into my system and as you can see the numbers of calls/cost is quite high

![image](https://user-images.githubusercontent.com/192778/43686750-d848b728-98c2-11e8-94cf-4436e1ed16c0.png)

This is basically a placeholder for me to put some other benchmarks and potential improvements against , e.g. caching the results of the metadata calls for the duration of the session

**Comment by phatcher** [comment]
On the feature branch I've introduce two caches, one for IPluralizer the other for IMetadata.

The first may sound odd but look at the number of invocations on my app which is importing ~100 records..
![image](https://user-images.githubusercontent.com/192778/43688856-c125cfc4-98e8-11e8-9dff-096dbebad074.png)

After these two optimisations the profile graph looks like this
![image](https://user-images.githubusercontent.com/192778/43688868-f9cbcf9a-98e8-11e8-92c0-500e841c258c.png)

For example, the invocations for SimplePluralizer.SuffixRule drop from 273M! to 11K and BestMatchResolver from 1.87M to 933K. We also save about 20M calls to Microsoft.Edm

The perceived improvement was good as well - varying from 25% to 50% faster

**Comment by object** [comment]
@phatcher this looks very interesting. Of course our current use of metadata resolver is quite naive - same repetitive operations without any caching. And judging from other feedbacks I have an impression that Microsoft OData V7 libraries has been slower than V6 conterparts. So there are good reasons to avoid calling them when we can.
But when it comes to caching, I suppose this should be caching per schema, because a client may connect to multiple OData services, and same types may be resolved differently for different schema URLs. Do you have this mind?

**Comment by object** [comment]
BTW, the forthcoming version 5.5 introduces compilation of expressions used in converting results to typed objects. But this didn't seem to give a noticeable performance gain.

**Comment by phatcher** [comment]
@object Yes, it has to be per schema, but it also has to be per ClientSettings due to things like IgnoreUnmappedProperties, NameMatchResolver etc.

I've implemented it so that it caches on a per ODataAdapter basis, and restarts if the Model is changed, but it should be possible to move this down a bit further so that the cache could be instantiated once per schema/ClientSettings combination.

The code is on features/512_Metadata if you want to take a look.  I'd appreciate if you'd try it on your project and see if you get the same sort of improvements.

On a slightly different point, is there any need for ODataModelAdapter/ODataModelAdapterBase as they don't seem to be referenced from anywhere?

**Comment by object** [comment]
Thanks Paul. I will try your changes.
And I am not sure we need ODataModelAdapter. This was a PR I accepted based on suggested ideas to add more customization possibilities. But now it looks like a premature change without real practical need. And now that V5 adds more customization points, I think these classes can be taken away.

**Comment by phatcher** [comment]
@object Do you mind if I change the signature of MetadataBase etc, I'd like to break the direct link between it and ISession and instead just inject/set the values that it uses - this then allows me to have a cache factory, which can construct/return the appropriate Metadata cache

I'd also like to do some internal renaming, e.g. at the moment what we are calling a MetadataCache is really an EdmModelCache which leads to interesting name choices for IMetadataCache :-)

**Comment by object** [comment]
@phatcher It should be fine as long as it doesn't break the public API (otherwise it requires major version bump). ODataClient class has a public method ClearMetadataCache which we shouldn't touch. Also I'd like to avoid exposing such details like Edm in public API, to keep the client "simple" as the name suggests. Apart from that, go ahead, Paul, you have commit rights. You can also get rid of ODataModelAdapter/ODataModelAdapterBase classes if it doesn't break anything (I don't think it does).

**Comment by phatcher** [comment]
@object  Yes, my ideas shouldn't touch the public API at all, just the internal implementation.

What ClearMetadataCache will do is reset the entire caching layer that I'm introducing, but I might need to introduce a couple more abstractions so that I can construct the correct cache based on the ODataClientSettings, that way it will persist across ODataClient instances rather than, as currently,  surviving for just a single ODataAdapter

**Comment by object** [comment]
Sounds good.

**Comment by phatcher** [comment]
Ok with the final performance optimisation it save another few million calls...

![image](https://user-images.githubusercontent.com/192778/44617497-3fc27900-a85b-11e8-9a73-79b235c41766.png)

You can see the calls to Microsoft have dropped another 20m invocations saving ~40% of the execution time, we also save almost 10m calls inside Simple.OData but these affect the timing results much less.

Just need to do the tidy up and it will be ready for merging

**Comment by object** [comment]
That's terrific Paul! BTW what tool did you use to collect these metrics? JetBrains profiler?

**Comment by phatcher** [comment]
Yes using Timing mode - I can't see a "hot" path through the code, so I just concentrated on reducing calls.

I've just finished the style refactoring so I'll issue a pull request and you can tell me what you don't like - couple of renames etc but they don't hit the public API just the internal classes that happen to be public.

As is it provides a good performance improvement, but to finish off it needs the cache factory functionality so that the metadata cache persists across different ODataClient instances - this is will be very useful for short-lived/multi-threaded clients such as web applications using OData as the backend

**Comment by object** [comment]
But it can be achieved by specifying MetadataDocument. Or you have in mind caching not just the document but all metadata as resolved by the client and then persistent? This might be a challenge because client may keep extending such metadata as it is executing requests. Then persistent cache needs to be extended too.

**Comment by phatcher** [comment]
@object What I'm considering is aligning MetadataDocument -> IEdmModel -> MetdataBase -> MetadataCache so that the costs of producing all this metadata, which we have seen is expensive, are amortized over each unique MetadataDocument/ClientSetings combination, rather than spun up each time a new ODataClient is created.

For desktop clients, what we have already is probably good enough, but for my main use case where I have web applications calling an OData backend I think it is a useful optimisation as then the new metadata cache will be used for the lifetime of the web app rather than being inflated for every web request.

Before that though I want to introduce some form of Type cache to hold things like whether a Type is a dynamic object and if so what the property is called, I think this would address #158, #302, #351, #365 and #369;  it would also remove my need for a custom type converter that's needed just to handle subtype resolution e.g. Animal -> Dog.

This _may_ have some performance benefits in DictionaryExtensions.ToObject but the overall costs of this is now very low at ~3ms, I'm more interested in good open type support which would tidy up my client implementation substantially and open up some more possibilities on our projects.

**Comment by object** [comment]
@phatcher I just pushed 5.5.0-beta2 package with performance improvements. They are huge - I ran benchmark tests (and stored results in Artifact directory of the Benchmark project), about 30% faster on all tests.

I am closing this issue now, so we can create a fresh one for new aspects of performance improvements.
