### ISSUE TITLE
use count with filter error

### ISSUE THREAD

**Issue by homer-zhang** [object/Simple.OData.Client#523]
when I use odataclient to fetch data from Microsoft Dynamics CRM,  count with filter , it throw an error,
only use one function , count , filter , skip , top , there is no error , but both use count and filter , error meessge show , both use skip and count , error message show. Can you help me ?
code : 
`
var rs = cilent.For("products").Filter("contains(name,'test')")
                .Count().FindScalarAsync<int>().GetAwaiter().GetResult();
`
errors :
`
{
  "error":{
    "code":"","message":"Count Segment is not supported when SavedQuery or UserQuery or FetchXml option is provided","innererror":{
      "message":"Count Segment is not supported when SavedQuery or UserQuery or FetchXml option is provided","type":"Microsoft.Crm.CrmException","stacktrace":"   \u5728 Microsoft.Crm.CrmException.Assert(Boolean condition, String message)\r\n   \u5728 Microsoft.Crm.Extensibility.OData.Extensions.EdmExtensions.IsCustomQueryOptionPresent(HttpRequestMessage request)\r\n   \u5728 Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySet(String entitySetName)\r\n   \u5728 lambda_method(Closure , Object , Object[] )\r\n   \u5728 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   \u5728 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- \u5f15\u53d1\u5f02\u5e38\u7684\u4e0a\u4e00\u4f4d\u7f6e\u4e2d\u5806\u6808\u8ddf\u8e2a\u7684\u672b\u5c3e ---\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   \u5728 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- \u5f15\u53d1\u5f02\u5e38\u7684\u4e0a\u4e00\u4f4d\u7f6e\u4e2d\u5806\u6808\u8ddf\u8e2a\u7684\u672b\u5c3e ---\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   \u5728 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- \u5f15\u53d1\u5f02\u5e38\u7684\u4e0a\u4e00\u4f4d\u7f6e\u4e2d\u5806\u6808\u8ddf\u8e2a\u7684\u672b\u5c3e ---\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   \u5728 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}
`
also there is another error when use count with skip.
code :
`
var annotations = new ODataFeedAnnotations();
var rs = cilent.For("products").Filter("contains(name,'test')")
                .Top(2).Skip(2).FindEntriesAsync(annotations).GetAwaiter().GetResult();
`
error:
`
{
  "error":{
    "code":"","message":"Skip Clause is not supported in CRM","innererror":{
      "message":"Skip Clause is not supported in CRM","type":"Microsoft.Crm.CrmHttpException","stacktrace":"   \u5728 Microsoft.Crm.Extensibility.OData.DataQueryOptionsConverter.SetPagingInfoAndTopCount(QueryExpression qe, TopQueryOption topQueryOption, SkipQueryOption skipQueryOption, CrmODataExecutionContext context)\r\n   \u5728 Microsoft.Crm.Extensibility.OData.QueryOptionsConverterBase`4.GetQueryExpression(ODataQueryOptions queryOptions, String edmEntityName, CrmODataExecutionContext context)\r\n   \u5728 Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.RetrieveEdmEntityCollection(CrmODataExecutionContext context, String entityCollectionName, String castedEntityName, ODataQueryOptions queryOptions)\r\n   \u5728 Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySetInternal(String entitySetName, String castEntityName, CrmODataExecutionContext context, CrmEdmEntityObjectCollection crmEdmEntityObjectCollection, ODataQueryOptions queryOptions)\r\n   \u5728 Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySet(String entitySetName)\r\n   \u5728 lambda_method(Closure , Object , Object[] )\r\n   \u5728 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   \u5728 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- \u5f15\u53d1\u5f02\u5e38\u7684\u4e0a\u4e00\u4f4d\u7f6e\u4e2d\u5806\u6808\u8ddf\u8e2a\u7684\u672b\u5c3e ---\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   \u5728 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- \u5f15\u53d1\u5f02\u5e38\u7684\u4e0a\u4e00\u4f4d\u7f6e\u4e2d\u5806\u6808\u8ddf\u8e2a\u7684\u672b\u5c3e ---\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   \u5728 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- \u5f15\u53d1\u5f02\u5e38\u7684\u4e0a\u4e00\u4f4d\u7f6e\u4e2d\u5806\u6808\u8ddf\u8e2a\u7684\u672b\u5c3e ---\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   \u5728 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   \u5728 System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}
`

**Comment by object** [comment]
From the call stack it looks like this is a server error. You can see that the exception is thrown by Microsoft.Crm.Extensibility code, I guess this is the limitation of Microsoft Dynamics CRM.

To be absolutely sure, you can make a simple test. Since for GET requests our library simply generates URLs, you can use Postman or any other HTTP tool to manually generate a request, send it to Dynamic CRM and check what result you are getting.

**Comment by homer-zhang** [comment]
@object  Yes , you are right , Microsoft Dynamics CRM web api do not support skip。 but there is another question, count with filter, I can get the right result with the URL :  http://xxx/MDM/api/data/v8.2/products/?$top=1&$count=true&$filter=contains(name,%27test%27) 
it will give me the right total count by the filter,and only show one on the current page.
but use odataclient ,  filter and then count , it will error , because the url is not same as the right one.
the url of odataclient is http://xxx/MDM/api/data/v8.2/products/$count?$filter=contains(name,%27test%27) , it is not work well .

**Comment by object** [comment]
I believe this is also a server side error, because OData the library generates URL correctly, according to the specs. I've found a GitHub issue:

https://github.com/OData/WebApi/issues/194

count=true is not the same as count, because the first one retrieves both count and entities, the latter one only retrieves a count.
