### ISSUE TITLE
Upgrade to Net Core?

### ISSUE THREAD

**Issue by PDNemesis** [object/Simple.OData.Client#530]
Is there any plan for an upgrade to .Net Core?
We are currently working with AspNet Core projects that will be executed in a container that needs run in a Linux machine and we need all of our components to be not dependent of the .NET Framework.
Thanks!

**Comment by phatcher** [comment]
It already works with .NET Core, need to be netstandard2.0 or above

**Comment by PDNemesis** [comment]
Taking a look to the code (Simple.OData.Client.Core project for instance), we have seen a dependency of .NETFramework 4.5.2.

**Comment by phatcher** [comment]
It actually says `<TargetFrameworks>net452;netstandard2.0</TargetFrameworks>`, that's not a really a dependency, it means that it is compiled separately for both net452 and netstandard2.0

You can also look at the [published nuget package](https://www.nuget.org/packages/Simple.OData.Client/) and see that it supports both frameworks

**Comment by PDNemesis** [comment]
That's right! Thank you very much :-)
