### ISSUE TITLE
Filters on key-based queries

### ISSUE THREAD

**Issue by wiredbarb** [object/Simple.OData.Client#532]
This has been issued before and you explained in [a comment](https://github.com/object/Simple.OData.Client/issues/262#issuecomment-226426103) why filters on key-based queries are not supported. I would like to reopen this discussion, because:

1. This restriction is posing a major issue with our use cases, where access right checks need to be applied on single entry queries. Currently, this requires fetching the whole entity - including attributes that are needed for nothing but filtering - to apply the checks locally. We cannot use just filters, because the only identification feature we have for detail requests is the entity's key attribute, and the Simple OData Client will convert `.Filter(x => x.Id == 13).Filter(x => x.CustomerId == 125)`  to `.Key(13).Filter(x => x.CustomerId == 125)`, which results in "OData filter and key may not be combined.", of course. 
To solve this, either introducing a redundant non-key-attribute holding the key value - which does not work for external OData services (plus, it _is_ redundant) - or using some sort of crude workaround like `.Filter(x => !(x.Id < 13 || x.Id > 13))` is required.

1. In practice, filters usually do seem to be supported on key-based queries and they behave as expected - requesting a record with existing key that does not match the filter criteria will return the same result as requesting one with a nonexistent key. 
cf. Northwind queries: [matched criterion](http://services.odata.org/V4/Northwind/Northwind.svc/Categories(1)?$filter=CategoryName%20eq%20%27Beverages%27), [unmatched criterion](http://services.odata.org/V4/Northwind/Northwind.svc/Categories(1)?$filter=CategoryName%20ne%20%27Beverages%27), [nonexistent key](http://services.odata.org/V4/Northwind/Northwind.svc/Categories(9))

I am aware that the `$filter` option is not defined (yet also not explicitly forbidden) for single entity requests in the [URL Conventions](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_SystemQueryOptions), so I expect you judge the support for this as straying too far from the definition. In that case, removing the query conversion mentioned in 1. or introducing a setting to disable this behaviour would do as well to solve this.

**Comment by object** [comment]
@wiredbarb sorry for slow response - too much to do with other projects. Your explanation in (2) makes sense, and I will see if I can relax the constraint so the library will support specifying both keys and filters in a single query.

**Comment by object** [comment]
I believe the library can support both key and filter specification. Should be released in version 5.6.
