### ISSUE TITLE
Library is not strongly named / signed

### ISSUE THREAD

**Issue by chancie86** [object/Simple.OData.Client#536]
When I try to sign my own assembly which loads in Simple.OData.Client I get this exception at runtime:

System.IO.FileLoadException: 'Could not load file or assembly 'Simple.OData.Client.Core, Version=5.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

**Comment by object** [comment]
This was discussed earlier:
https://github.com/object/Simple.OData.Client/issues/155

In short: the library assembly is not signed, and there are no plans to sign it. There are workarounds for that left up to the users.

**Comment by chancie86** [comment]
Just wanted to follow up on how to sign the built assembly as it really wasn't trivial...

You can use a tool like Nivot, as per suggestion in #155, but it doesn't quite get you there due to the use of the InternalsVisibleTo attribute in Simple.OData.Client.Core.dll. This causes the load to fail at runtime.

The way I got it to work is to modify the IL for the other 3 dll's. Search for uses of InternalsVisibleTo in the IL code and update the content. Unfortunately, as it's IL, it's in binary format rather than a nice string (which would be something like [assembly: InternalsVisibleTo("Simple.OData.Client.Core, PublicKey=abcdef")]. The way I get the data was to add it to my own assembly, build, disassemble, and copy and paste the data out of there. Afterwards you can re-assemble the dlls and then add the reference to your project.

References:
http://www.delabs.io/the-12th-labor-of-a-net-developer-part-4/
https://stackoverflow.com/questions/331520/how-to-fix-referenced-assembly-does-not-have-a-strong-name-error/
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=netframework-4.7.2

**Comment by NetTecture** [comment]
I literally want to voice an opposing opinion here, too.

This is a library you want to just use. If you have to rebuild your whole build stack the moment you use it in a signed project, it differs SIGNIFICANTLY from any other NuGet package that I use, and most of them are ALSO open source. Not sure where the reference in #155 comes from, but no other package I have requires me to self sign. Including, btw., Newtonsoft Json. It is trivial to add signing to the project and publish official project versions, but it is NOT trivial to add signing as post fact without totally building yourself, which makes the official nuget packages moot for those cases.
