### ISSUE TITLE
Simple.OData.V4 in Test Project

### ISSUE THREAD

**Issue by Mugen-Binary** [object/Simple.OData.Client#548]
Hello!

I am working on a project that realizes integration tests through the MSTest framework. Now the problem is, I installed the Simple.OData.V4 NuGet into the Test Project. However, when I run the tests, I get the error message: 

`Message: Initialization method KiamToKcrmCrudTestCases.KiamKcrmApiReadTestCase.Initialize threw exception. System.AggregateException: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter ---> System.IO.FileNotFoundException: Could not load file or assembly 'Simple.OData.Client.V4.Adapter' or one of its dependencies. The system cannot find the file specified.WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].`

I assume this happens because the assembly is present in the project, but it is not present in the context the test runner uses. Is there any workaround for this problem?

**Comment by object** [comment]
Hi,
You should check that Simple.OData.V4.Client is present in a test run directory. It's been long time since I used MSTest, so but as far as remember it runs tests in a different directory than the project bin folder. 
You can check out Simple.OData.Client unit and integration tests. They all run fine, but they are using XUnit.

**Comment by Mugen-Binary** [comment]
I found a solution. Apparently, dynamic assembly loading and any assembly loading of assemblies which MSTest does not recognize as "necessary" is quite ugly. I had to add the assembly as file to the project and add it as a deployment-item. But it works now. Thank you for your help!
