### ISSUE TITLE
Retrieve annotations from metadata

### ISSUE THREAD

**Issue by pko67** [object/Simple.OData.Client#552]
Possible similiar question like this:
https://github.com/object/Simple.OData.Client/issues/544

I want to retrieve language dependent column descriptions provided in annotations from a service. The service is in use in a JavaScript environment and it will return the expected values also within Postman.
Now I want to get these information in C# environment, using Simple.OData.Client in version 5.5.0. The OData service is in version 2.

C# code:
var baseUri = new System.Uri("http://svr-sap-dev:8000/sap/opu/odata/MYPROD/REPORT_TAB_SRV/");
var credentials = new System.Net.NetworkCredential("user", "passwd");
var client = new ODataClient(
    new ODataClientSettings
    {
        BaseUri = baseUri,
        Credentials = credentials
    });

var metadata = await client.GetMetadataAsync();

Checking the result in the OnTrace-Handler will get "Request completed: OK"
Now I observe the result variable metadata in debugger and after expanding the complex structure on the following path, I can see the expected values:

Debugger watch window:
metadata.schemaTypeDictionary.Items[6]).value.DeclaredProperties.Items[2].DirectValueAnnotations.Items[0].Value.value <-- expected value.

When I use this path as an individual line in debugger output I will get an error message.
My question is: Is there an way using the simple OData client API to retrieve these annotation values?

((Microsoft.Data.Edm.Csdl.Internal.Parsing.Ast.CsdlDirectValueAnnotation)
(new System.Collections.Generic.Mscorlib_CollectionDebugView<object>(((
(Microsoft.Data.Edm.Csdl.Internal.CsdlSemantics.CsdlSemanticsProperty)
(new System.Collections.Generic.Mscorlib_CollectionDebugView<Microsoft.Data.Edm.IEdmProperty>((
(Microsoft.Data.Edm.Csdl.Internal.CsdlSemantics.CsdlSemanticsStructuredTypeDefinition)
(new System.Collections.Generic.Mscorlib_DictionaryDebugView<string, Microsoft.Data.Edm.IEdmSchemaType>((
(Microsoft.Data.Edm.Library.EdmModelBase)metadata).schemaTypeDictionary).Items[6]).value)
.DeclaredProperties).Items[2])).@property).annotations).Items[0])).value

error CS1503: Argument "1": Conversion of 
"System.Collections.Generic.IEnumerable<Microsoft.Data.Edm.IEdmProperty>" 
in "System.Collections.Generic.ICollection<Microsoft.Data.Edm.IEdmProperty>"
not possible.

Thanks! Peter

**Comment by object** [comment]
@pko67 For the time being Simple.OData.Client has only limited support for annotations. This is due to the fact it convert results into instances of C# types which have no annotation concept. However, the library includes ODataEntryAnnotations type that can be used retrieve entry-specific annotations (there is also a type for feed annotations).
Have a look at the library Integration tests, in particular TripPinTests that show how to use these types to retrieve annotations associated with results.

**Comment by pko67** [comment]
I set the OdataClientSettings TraceFilter to ODataTrace.All and catched the required annoations from the OnTraceHandler.
This fulfills my requirements!
