### ISSUE TITLE
Filter throws NullReferenceException instead of meaningfull exception

### ISSUE THREAD

**Issue by Mugen-Binary** [object/Simple.OData.Client#557]
Hello!

When I run the following very simple query:

```
var contactModel = await OdataClient
                .For<KcrmContactModel>()
                .Filter(x => x.SsoId == ssoId.ToString())
                .FindEntryAsync() ?? throw new NotFoundException();
```

I get a System.NullReferenceException thrown. I identified the issue: I can not use ToString in the filter lambda. I do understand now why, as well. Because it can not be translated into OData Syntax.

However, it would be nice if the library threw a meaningful exception instead of failing with a null pointer.

Cheers, Patrick

**Comment by NetTecture** [comment]
Actually this may be a bug. Is there ar eason ou could not run ssoId and THEN send to odata? that is a variable, right, we do not talk of ToString on the x. side.

**Comment by Mugen-Binary** [comment]
No that's exactly how I solved the problem.

```
var ssoString = ssoId.ToString();
var contactModel = await OdataClient
                .For<KcrmContactModel>()
                .Filter(x => x.SsoId == ssoString)
                .FindEntryAsync() ?? throw new NotFoundException();
```

That works. But due to the unspecific exception it took me a while to figure out what the problem was.

**Comment by object** [comment]
@Mugen-Binary Thank you for submitting the issue. What you are suggesting makes absolute sense. I will look into how this can be improved.

**Comment by object** [comment]
This is actually a bug because the library is capable of translating soId.ToString() into the actual value before generating OData filter clause. Fix will be released in a next version.
