### ISSUE TITLE
how to get $metadata result into datatable?

### ISSUE THREAD

**Issue by nighotatul** [object/Simple.OData.Client#567]
we have https://services.odata.org/V2/Northwind/Northwind.svc/$metadata excute this link we got exception "json is not supported." so how we can get metadata directly and convert into datatable?

**Comment by nighotatul** [comment]
when we call GetMetadataAsync() this method we get nothing.

**Comment by object** [comment]
Hello! Do you want to obtain the metadata document? Then you need to use service endpoint  https://services.odata.org/V2/Northwind/Northwind.svc (without "$metadata") and call a method GetMetadataDocumentAsync() with await.

Hope this helps.

**Comment by nighotatul** [comment]
Hello,

I got Exception that Resource not found.

I am using 5.6.1 version when i go into detail exception then i came to know that Requested uri

going like below

https://services.odata.org/V4/Northwind/$metadata

which is wrong it should be executed like below 

https://services.odata.org/V4/Northwind/Northwind.svc/$metadata

then only we will get the result.Please check it example

https://services.odata.org/V4/Northwind/Northwind.svc/$metadata

**Comment by nighotatul** [comment]
same things happened regarding trip pin service

https://services.odata.org/v4/TripPinService/

I am executing above link and call  var _response1 = await client.GetMetadataDocumentAsync();

its requested uri is https://services.odata.org/v4/$metadata

so above throw exception like not found so it should execute like below to get result

https://services.odata.org/v4/TripPinService/$metadata

**Comment by nighotatul** [comment]
https://js.devexpress.com/Demos/WidgetsGallery/odata/WeatherItems

the above odata service metadata i got perfectly by following code

 var _response1 = await client.GetMetadataDocumentAsync();

So i don't know why it is work for some url and not work for some other

please check it .

**Comment by object** [comment]
@nighotatul Before releasing 5.6.1 I ran integration tests that validate behavior of sample services at odata.org (both for XML and JSON payload, OData versions 2, 3 and 4). The tests passed so I supposed there's something in your app that wasn't correctly set up. Can you checkout the library integration tests? If you are absolutely sure you set it up correctly, can you send an example of URLs and payload (that you can obtain from tools like Fiddler)?

**Comment by nighotatul** [comment]
Please closed this ticket issues has been solved.
