### ISSUE TITLE
How to replace CustomConverters.RegisterTypeConverter 

### ISSUE THREAD

**Issue by kyleherzog** [object/Simple.OData.Client#573]
I've been using `CustomConverters.RegisterTypeConverter(Type type, Func<IDictionary<string, object>, object>converter)` to convert an object from an int, which is how the object normally serializes and is sent down from my OData host.  This works in v5.6.1 but doesn't seem to have any effect upon upgrading to v5.6.2.  In v5.6.2, I start to get `ConstructorNotFoundException`, which is what i expect to get if my converter isn't registered.

I see that `CustomConverters.RegisterTypeConverter` is now marked as obsolete, and it is noted that I should use `ITypeCache.Converter`,  but how exactly do I go about doing that.  Where do I get the `ITypeCache`?

**Comment by phatcher** [comment]
@kyleherzog I'll try and update the documentation pages to make this clearer, but basically you can get to it from the ODataClientSettings.TypeCache property which contains an ITypeConverter.

This give a couple of capabilities...
1. You can register custom converters on a per-schema basis
2. You can register open types centrally rather than needing to pass the dynamic property container name in the command; this also solves the issue of how to retrieve open types via expand.

```
var settings = new ODataClientSettings {BaseUri = new Uri("http://localhost")};

settings.TypeCache.TypeConverter.RegisterTypeConverter(typeof(Bar), MyBarConverter);

// This registers the Animal as an open type with the dynamic properties 
// container "DynamicProperties" the WebAPI OData default
settings.TypeCache.Register<Animal>();
```

On the next release, I'll probably also stretch out the ITypeConverter interface to include open generic registration methods i.e.

```
settings.TypeCache.TypeConverter.RegisterTypeConverter<Bar>(MyBarConverter);
```

**Comment by phatcher** [comment]
@kyleherzog One other thing, if you create your ODataClientSetttings before you call the CustomerConverters.RegisterTypeConverter, it should register your type converter in the relevant ITypeConverter instance; still not sure if we should provide a global registration ability that would default the converters in the per-schema instance?

**Comment by kyleherzog** [comment]
@phatcher I think I'm still missing something.  I'm registering my type converter with 
`settings.TypeCache.Converter.RegisterTypeConverter(typeof(myType), myConverter.Convert);`

I can verify that the converter is registered for `myType` by calling `settings.TypeCache.Converter.HasObjectConverter<myType>()`. However, I don't ever see `myConverter.Convert` ever being called if I debug and step through.  I just continue to get a `ConstructorNotFoundException`

**Comment by phatcher** [comment]
@kyleherzog Have a look at my v5 branch, I've added a new test GetPhotoViaConverter which is a TripPin test using a custom converter.

Can you see any differences between this setup and your code?

**Comment by kyleherzog** [comment]
@phatcher I pulled down the v5 branch, but I can't seem to find a test called GetPhotoViaConverter.  I did a solution wide search in the Simple.OData.Client solution, but came up empty. Is it a brand new test you just created?  Looks like the latest commit from you that I'm seeing on v5 was on Jan 11.

**Comment by phatcher** [comment]
@kyleherzog v5 on my fork i.e. https://github.com/phatcher/Simple.OData.Client/commit/73ed858fa07089b017fbdc683ec0037e5644c016

**Comment by kyleherzog** [comment]
Got it working.  I had my converter setup to use the `Func<object, object>` signature instead of `Func<IDictionary<string, object>, object>`.  Leveraging the IDictionary version works just fine. Thanks for your help!
