### ISSUE TITLE
Multiple Expand propeties

### ISSUE THREAD

**Issue by Allann** [object/Simple.OData.Client#69]
When I request multiple properties to be expanded I get a NotSuppotredException.  This is actually supported, at least it is in v4. Is there a chance this can be supported here too?

According to OData ABNF, expand syntax should be:
expand = '$expand' EQ expandItem *( COMMA expandItem )

Something like  http://services.odata.org/northwind/northwind.svc/Categories?$expand=Products/Category,Products/Supplier

It could be that I have the syntax wrong for Expand too.  Can you supply an example?

Thanks,  appreciate your work so far.

**Comment by object** [comment]
Hi,

I checked TripPin examples, and there I had expansion of multiple properties, here's how it looks:

TripPinServiceRW/People('russellwhyte')?$expand=Trips,Friend

And here's the code:

            var person = await _client
                .For<Person>()
                .Key("russellwhyte")
                .Expand(x => new { x.Trips, x.Friends })
                .FindEntryAsync();


If there is something that doesn't work for you, can you supply the code snippet and how the URL looks?

Thanks

**Comment by Allann** [comment]
Thanks, will check this on Monday
