### ISSUE TITLE
WebRequest timeout

### ISSUE THREAD

**Issue by junker76** [object/Simple.OData.Client#71]
Is it possible to set the web request timeout for any/every issued operation?
we suspect we have some server-side operation that is taking a lot of time to complete and the client stops working with an error like 'server is not responding'.

We found this thread
https://github.com/object/Simple.OData.Client/issues/23
but the signature of the BeforeRequest handler seems to be changed iv v. 4 and System.Net.Http.HttpRequestMessage does not permits to set any timeout).

Thanks.

**Comment by object** [comment]
Thanks for reporting the issue. Timeot is set on HttpClient instance which is not exposed by ODataClient. I will figure out how to best expose this property and let you know.

**Comment by object** [comment]
Resolved in version 4.1.0 (added RequestTimeout to ODataClientSettings).

**Comment by junker76** [comment]
Thank you.
