### ISSUE TITLE
ODATA V2 - Issues/questions

### ISSUE THREAD

**Issue by iuliapapadima** [object/Simple.OData.Client#74]
Hi,

I have to consume some odata services. These services were generated on a SAP HANA Platform and there it is used ODATA Version 2 protocol.

I tried to use Simple.OData.Client library in order to get/change the data. I'm receiving the error: "Unable to identify OData protocol version". I debuged it and I noticed that there is a method: GetSupportedProtocolVersions(in AdapterFactory.cs). Here it's identified the protocol. Unfortunately, these odata services don't have the protocol version in the metadata response header. The protocol version is mentioned only in the payload (m:DataServiceVersion ="2.0"). The metadata response is looking like this:

HTTP/1.1 200 OK
set-cookie: xsSessionId=8DE9915B864974439436F64EFAFF08E1; path=/; HttpOnly
set-cookie: sapxslb=03663AB23F1F1B41ACDAC72C9883C327; path=/; HttpOnly
content-type: application/xml;charset=utf-8
content-length: 2040
cache-control: no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
< edmx:E dmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx">< edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:DataServiceVersion="2.0">
< Schema Namespace="playground.i055799.OdataTestsProject.OdataTestService1" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://schemas.microsoft.com/ado/2008/09/edm"><EntityType Name="t_ztable1Type">< /Schema>...........< /edmx:DataServices>< /edmx:Edmx>

Please tell me if it's possible to consider also this situation, when the protocol version is determined.

I made a little change in the my code in order to return the protocol version 2 and I tested it. 
I have another issue in the batch processing. An error "BAD Request" is returned when a batch request is sent. I investigated this and is seems that a Content-Length is needed for each operation.
Currently every operation from a changeset looks like this:

--changeset_f290a406-5cdf-40a9-abd1-cfa4e741af3a
Content-Type: application/http
Content-Transfer-Encoding: binary

POST http://***/OdataTestsProject/OdataTestService1.xsodata/t_ztable1 HTTP/1.1
Content-ID: 1
Content-Type: application/json;odata=verbose;charset=utf-8

{
  "__metadata":{
    "type":"playground.i055799.OdataTestsProject.OdataTestService1.t_ztable1Type"
  },"ID":38,"VERS_ID":14,"COL11":"Col 123","COL12":"Col 12345"
}
--changeset_f290a406-5cdf-40a9-abd1-cfa4e741af3a--

Please tell me if it is possible to add additional headers(Accept,Content-Length) for each POST/PUT/PATCH operation.

e.g.

--changeset_f290a406-5cdf-40a9-abd1-cfa4e741af3a
Content-Type: application/http
Content-Transfer-Encoding: binary

POST http://***/OdataTestsProject/OdataTestService1.xsodata/t_ztable1 HTTP/1.1
Content-ID: 1
Content-Type: application/json;odata=verbose;charset=utf-8
Accept: application/json;odata=verbose
Content-Length: XXX

{
  "__metadata":{
    "type":"playground.*.OdataTestsProject.OdataTestService1.t_ztable1Type"
  },"ID":38,"VERS_ID":14,"COL11":"Col 123","COL12":"Col 12345"
}
--changeset_f290a406-5cdf-40a9-abd1-cfa4e741af3a--

Thank you for your support!

Kind Regards,
Iulia

**Comment by object** [comment]
Hi and thank you for the issue report.

When it comes to protocol version, I will check if I can detect it from the payload. It's probably safe to assume that if it is not returned in the header, it is an old service (v1-3).

With content length it is another story. I am using internally Microsoft ODataLib that generates all batch payloads. I am not sure I can tweak it to write the content length. I will come back to you about that.

**Comment by object** [comment]
Hi again,

I just pushed version 4.0.10 where the check for supported OData protocol is relaxed - if there are no such headers, it assumes that this is a legacy adapter.

When it comes to other issue, it's more complicated. As I said before, I am using ODataLib internally that generates batch changesets and while I have access to message stream, the stream length is not easily accessible. I checked Microsoft OData service examples for protocols V1-3 and they all accept changesets without content length so this is something you should strive to support too. If I find a way to get hold of the content length, I will change the implementation.
