### ISSUE TITLE
Aggregate function on Simple OData Client

### ISSUE THREAD

**Issue by jackmadeja** [object/Simple.OData.Client#76]
I have a query that looks like this: 
MyDataSource?$filter=productId eq '442343' and timestamp ge datetimeoffset'2014-01-18T00:00:00Z' and timestamp le datetimeoffset'2015-02-12T00:00:00Z' &aggregation=MONTH
This query will return list that is aggregated on timestamp on 1 month. 
I wonder how to implement aggregate with typed syntax:
if I have this:
var listOfData = await client
.For <MyDataSource> ()
.Filter (x => x.productId == productId && x.timestamp >= timeFrom && x.timestamp <= timeTo)
.FindEntriesAsync ();

**Comment by object** [comment]
Hi Jack,

I guess you are talking about OData aggregation extensions, as describer here: http://docs.oasis-open.org/odata/odata-data-aggregation-ext/v4.0/cs01/odata-data-aggregation-ext-v4.0-cs01.html

I so, then they are not (yet) implemented in the Simple.OData.Client, but this is something that I can add to the backlog.
