### ISSUE TITLE
Simple.OData.Client and WPF

### ISSUE THREAD

**Issue by skadefro** [object/Simple.OData.Client#77]
is anything special needed to get SOC to work in a WPF application, or is that not supported at all ?
( simple test project that "fails" http://admin.wingu.dk/OdataWPFTest.zip )
Notice that it fetches the /$metadata and then it just hangs forever ?

**Comment by object** [comment]
Hi,

No, the library works just fine. But you have to use it in asynchronous manner, it's Wait and Result that block your app.

**Comment by skadefro** [comment]
Hey, the lib works perfectly in console apps, windows apps, and MVC projects, by just accessing the result property of the tasks. But in WPF it just hangs.
I'm a bit new to the whole async/await approach, but http://stackoverflow.com/questions/5095183/how-would-i-run-an-async-taskt-method-synchronously gave me the "trick" with just accessing the result property, to block and wait for completion.
Do you have any idea how I would go about, getting the result synchronously in WPF then?

Testing stuff to see if SOC just isn't working inside WPF I tried this:
var task = client.For<ccp.entities.entitybase>("entities").Filter(x => x.id == "1").FindEntryAsync();
//var result= t.Result; 
var continuation = task.ContinueWith(t => {
	var result= t.Result;
});
It takes a very, very long time, but it does get the result. but that's still async, not really usefull.

if instead do something like this, it just looks forever, never returning isCompleted.
                while (!task.IsCompleted)
                {
                    System.Threading.Thread.Sleep(100);
                }
                var result = task.Result;

I'm assuming the task has been stated since calling start, results in the exception "Start may not be called on a continuation task"

**Comment by object** [comment]
The problem with Wait and Result is that in some scenarios they simply block the caller, usually it happens in UI thread. So I'd recommend not to use it at all. In Silverlight you just can't use these calls, period. The app will block 100%. I believe what you can try to achieve can be implemented in a simpler way. I can check it out later, but you should be able to find some examples on the net or just ask at StackOverflow.

**Comment by object** [comment]
Here are a couple of examples:

http://www.codeproject.com/Tips/457235/WPF-with-Asynchrony-Part
http://www.codearsenal.net/2012/11/csharp-5-async-and-await-example.html#.VN8ls0fF-SE

**Comment by skadefro** [comment]
you rock, thank you ;)
decorating all functions with async, and using await in the WPF works perfectly.
So no issue at all, error was on my part.

I'll try and follow your advice and rewrite all the code to async/await
