### ISSUE TITLE
Problem with the .Count() functionality in this simple code snippet

### ISSUE THREAD

**Issue by thomasbeste** [object/Simple.OData.Client#80]
var settings = GetODataClientSettings();
            var client = new ODataClient(settings);
            var command = client
                .For<FacilityModel>("Facilities")
                .Filter(x => x.FacilityCurrency == "EUR")
                .Count()
                .Top(1005);

            var result = await command.FindEntriesAsync();
            return result;

The above code fails with a '{"Not Found"}' exception message. The code runs against an OData V3 service, built using Odata v3 for WebApi 2.2. As soon as i remove the .Count() method, the code runs smoothly. i cannot seem to find any good documentation documenting how to use the $inlinecount=allpages correctly from the Simple.OData client. i have verified that the server responds correctly:
Query: http://localhost:63115/Facilities?$inlinecount=allpages
Response (values snipped): "odata.metadata":"http://localhost:63115/$metadata#Facilities","odata.count":"1000","value":

**Comment by object** [comment]
Hi,
Since you are using Count clause, you are getting back a scalar value, so FindEntriesAsync won't work. Try replacing it with .FindScalarAsync<int>, i.e.:
var result = await command.FindScalerAsync<int>();

Then "result" should contain the actual count.

**Comment by thomasbeste** [comment]
Hi,

Thanks for the quick reply. 

However i was looking for a construction which would make it possible to utilize the "inlinepagecount". You have an example of this where you use a constructor taking two arguments, a bool and an out promise<int>. I cannot find that constructor anywhere, and I am wondering if it is related to an old version, or if I am doing something wrong :-)

Med venlig hilsen/regards 

Thomas Albrecht-Beste
beste.dk

**Comment by object** [comment]
Oh I see, I misunderstood you. Version 4.0 changes the syntax, you should use feed annotations, like in the integration test below.

        [Fact]
        public async Task TotalCount()
        {
            var annotations = new ODataFeedAnnotations();
            var products = await _client
                .For("Products")
                .FindEntriesAsync(annotations);
            Assert.Equal(77, annotations.Count);
            Assert.Equal(77, products.Count());
        }

**Comment by thomasbeste** [comment]
Thanks a bunch, works like a charm! 

I cannot seem to find documentation, can you point me in the right
direction? :) 

Regards, 

Thomas Albrecht-Beste 

beste.dk 

Vagif Abilov skrev den 2015-02-20 07:56: 

> Oh I see, I misunderstood you. Version 4.0 changes the syntax, you should use feed annotations, like in the integration test below. 
> 
> [Fact]
> public async Task TotalCount()
> {
> var annotations = new ODataFeedAnnotations();
> var products = await _client
> .For("Products")
> .FindEntriesAsync(annotations);
> Assert.Equal(77, annotations.Count);
> Assert.Equal(77, products.Count());
> }
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 

Med venlig hilsen/Regards,

Thomas Albrecht-Beste
+45 2082 2015
beste.dk
 

Links:
------
[1]
https://github.com/object/Simple.OData.Client/issues/80#issuecomment-75197558

**Comment by object** [comment]
This change is in fact not described in Wiki yet, something I need to do. The whole ODataFeedAnnotations feature came as a result from other request (https://github.com/object/Simple.OData.Client/issues/46) and was implemented right before 4.0 release.
