### ISSUE TITLE
Server driven paging?

### ISSUE THREAD

**Issue by uffelauesen** [object/Simple.OData.Client#82]
Does Simple.OData.Client support paging thru server pages ($skiptoken/nextLink/Continuation)? If so could you please supply an example of how to do paging from your client?

**Comment by object** [comment]
Yes it does. Here's an example from integration tests (https://github.com/object/Simple.OData.Client/blob/master/Simple.OData.Client.IntegrationTests/TripPinTests.cs):

        [Fact]
        public async Task FindAllPeople()
        {
            var annotations = new ODataFeedAnnotations();

            int count = 0;
            var people = await _client
                .For&lt;Person&gt;()
                .FindEntriesAsync(annotations);
            count += people.Count();

            while (annotations.NextPageLink != null)
            {
                people = await _client
                    .For&lt;Person&gt;()
                    .FindEntriesAsync(annotations.NextPageLink, annotations);
                count += people.Count();
            }

            Assert.Equal(count, annotations.Count);
        }

**Comment by uffelauesen** [comment]
Ahhh, nice. Thank you Vagif.
/uffe
