### ISSUE TITLE
Dynamic data to Table

### ISSUE THREAD

**Issue by mskurnik** [object/Simple.OData.Client#84]
I have an application that lets a user dynamically query an OData service and return to them the specific columns they requested inside of a grid.  In order to do this I have an XML file that defines:
 - BaseUrl
 - ListName
 - Columns
  - ODataColumnPath
  - ColumnDataType
  - FriendlyName

I create a `DataTable` by recursively looping (while loop) through all `IEnumerable<IDictionary<string, object>>`s until I get the value(s) that I am looking for.  I then use the XML data to create the DataTable columns and then I populate the rows from the loop.  This approach works fine but it is a lot of code to accomplish this.

Now when I run the query I am looking for in LinqPad connecting directly to [a Northwind odata service](http://demos.telerik.com/kendo-ui/service/Northwind.svc/) I get back a `IQueryable<Anonymous>` object.
**LinqPad -> Northwind**
```C#
Products.Select (x => new { x.ProductID, x.ProductName, x.Category.CategoryName })
```
**Request URL**
http://demos.telerik.com/kendo-ui/service/Northwind.svc/Products()?$expand=Category&$select=ProductID,ProductName,Category/CategoryName

Using your library, I get back the same data but as `IEnumerable<IDictionary<string, object>>`
**Code**
```C#
ODataClient client = new ODataClient(new ODataClientSettings { UrlBase = "http://demos.telerik.com/kendo-ui/service/Northwind.svc/", OnTrace = (a, b) => { string.Format(a, b).Dump("Trace Event"); } });
var data = await client.For("Products").Expand("Category").Select("ProductID,ProductName,Category/CategoryName").FindEntriesAsync().Dump();
```
**Request URL (From trace event)**
http://demos.telerik.com/kendo-ui/service/Northwind.svc/Products?$expand=Category&$select=ProductID,ProductName,Category/CategoryName

Now if I specify a strongly typed class, I get back the same as the `IQueryable` did (with a little extra work):
```C#
var strongly = (await client
	.For<Product>()
	.Expand(x => x.Category)
	.Select(x => new { x.ProductID, x.ProductName, x.Category.CategoryName })
	.FindEntriesAsync())
	.Select(x => new { x.ProductID, x.ProductName, x.Category.CategoryName })
	.Dump();
```
My question to you is there a way to dynamically define a class and pass it into the `For<T>(...)` static method?

**Comment by object** [comment]
If you define the class dynamically, then it's not know at compile time and you can not use it in a typed version of syntax.

However, Simple.OData.Client also supports dynamic syntax where you don't need to define any entity classes. The code will be like this:

var dynamically = await client
    .For(x.Product)
    .Expand(x.Category)
    .Select(x.ProductID, x.ProductName, x.Category.CategoryName)
    .FindEntriesAsync();

Is this something that will work out for you?

**Comment by mskurnik** [comment]
Is there a simple way to convert this to a DataTable?  The only methods that I see for DynamicODataEntry are GetMetaObject and AsDictionary.  AsDictionary puts me right back to where I was and I am not sure what GetMetaObject  does as there are no examples for it.

**Comment by object** [comment]
Can you try one of these suggestions?

http://stackoverflow.com/questions/18923005/dictionarystring-object-to-datatable

http://stackoverflow.com/questions/15293653/coverting-list-of-dictionary-to-datatable

**Comment by mskurnik** [comment]
I already am doing something like that but it was bulky.  I ended up finding a solution.  Here is my post from StackOverflow.

I ended up finding [LatticeUtils AnonymousTypeUtils.cs][1] which creates an anonymous object from a Dictionary<string,object> to create an anonymous object.
I ended up modifying the first `CreateObject` method with the following

    public static object CreateObject(IDictionary<string, object> valueDictionary)
    {
      Dictionary<string, object> values = new Dictionary<string, object>();
    
      foreach (KeyValuePair<string, object> pair in valueDictionary)
      {
          if (pair.Value != null && pair.Value.GetType() == typeof(Dictionary<string, object>))
          {
              // Create object and add
              object o = CreateObject(pair.Value as IDictionary<string, object>);
              values.Add(pair.Key, o);
          }
          else if (pair.Value != null && pair.Value.GetType() == typeof(List<IDictionary<string, object>>))
          {
              // Get first dictionary entry
              IDictionary<string, object> firstDictionary = ((IEnumerable<IDictionary<string, object>>)pair.Value).First();
    
              // Get the base object
              object baseObject = CreateObject(firstDictionary);
    
              // Create a new array based off of the base object
              Array anonArray = Array.CreateInstance(baseObject.GetType(), 1);
    
              // Return like the others
              values.Add(pair.Key, anonArray);
          }
          else
          {
              values.Add(pair.Key, pair.Value);
          }
      }
    
      Dictionary<string, Type> typeDictionary = values.ToDictionary(kv => kv.Key, kv => kv.Value != null ? kv.Value.GetType() : typeof(object));
    
      Type anonymousType = CreateType(typeDictionary);
    
      return CreateObject(values, anonymousType);
    }

If you strip out all of the unused methods, comments, and variables like `mutable` I ended up with 160ish lines of readable code.

In order to read the data I am still using Simple.OData.Client to get my data but I am serializing the object to JSON, creating the anonymous object, and then deserializing everything back into an `IEnumerable`.  With this I am able to process 1000 records from my OData service in about 0.35 seconds or so.

    // Get Data
    ODataClient client = new ODataClient(new ODataClientSettings { UrlBase = "http://demos.telerik.com/kendo-ui/service/Northwind.svc/", OnTrace = (a, b) => { string.Format(a, b).Dump("Trace Event"); } });
    IEnumerable<IDictionary<string, object>> data = await client
    	.For("Products")
    	.Expand("Category,Order_Details")
    	.Select("ProductID,ProductName,SupplierID,CategoryID,QuantityPerUnit,UnitPrice,UnitsInStock,UnitsOnOrder,ReorderLevel,Discontinued,Category/CategoryName,Order_Details")
    	.FindEntriesAsync();
    
    // Convert to JSON
    string json = JsonConvert.SerializeObject(data);
    
    // Create anonymous type/object
    object anonymousObject = AnonymousClassBuilder.CreateObject(data.First());
    
    // Deserialize into type
    IEnumerable enumerable = (IEnumerable)JsonConvert.DeserializeObject(json, anonymousObject.GetType().MakeArrayType());

I might end up creating a Fork of Simple.OData.Client and adding this to it so I don't have to serialize the object back to JSON and then back to an object.


  [1]: https://github.com/dotlattice/LatticeUtils/blob/master/LatticeUtils/AnonymousTypeUtils.cs
