### ISSUE TITLE
DateTime converison

### ISSUE THREAD

**Issue by yang-** [object/Simple.OData.Client#89]
I have noticed that you have changed the formatter to the microsoft library in the current version of Simple.OData.Client. I was trying to send patch request to odata service with datetime in the payload and the datetime string format in the request is 2015-03-10T00:00:00+00:00. However, my service is like `http://services.odata.org/V3/OData/OData.svc/Products?$format=json`, whose datetime format is yyyy-MM-ddTHH:mm:ss. Is there anyway to set the formatter to ignore the timezone or force the formatter to convert datetime to yyyy-MM-ddTHH:mm:ss string?

**Comment by object** [comment]
Hi,
I checked the ODataMessageWriterSettings properties, and the only thing that affects DateTime format is OData protocol version. For example, if I set OData version to V2, then it converts datetimes to numbers, i.e. "ReleaseDate": "\/Date(1426016517752)\/", and when the version is set to V3 or V4, then it writes datetimes using ISO format: "ReleaseDate":"2015-03-10T19:41:15.8902869+00:00".

It seems to me that this is server's responsibility to understand ISO format including timezones. At least there doesn't seem to be a straightforward way to tweak the client that is based on Microsoft's EDM libraries.
