### ISSUE TITLE
Error when i try to Insert a new object

### ISSUE THREAD

**Issue by manusisnova** [object/Simple.OData.Client#90]
Hi I have a error when i try to insert object with derived type, my example explained better

[Fact]
        public async Task InsertExtendedProductWithCategoryByAssociation()
        {
            var category = await _client
                .For<Category>()
                .Set(new { CategoryName = "Test5" })
                .InsertEntryAsync();
            var product = await _client
                .For<ExtendedProduct>("Product/ExtendedProduct")
                .Set(new { ProductName = "Test6", UnitPrice = 18m, Category = category })
                .InsertEntryAsync();

            Assert.Equal("Test6", product.ProductName);
            Assert.Equal(category.CategoryID, product.CategoryID);
            category = await _client
                .For<Category>()
                .Expand(x => new { x.Products })
                .Filter(x => x.CategoryName == "Test5")
                .FindEntryAsync();
            Assert.True(category.Products.Count() == 1);
        }

The error is {"Value cannot be null.\r\nParameter name: source"}

StackTrace is 

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Simple.OData.Client.BoundClient`1.<InsertEntryAsync>b__c(Task`1 x)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sisnova.ODataServiceTest.MainPage.<btnNuevo_Click>d__13.MoveNext()

Can you help me?

Thanks in advance

**Comment by object** [comment]
Thank you for the comprehensive error description. I will check this out.

**Comment by object** [comment]
What version of Simple.OData.Client are you using? The latest (4.3.0)?

**Comment by object** [comment]
Also, how is ExtendedProduct defined in service metadata? Can you send me the metadata file?

**Comment by manusisnova** [comment]
Thank for you quickly reply, i am using 4.3.0 with OData V3 adapter.

My metadata file is big, but i create a new OData Service with 3 class to example, i send it, if you need something else feel free to ask

<?xml version="1.0" encoding="utf-8"?><edmx:Edmx Version="1.0" xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx"><edmx:DataServices m:DataServiceVersion="3.0" m:MaxDataServiceVersion="3.0" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><Schema Namespace="Simple.OData.ClientTest.EB_SimpleODataClient" xmlns="http://schemas.microsoft.com/ado/2009/11/edm"><EntityType Name="Simple_OData_ClientTest_DataModelCode_Product"><Key><PropertyRef Name="Oid" /></Key><Property Name="Oid" Type="Edm.Int32" Nullable="false" /><Property Name="ProductID" Type="Edm.Int32" /><Property Name="ProductName" Type="Edm.String" /><Property Name="UnitPrice" Type="Edm.Decimal" /><Property Name="CategoryID" Type="Edm.Int32" /><NavigationProperty Name="Category" Relationship="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Product_Category" ToRole="Category" FromRole="Simple_OData_ClientTest_DataModelCode_Product" /></EntityType><EntityType Name="Simple_OData_ClientTest_DataModelCode_ExtendedProduct" BaseType="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Product" /><EntityType Name="Simple_OData_ClientTest_DataModelCode_Category"><Key><PropertyRef Name="Oid" /></Key><Property Name="Oid" Type="Edm.Int32" Nullable="false" /><Property Name="CategoryID" Type="Edm.Int32" /><Property Name="CategoryName" Type="Edm.String" /></EntityType><Association Name="Simple_OData_ClientTest_DataModelCode_Product_Category"><End Type="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Product" Role="Simple_OData_ClientTest_DataModelCode_Product" Multiplicity="*" /><End Type="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Category" Role="Category" Multiplicity="0..1" /></Association><EntityContainer Name="Simple.OData.ClientTestService" m:IsDefaultEntityContainer="true"><EntitySet Name="Simple_OData_ClientTest_DataModelCode_Product" EntityType="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Product" /><EntitySet Name="Simple_OData_ClientTest_DataModelCode_Category" EntityType="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Category" /><AssociationSet Name="Simple_OData_ClientTest_DataModelCode_Product_Category_Simple_OData_ClientTest_DataModelCode_Category" Association="Simple.OData.ClientTest.EB_SimpleODataClient.Simple_OData_ClientTest_DataModelCode_Product_Category"><End Role="Simple_OData_ClientTest_DataModelCode_Product" EntitySet="Simple_OData_ClientTest_DataModelCode_Product" /><End Role="Category" EntitySet="Simple_OData_ClientTest_DataModelCode_Category" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>

**Comment by object** [comment]
I can't reproduce it on my test data, so I need an example.

**Comment by manusisnova** [comment]
Sorry for the delay,
I created a example but we use DevExpress Framework, i include references dlls, if you have problems to run, i can create example with EntityFramework.

https://dl.dropboxusercontent.com/u/38813484/Simple.OData.ClientTest.zip

For the WinRT Client, this is my code

        async void TestSimpleODataClient()
        {
            serviceUri = new Uri("http://localhost:7675/simple.odata.clienttest.svc/");
            ODataClientSettings odataClientSettings = new ODataClientSettings(serviceUri.AbsoluteUri);
            ODataClient odataclientTest = new ODataClient(odataClientSettings);
            var category = await odataclientTest
                .For<Category>("Simple_OData_ClientTest_DataModelCode_Category").FindEntryAsync();
            Product newproduct = new Product();
            newproduct.ProductName = "Test6";
            newproduct.UnitPrice = 18m;
            newproduct.Category = category;

            var product = await odataclientTest
                .For<Product>("Simple_OData_ClientTest_DataModelCode_Product/Simple_OData_ClientTest_DataModelCode_ExtendedProduct")
                .Set(newproduct)
                .InsertEntryAsync();
        }

Thanks for your help

**Comment by object** [comment]
I build the solution but since it requires a database I can't run the OData service. I guess the easiest would be if you send my just the metadata document (the one you get if you go to SERVER_URL/$medatada). I don't really need actual data to investigate this case.

**Comment by manusisnova** [comment]
Sorry i forgot attach database file, my metada file is here https://dl.dropboxusercontent.com/u/38813484/%24metadata%20example.zip
And SQL Server 2012 DataBase here
https://dl.dropboxusercontent.com/u/38813484/EB_SimpleODataClient.zip

**Comment by object** [comment]
Hi,

I double-checked your code and apparently you are not properly specifying base/derive type. Look at the example from the library tests:

            var ship = await _client
                .For("Transport")
                .As("Ship")
                .Set(new { ShipName = "Test1" })
                .InsertEntryAsync();

"For" clause must contain the name of the entity set  ("Product" in your case), and to specify that you are using specific type "ExtendedProduct" you should use the clause "As", i.e.

.For(""Simple_OData_ClientTest_DataModelCode_Product")
.As("Simple_OData_ClientTest_DataModelCode_ExtendedProduct")
.Set(newproduct)

Or you can also use typed version: For<Product>().As<ExtendedProduct>().

Can you try that and see if it works?

**Comment by manusisnova** [comment]
Works Perfectly, i didn't know the clause "As", Thanks a lot for your support
