### ISSUE TITLE
ExecuteAsEnumerableAsync possible bug

### ISSUE THREAD

**Issue by fastlink30** [object/Simple.OData.Client#93]
i have service that return IEnumerable
        [WebGet()]
        public IEnumerable<vLavor> GetLavoriByCodiDipe(string pkey)
        {
.....
IEnumerable<vLavor> lista = ....
return lista;
}

in some cases lista is null, when i read the values with
                   var cmd = await clientws
                        .Unbound<vLavor>()
                        .Function("GetLavoriByCodiDipe")
                        .Set(new { pkey = privatekey })
                        .ExecuteAsEnumerableAsync();

List<vLavor> ret = cmd.ToList();

i have ret with Count=1 and all values are set to null,
if cmd contains datas, conversion is done correctly

is my behaviour or bug?

thanks

**Comment by object** [comment]
Thank you for reporting the issue. I need more information in order to understand what's going on. Can you use Fiddler to record the generated URL and the response from the server? If it's possible to share this data, I'd like to have a look.

**Comment by fastlink30** [comment]
GET http://localhost/DroidService/DroidService.svc/GetLivelli?pkey=%2711f892f4-d16b-4710-9940-7367f7f72056%27&codicaus=%27CG%20%27&tipo_sla=1 HTTP/1.1
Host: localhost
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4


HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/xml;charset=utf-8
Server: Microsoft-IIS/7.5
X-Content-Type-Options: nosniff
DataServiceVersion: 1.0;
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Tue, 07 Apr 2015 07:13:20 GMT
Content-Length: 187

<?xml version="1.0" encoding="utf-8"?><GetLivelli xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" />


hope is enoug

**Comment by fastlink30** [comment]
if i edit the text on the previos message i see correctly the text, after saved is showed different and loose some lines, i can send you file with email? or there are possibility to attach file?

**Comment by object** [comment]
Please send me the file to vagif.abilov@gmail.com. It will also help if you include service metadata file (the response you get if you go to http://localhost/DroidService/DroidService.svc/$metadata.

**Comment by fastlink30** [comment]
email sent

**Comment by object** [comment]
I've just pushed version 4.3.2. Should fix the issue.
