### ISSUE TITLE
Single download metadata

### ISSUE THREAD

**Issue by jdluzen** [object/Simple.OData.Client#94]
I'm trying to avoid downloading the metadata on the first method call of every instance. Is there a way I can clone the metadata, or share a single instance among threads? One download per application instance is fine I mean.

**Comment by object** [comment]
Metadata should be downloaded once per AppDomain, because once it's downloaded it is inserted into a static dictionary with service URL as a key. Are you experiencing multiple calls to metadata? If so I would like to know more about it in order to reproduce (and fix) this behavior.

**Comment by Fabian-Schmidt** [comment]
I had an issue that the metadata was downloaded twice in a multithreading scenario, seen in Fiddler.
When i start multiple download tasks on the same odata client class istance.
Should I create an example console application for it?

**Comment by object** [comment]
Yes please. I will appreciate a sample that reproduces this behaviour.

**Comment by Fabian-Schmidt** [comment]
I have uploaded an [example application](https://github.com/Fabian-Schmidt/Simple.OData.Client.Playground/tree/master/Simple.OData.Client.Playground.MultiLoadOfMetadata).
I have also captured an example [Fiddler trace](https://raw.githubusercontent.com/Fabian-Schmidt/Simple.OData.Client.Playground/master/Simple.OData.Client.Playground.MultiLoadOfMetadata/FiddlerExample.saz).
![Screenshot of Fiddler trace](https://raw.githubusercontent.com/Fabian-Schmidt/Simple.OData.Client.Playground/master/Simple.OData.Client.Playground.MultiLoadOfMetadata/FiddlerExample.png)

The code is starting the download of two entities at the same time without waiting for the first one to finish.
```C#
//Init the Client
var client = new Simple.OData.Client.ODataClient("http://services.odata.org/V4/TripPinServiceRW");

//Init two task to load Photos and People entities.
var photosTask = client.For("Photos").FindEntriesAsync();
var peopleTask = client.For("People").FindEntriesAsync();

//Wait for the Tasks.
System.Threading.Tasks.Task.WaitAll(photosTask, peopleTask);
```

**Comment by object** [comment]
Then I understand why this is hapenning. Both operations start before the metadata document is requested and insterted into the metadata cache, therefore both of them request metadata. There are two options to deal with this:

1. await for the first operation to be completed or an an extra step that requests metadata string (GetMetadataAsString). In either case, it will slightly slow down the application startup but ensure that metadata is requested only once.

2. Wait until the version 4.4 is released (within a day or two), it will have a new property ODataClientSettings.MetadataDocument that you can use to preload the copy of your metadata. Then the client will not make extra calls to obtain metadata.

**Comment by object** [comment]
The version 4.4 is out now with support for MetadataDocument property in ODataClientSettings. Please check it out.
