### ISSUE TITLE
Can this library be used to generate the request url only?

### ISSUE THREAD

**Issue by dradovic** [object/Simple.OData.Client#99]
I was looking for a library that could translate a C# filter expression into a proper OData query string. Simple.OData.Client certainly needs to do this internally. My question is: is this functionality somehow exposed? Can I use it to get an OData request URL without actually fetching the objects?

**Comment by object** [comment]
Sure, that's possible. Here is an example:

            var command = _client
                .For<Product>()
                .Filter(x => x.ProductID == 1L);
            string commandText = await command.GetCommandTextAsync();
            Assert.Equal("Products(1L)", commandText);

**Comment by dradovic** [comment]
Thanks. I've tried that but I don't see any overload of `GetCommandTextAsync` without parameter. They all require a `collection` of type string (what is this?) and then either an `Expression` or a `ODataExpression`.

Can you please help me out or point me to some documentation?

**Comment by dradovic** [comment]
Thanks. It seems like `GetCommandTextAsync` is actually already firing a request. I was more looking for something that can be called "offline". Does that make sense?

**Comment by object** [comment]
No, it doesn't fire the request for the given command, but it needs to make a single request to fetch metadata document. For simple queries it's possible to generate the URI without knowing metadata, but in general case knowing service metadata is necessary. I can think of the way of providing metadata as a local file, so the client doesn't need to make a network roundtrip.

**Comment by object** [comment]
The version 4.4 (coming in a day or two) will have ODataClientSettings.MetadataDocument property that you can use to initialize with the service metadata. Then it will not make an extra call to retrieve a metadata document while executing GetCommandTextAsync.

**Comment by dradovic** [comment]
I see. Thank you very much for your time and your wonderful library.

**Comment by object** [comment]
And the version 4.4 is out with support for MetadataDocument in ODataClientSettings.

**Comment by teeberryu** [comment]
Can this be done without MetadataDocument (and ODataController)?
I'm trying to use GetCommandTextAsync() in order to call a method with OData support (in a ApiController, not ODataController) which looks like this: 

public Object Get(ODataQueryOptions<ProblemDTO> oDataOptions)

Then in an MVC Controller I'm calling the api service via HttpClient, after generating oData query string via ODataClient:

var command = oDataClient
            .For<ProblemDTO>()
            .Filter(x => x.ProblemID == 1);
string commandText = await command.GetCommandTextAsync();

I really like the LINQ support provided by the oDataClient and OData querying power, is there any possibility to user them without MetadataDocument?

**Comment by rekosko** [comment]
But still, can't we just use it with simple:

Expression<Func<T,bool>> expression = ...
var string = expression.GiveMeThatODataString(); // ?

I also need a way to translate my linq expression to odata string and nothing else.
Is it possible somehow with this library?

**Comment by watfordgnf** [comment]
@rekosko you're specifically looking for the translation of a filter expression? In any case the expression it generates would be based on the entities involved. You could remove the base URL from the generated command text.

**Comment by cbfrank** [comment]
I have the same requirement as rekosko, I would like to just translate an Expression<Func<T,bool>> to a odata query string. but before the demo code can work, I need to create an ODataClient with a valid url that host an odata api, if I specify an url like "127.0.0.1", the GetCommandTextAsync will throw HttpRequestException. can we split the GetCommandTextAsync as an mini tool function?

**Comment by watfordgnf** [comment]
@cbfrank to generate it, it needs the metadata for the service. Would your client have the metadata locally?

**Comment by cbfrank** [comment]
@watfordgnf sorry, no it doesn't have. actually, the web api is not an odata standard api, it just have a "Get" method which support query string of odata format.  this is why I can't provide any url when creating ODataClient.

**Comment by watfordgnf** [comment]
Without metadata we cannot properly generate the OData expression.

**Comment by cbfrank** [comment]
@watfordgnf I see. Maybe I can try to create a metadata manually, and then use the GetCommandTextAsync . Is this a possible solution?

**Comment by watfordgnf** [comment]
If `GetCommandTextAsync()` does not use a local metadata document you can open a bug and we'll get a fix in for that.
